### ISSUE TITLE
Orvis: Password Protected Portfolio Projects different in appearance and behavior when hovered

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#106]
1. Publish Portfolio Projects with featured images and set one as password protected.
2. Go to the /portfolio/ page and hover the password protected post and also one that is not password protected.

Screenshot: [https://cldup.com/-bzudl_Mr8.png](url)

Result: The password protected post looks different and also has no hover effect.

Expected: Same layout and hover effect as non-password protected post.

* User report: [https://wordpress.org/support/topic/orvis-password-protected-projects-break-hover-animation/#post-10200889](url)

* User's site: Not provided

I don't think this is actually a bug, and might be more of an enhancement.

**Comment by thomasguillot** [comment]
So there's actually a bug because the Featured Image shouldn't be displayed if it's password protected. 

The style of a password protected project should be the same as a project without a featured image: white border (goes slightly grey on hover) with Title and category:

![](https://cldup.com/yHN0Ieog91.gif)

**Comment by thomasguillot** [comment]
PS: Orvis is not maintained on GitHub but I have since fixed the issue on wpcom and I will generate a new zip for wporg
