### ISSUE TITLE
Redhill: Link Missing Style

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1113]
## Steps to replicate

1. Create a new page on your site
2. Add the "Media & Text" block on it
3. Add a hyperlinked text on the Text area of the block
4. Publish the page
5. Activate the Redhill theme

## Result

The link on this block isn't being highlighted, as follows:

![Links](https://user-images.githubusercontent.com/16104522/61584030-7f4f1f00-ab17-11e9-95bd-cef2f07a8d4c.png)

## Expected

For the link to highlight as it does on a Paragraph block.

* User report - ticket: #2194551-zd

**Comment by thomasguillot** [comment]
Hi @carinapilar, this should now be fixed 😊

Also

* 745a0b8
* fa9df39
* be4d855

**Comment by iamtakashi** [comment]
@thomasguillot Could you make PRs when you make a change to what's in production so that we can review and discuss the approach? I don't think I'd agree with the approach you took. I'd keep the style (inherited link text colour), but I'd make it's only applied to when background colour is added to either the background of the block or the paragraph.

**Comment by catkit** [comment]
I understand this hasn't been published yet to production, so once it is let us know so we can tell user, please. Thanks.

**Comment by iamtakashi** [comment]
@carinapilar @catkit The fix to add underline to text links has been deployed.
