### ISSUE TITLE
Sela: post formats available but do not work. 

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/themes#112]
1. Add Sela to a test site
2. Create a new standard post and publish
3. Create additional posts using the different post formats and publish. 

I expected that the post formats would work since they are available in the editor. 

The post formats are available for Sela but they do not work. There is no mention of post formats in the theme instructions https://wordpress.com/themes/sela/ 

* User report: https://en.forums.wordpress.com/topic/sela-theme-post-formats/#post-3101036
* Follow-up ticket: None. 
* User's site: theequotex.wordpress.com
* My Test site: freetestblogliz.wordpress.com

**Comment by alaczek** [comment]
Sela does support some of the post formats (aside, gallery, image, link, quote, video), but the differences are very subtle, for example:
* link post format title links directly to the URL mentioned in the post and has an icon after the title
https://cloudup.com/iusaDD9u755

* quote has a different text formatting then regular posts
https://cloudup.com/i4bKlBZFCPa

Aside, gallery, image, and video don't offer any distinguishable differences though. Since it's a quite old theme, we won't be adding any visual styles to distinguish post formats at this point. What would be the logical fix then? Add some sort of note to theme showcase page? If so, what could we say?

Also, post format are generally on the way out, and newer themes don't support them anymore. We released an update to Sela called [Dara](https://darademo.wordpress.com), that does not support post formats. If the user wants post format support, there are some older themes that offer that, but the level of support and visual presentation is individual for each theme.

**Comment by laurelfulford** [comment]
> What would be the logical fix then? Add some sort of note to theme showcase page? If so, what could we say?

Sela already doesn't mention post formats in the Showcase, and it doesn't have the tag, so I think we're good there.

@alaczek What do you think about removing the support for aside, gallery, image and video? At least that way, they won't show up as options in the theme.

**Comment by alaczek** [comment]
That could work! It won't do anything to the posts that already had a post-format set, right?

**Comment by laurelfulford** [comment]
I just gave this a trial run:

Weirdly, in Calypso, all the post formats are still there. I think this might be a caching issue (I can't replicate with another theme that only supports one); I can double-check the test site tomorrow to verify.

In /wp-admin, it will keep the supported Post Formats (link, quote), and if you have a different one selected (gallery), it will still list that there too when editing that specific post, at least as long as it's selected. WordPress hangs on to your post format choice, whether or not your theme supports them.

**Comment by laurelfulford** [comment]
It looks like Calypso only shows the supported post formats, even on posts that use a different format. But the format isn't actually changed, and is selected again in Calypso when you switch to a theme that supports them. So I think this is a safe update :)

**Comment by laurelfulford** [comment]
Updated in r48771-wpcom-themes.

**Comment by laurelfulford** [comment]
Commented on the forum thread and closed it.
