### ISSUE TITLE
Sketch: Too-long titles don't wrap on mobile, cover menu toggle

### ISSUE THREAD

**Issue by sarahfg** [Automattic/themes#120]
## Steps to replicate

- Create a really long one-word title for your site
- Add Sketch theme to your site
- Look at it as the screen width between ~300 and 400. 

## Result

A site with a long title without a break in the text doesn't work well with the mobile menu view. Because the text doesn't break up into smaller bits it appears over top the menu 

GIF of my testing site: https://cloudup.com/cFlzMwIYqmY
User's Screenshot on their site: https://miriammcclay.files.wordpress.com/2018/04/image-1.jpg

## Expected

The menu should move below the text sooner when the title is that long

* User report: #1130181-zen
* User's site: miriammcclay.wordpress.com

**Comment by alaczek** [comment]
Ah, yes. We run into this one whenever a theme displays mobile menu next to the site title :|

Unfortunately, there's not elegant, easy fix here. We could add `word-break: break-all`, which would force long words to break into two lines. But in most cases this is not desirable, since the word can be broken randomly, which doesn't look good. For this reason, I'd rather not do this. Making this sort of change in a live theme would also have impact on existing sites, which we try to avoid.

In this particular case, I'd suggest breaking up the title with a space (which is what they did already). Alternatively, the mobile menu could be pushed below with CSS, but it looks like the user doesn't have access to custom CSS :|

Sorry I don't have a better answer. Let us know if there's anything else we can do to help.
