### ISSUE TITLE
Varia: Normal font size is bigger than default size.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1239]
Currently, the normal size is actually bigger than the default. This is confusing, and I think it should be the same size as default size.

<img width="727" alt="Screen Shot 2019-08-10 at 16 38 44" src="https://user-images.githubusercontent.com/908665/62823840-c87e1600-bb8d-11e9-853d-327bc6b1114b.png">

**Comment by iamtakashi** [comment]
@allancole This make me wonder if we even need `size -> md` in Varia. Wouldn't it make more sense if `base` and `md` are the same or we get rid of `md` completely?

**Comment by allancole** [comment]
I can’t remember exactly why right now but I think we need to keep `md` and `base` so that the type scale covers all the sizes. If we remove `md`, I think we’d be skipping a size in the scale, which may not be bad,  but would wont to research this more before making a call. 

For now I think your #1240 pr looks good so we can go ahead and merge that and maybe start a new ticket for the "md" font size.

**Comment by iamtakashi** [comment]
Yes there is no rush to make a call. I agree skipping it won't be good. Would be good to audit Varia to make sure that where the font size is set to "md" is actually the size it intends to.

**Comment by allancole** [comment]
> Would be good to audit Varia to make sure that where the font size is set to "md" is actually the size it intends to.

Good point. I think I’ll end up doing various audits when we start writing the docs. But a general audit on all the variables would be worth while too 👍
