### ISSUE TITLE
 Shoreditch: Like buttons appear on Panel Page Template in spite of page settings 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#13]
This issue was originally reported by @chad1008 in 4202-wpcom-themes:

The Like buttons appear on the Panel Page templates in spite of page settings, except on the front page.

## Steps to replicate

1.  Activate Shoreditch
2. Make sure like buttons for the site are turned on under My Site > Sharing
3. Create a page with the Panel Page template
4. Give that page a few child pages
5. Make sure the Like button is turned off for each individual Child Page
6. View the Parent Panel Page - like buttons appear on the child panels
7. Visit My Site > Customize > Static Front Page and set your panel page as the site's front page
8. View the front page - like buttons are gone
9. Reset the front page and view the panel page - like buttons reappear.
10. Disable the site like buttons setting and view the panel page again. Like buttons disappear. 

* User report: 2918760-t
* User's site: https://admagicmedia.com/services/

**Comment by sixhours** [comment]
I am able to reproduce this, though it happens regardless of whether the Panel Page is set to the home page or not.

I suspect this is similar to Automattic/jetpack#8990 , in that Likes settings are tied into the page's main query rather than the subsequent child page query.

I'm going to test this theory by applying a similar setup to Affinity, which also uses a separate query on a page to build out the contents.

**Comment by sixhours** [comment]
I confirmed that the same thing happens in Affinity, with the following steps to reproduce:

1. Activate Affinity.
2. Make sure like buttons for the site are turned on under My Site > Sharing.
3. Create a couple of Pages, and turn Likes off for those pages.
4. Set a Static Front Page under Customize -> Homepage Settings.
5. Go to Customize -> Theme Options -> Panel 1 and select one of the pages created in step 3. 
6. Go to Customize -> Theme Options -> Panel 2 and select the other page created in step 3.
7. Publish changes and view your home page. The Likes settings for the individual child pages are not respected; you'll still see Likes enabled, even though they've been turned off for those child pages.

The individual page Likes settings are overruled by the global Likes settings because we're displaying those pages outside the main query. This gets even more complicated when you set a static front page, since that has its own global Likes settings as well.

This is not specific to these themes; it will happen any time we display content outside the main query (I've seen similar tickets with bugs when Likes are enabled/disabled on Featured Content, for example). 

I'm going to move this to a Jetpack ticket. The workaround for now is to turn off Likes globally, or to hide them using Custom CSS.

**Comment by sixhours** [comment]
Reported in Automattic/jetpack#9002 and included user information for follow-up.
