### ISSUE TITLE
Afterlight: Soundcloud icon not visible. Suggest using Jetpack icons instead of Genericons

### ISSUE THREAD

**Issue by nagpai** [Automattic/themes#130]
## Steps to replicate

* Install theme on test site
* Browse to Customizer >> Menu >> Create a menu and add it to Social Menu position
* Add a SoundCloud link 

## Result

* You will notice the generic icon rather than the SoundCloud icon.
* Change the theme to Radcliffe2 and you see that SoundCloud icon does appear

## Expected

I would expect the SoundCloud icon to show up, which does not, since the theme uses Genericons. I checked[ this issue on Genericons repo](https://github.com/Automattic/Genericons/issues/54) that mentions no more Social icons within that library.

* User report: [#1153935-zen](https://woothemes.zendesk.com/agent/tickets/1153935)
* User's site: http://lazonz.com

**Comment by alaczek** [comment]
We can't rely on Jetpack here, since our themes are used on self-hosted sites as well that may or may not have it installed. I thought that maybe Jetpack is using [Social Logos](https://github.com/Automattic/social-logos)], in which case we could maybe swap them out with Gridicons. It looks like Social Logos don't include Soundcloud though, so Jetpack must be using something custom. 
For reference, here are the social menu icons used in Jetpack: https://github.com/Automattic/jetpack/tree/1f4507e0cbfdbdec3eadc099a03c2799fd0f0f2c/modules/theme-tools/social-menu

**Comment by thomasguillot** [comment]
The only option I can see here is removing the current social menu and use Jetpack Social Menu with SVG which includes Soundcloud `add_theme_support( 'jetpack-social-menu', 'svg' );` https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/social-menu/social-menu.svg?short_path=2cc0da9#L97

That being said, if we change the menu now, it will affect current users: the menu IDs/names are different so users would lose their menus.

So this looks like a `wontfix` to me.
