### ISSUE TITLE
Exford: Menu button still displays on mobile if primary menu is empty

### ISSUE THREAD

**Issue by lakellie** [Automattic/themes#1331]
## Steps to replicate

1. Create a new empty menu with no pages 
2. Assign the menu to the primary location

## Result

The menu button displays on mobile, and can be clicked, but nothing displays when you do: https://cld.wthms.co/Ijt0HM

## Expected

For the menu button to be hidden if the menu does not contain any items

Issue does not occur if no primary menu is assigned at all; it only occurs if an empty menu is assigned as primary.

* User report: #14786754-hc

**Comment by iamtakashi** [comment]
I don't understand the need for an empty menu assigned as primary. Please advice the user to not to have a menu at all.

**Comment by lakellie** [comment]
Hi @iamtakashi! Thanks for taking a look.

I hope you don't mind me sharing my perspective on this as an HE. Your suggestion, to advise the user not to have a menu at all, requires the user to actually contact us first, then the HE taking the time to determine why the menu button isn't working each time this question comes in.

Whereas if the issue is fixed with the theme, it's a one-time fix and no one will have to ever contact us about it again. It saves a lot of time in the long run (and user frustration too). Of course there isn't a need for a user to have an empty menu versus not having a menu at all, but many WordPress.com users don't understand the difference.

I now see it appears this issue isn't specific to just Exford but actually to Varia, which means it will impact _all_ our new themes. That being the case, I do think logically it makes sense to hide the menu button instead of displaying a seemingly broken button on mobile if there is an empty menu assigned. 

If you'd still like to leave the issue closed that's fine but wanted to share my perspective here. Thanks!

**Comment by iamtakashi** [comment]
@lakellie Thanks for sharing your perspective. 

It's a matter of priority. As you can imagine, we can't spend time to work on every possible edge case like this. There are more things that many people can benefit from and that need to be worked urgently. Also, if we were adding a piece of code to prevent every possible edge case because it's a "one-time fix", themes would be bloated, slow, and harder to work on.

I'm sorry for my initial response that came across as non-empathetic and blunt. We can revisit to it if this becomes a common issue, but I don't think this needs to be fixed at this moment.
