### ISSUE TITLE
String of additional Save Save Save text appending to posts

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/themes#136]
## Steps to replicate
1. Install Pinterest on the safari browser
2. Publish a post with a photo
Note: User is using the [Nishita theme](https://wordpress.com/theme/nishita) but says a few other bloggers she knows have reported the same issue with different themes.

## Result
I was not able to replicate the issue. Everything worked normally on my end.

## Expected
When publishing the post (with photo) strings of 'Save' text would append to the bottom of her post.

Upon removing the Pinterest extension, the issue stopped for her and two other bloggers.

* User report: [1151789](https://woothemes.zendesk.com/agent/tickets/1151789)
* User's site: https://travelsandtrifles.wordpress.com/

**Comment by laurelfulford** [comment]
I also can't recreate this issue. I:

1. Installed the Pinterest "Pin It" button browser extension to Safari (https://safari-extensions.apple.com/details/?id=com.pinterest.extension-HWZFLG9PNK)
2. Applied the Nishita theme
3. Published a post with a photo

I could not see "Save" in Calypso, or in the preview of the post after publish (I'm not exactly sure where it was for the user).

Given that this is a retired theme, and two of us can't recreate the issue, I'm going to close this issue. If it does crop up again, I suspect it's not theme-related, since the user has reported it's happening with multiple themes.

**Comment by chickenn00dle** [comment]
Thank you!!!
