### ISSUE TITLE
Varia: block inside wide width block is narrower than it should be.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1394]
I've noticed that a block inside a wide width block is narrower than it should be. Notice the red circles in the screenshot below. That padding should be the same as the vertical ones as you can see in the second screenshot. It's narrower by 32px (16px each side.)

<img width="1118" alt="Screen Shot 2019-09-04 at 23 25 43" src="https://user-images.githubusercontent.com/908665/64298399-51118b80-cf6d-11e9-9e90-92da789dd111.png">

This seems to be caused by the following rule:

```
.entry-content [class*="inner-container"] {
  max-width: inherit;
}
```

If I disable that in the dev tools, it would look as it should be. But I'm assuming we need this for some reason. @allancole what is this for? If this is absolutely necessary, what can we do to fix this?

<img width="1058" alt="Screen Shot 2019-09-04 at 23 38 38" src="https://user-images.githubusercontent.com/908665/64298410-58389980-cf6d-11e9-8b08-f38c2a73d693.png">

**Comment by allancole** [comment]
> But I'm assuming we need this for some reason.

Thats a good question. I don’t remember but let me do some investigating to see…

**Comment by allancole** [comment]
Yeah, @iamtakashi it looks like we don’t need that `max-width: inherit` line at all any more. Must’ve been left over from the refactor. I’m gonna remove it. 

But I also noticed another related issue we may want to revise.  

**Editor:**

![image](https://user-images.githubusercontent.com/709581/64375866-e0ae4d00-cff4-11e9-8d34-0bead6567014.png)

**Frontend:** 

![image](https://user-images.githubusercontent.com/709581/64375970-2834d900-cff5-11e9-996c-cf19d34c38c7.png)

Notice how the editor styles make the “Normal > Full” block stretch to the edge and ignore the left/right padding from the parent’s `.has- background-color` utility class. Do you think we should make nested `.alignfull` blocks stretch to the edge like it does in the editor? This only happens when the parent Block has a background color which makes me feel like what we have on the frontend is a better expected behavior. Let me know what you think.

**Comment by iamtakashi** [comment]
> it looks like we don’t need that max-width: inherit line at all any more. Must’ve been left over from the refactor. I’m gonna remove it.

👍

> But I also noticed another related issue we may want to revise.

Oh, nice catch. I agree that what we see in the front-end makes more sense.
