### ISSUE TITLE
Harmonic: Intermittent Inability to Click the Mobile Menu

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/themes#141]
## Steps to replicate

1. Open jasonsoroski.net on mobile.
2. Tap on "Menu" (to the upper right) to open the menu up.

## Result

The menu didn't open when I first tapped it. If I navigate round the window (scroll up/down, view my notifications, etc) then go back to tap the menu again, it'll work the second time. 

I tested this on an Android Pixel, using Chrome.

## Expected

I expected the menu to open up when first tapped.

* User report: 283762-h
* User's site: jasonsoroski.net
* Similar reports for this theme from the past: 2736-wpcom-themes, 2769-wpcom-themes

**Comment by laurelfulford** [comment]
Since Harmonic's retired (and has rather complex JavaScript), I'm going to close this as a wontfix. It's not ideal, but it's better than trying to make changes to the theme to fix this, and risk accidentally introducing new issues.

@SiobhyB could you please follow up with the user and let them know? And if possible, encourage them to switch to a newer theme? Thanks in advance!

**Comment by SiobhyB** [comment]
@laurelfulford: Thanks for looking into this! The user spotted that the theme was retired and ended up switching themselves.
