### ISSUE TITLE
Shawburn: Featured Image in Page not Displayed

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#1443]
## Steps to replicate

- Open a page and add a featured image, then Update or Publish page. 

<img width="1408" alt="Screen Shot 2019-09-28 at 3 28 34 PM" src="https://user-images.githubusercontent.com/36863633/65817222-ff26f300-e204-11e9-85e1-231d5538d9dc.png">

## Result

- Featured image is not be displayed in the page. 

- Even with _Enable the Jetpack Mobile theme > Show featured images_ enabled or not, the featured image still won't be displayed in the page.

<img width="1001" alt="Screen Shot 2019-09-28 at 3 31 52 PM" src="https://user-images.githubusercontent.com/36863633/65817239-1f56b200-e205-11e9-82c1-7ff446294132.png">

## Expected

The featured image in the page should be displayed. 

* User report: #15476272-hc
* Follow-up ticket: #2384811-zd

**Comment by nielslange** [comment]
@kspilarski No sure if it's a bug or a feature. Until now that page template didn't support displaying a featured image. I fixed this with https://github.com/Automattic/themes/pull/1452.

@allancole and @kjellr As `Shawburn` is a child theme of `Varia` I had to apply the fix there. Did it happen on purpose that pages do not show featured images or did it happen accidentally? If it happened on purpose wouldn't it be a good idea to remove the featured image section from the pages to avoid confusion?

**Comment by allancole** [comment]
Ahh yeah, this is a bit of an oversight. Thanks for catching it @nielslange & @kspilarski.

@takashi, I _think_ I’m leaning toward only supporting featured images on posts and removing them from Pages but I can also see a good argument for keeping them for everything. What are your thoughts?

**Comment by nielslange** [comment]
> @takashi, I think I’m leaning toward only supporting featured images on posts and removing them from Pages but I can also see a good argument for keeping them for everything. What are your thoughts?

@allancole & @iamtakashi While this is entirely your decision whether to keep or to remove the featured image for pages, I'm afraid that removing them can cause confusion for some customers.

**Comment by iamtakashi** [comment]
@allancole @nielslange Featured image is another thing that a user can't control the appearance directly, and in this Gutenberg era, it's becoming a thing from the past. I even want to get rid of it completely for both posts and pages. But I can understand the role in particularly index and archive pages with posts, but it doesn't make sense to display it on pages where a user has _almost_ full control (the title isn't a block yet though). 

The main part of the issue is that the theme not displaying featured images on the front of the site at all despite a user can add it in the editor. Therefore, I'd only add the featured image support to posts and disable it from pages including the UI in the editor.

`add_theme_support( 'post-thumbnails', array( 'post' ) );`

If they can't add featured image in the _page_ editor, it makes sense that it doesn't show up on the page on the front of the site.

**Comment by nielslange** [comment]
Shall I update my PR or will you take care of this issue, @iamtakashi?

**Comment by iamtakashi** [comment]
@nielslange my suggestion above needs to be implemented in Varia to remove the featured image support on pages from all the child theme, and it deserves a ticket for it. 

I don't think we need to do anything in Shawburn at this moment.

**Comment by iamtakashi** [comment]
But let's keep this open for now.

**Comment by nielslange** [comment]
> @nielslange my suggestion above needs to be implemented in Varia to remove the featured image support on pages from all the child theme, and it deserves a ticket for it.
> 
> I don't think we need to do anything in Shawburn at this moment.

I wasn’t planning on implementing this into Shawburn but into Varia. Guess, I’m just slowing you down with my comments and PRs here. Won’t bother you in the future. 😉

**Comment by iamtakashi** [comment]
> Won’t bother you in the future.

@nielslange Just to be clear, don't take my comments as discouragement in any way. I'm just trying to be clear in my opinion :)
