### ISSUE TITLE
Child configurations

### ISSUE THREAD

**Issue by nosolosw** [Automattic/themes#1519]
While working on https://github.com/Automattic/themes/pull/1516 I've noticed a couple of configurations that are inconsistent. Not sure how relevant it is but want to point it out:

- `config-separator.width` is present in `blocks/separator/config` as well as the `_config-child-theme-deep.scss` file of these themes: coutoire, leven, morden, redhill, rockfield, shawburn, stow, stratford - it's not defined in the rest of the themes.
- `config-footer.font.line-height` is not present in redhill's `_config-child-theme-deep.scss`

**Comment by nosolosw** [comment]
cc @allancole @iamtakashi

**Comment by allancole** [comment]
WOW, what a catch! You’re right that the variable arrays should match between `child-theme-name/sass/_config-child-theme-deep.scss` and `varia/sass/abstracts/_config-global.scss`(+ its includes). 

It looks like when we added `config-separator.width` we added it to the partial but forgot to add it to `varia/sass/child-theme/_config-child-theme-deep.scss` which is the starter array that we copy into _newly_ generated child themes with the latest Varia improvements. 

If child themes were overriding either the `height` or `width` variable, they’d throw an error while compiling. But since they aren’t, Varia just skips the child-theme’s `config-separator.width` array entirely and uses it’s own so no errors pop up. 

This is definitely worth a fix, just in case a future theme tries to override the separator variable. I’ll sort it out. 

If this were done entirely with `css-custom-properties` instead of Sass variables + css-custom properties, we wouldn’t need to break up and separate the Sass-variable arrays and their partials like this. Hoping we can move in that direction sooner than later.
