### ISSUE TITLE
Goran: Logo image isn't displayed when saved as draft in Customizer

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#160]
## Steps to replicate

1. Set a logo image via Customizer > Site Identity > logo
2. Save changes as draft
3. Close Customizer
4. Open it again

![goran-bug](https://user-images.githubusercontent.com/3521683/41322793-fe4b1c14-6e78-11e8-8019-ca4e6ae85153.jpeg)

## Result

The logo image appears in the Site Identity panel, but doesn't show in the site preview. 

## Expected

The logo should appear in the site preview. I could reproduce the issue at my test site. I also tested it  with Barkerville 2 but it only happened with Goran.

* User report: #4294475-hc
* Follow-up ticket: #1218356-zd
* User's site: https://romantorreto.wordpress.com/wp-admin/customize.php

**Comment by laurelfulford** [comment]
I tested the user's site -- it didn't have a logo applied, and when I tried adding one in the Customizer, it did appear in the preview. I also couldn't recreate it on my own test site.

My best guess is the issue was a weird blip, so I'm going to close this as "worksforme", but if the issue crops up again it can be reopened!
