### ISSUE TITLE
Cubic: Tiled Gallery block & CoBlocks Masonry block layout issues

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#1664]
The Tiled Gallery block and CoBlocks Masonry gallery block both have layout issues in the Cubic theme.

## Steps to replicate

Add a Tiled Gallery block to a page, resize the browser to see the issue:

## Result

The image layout is incorrect:
Video: https://cld.wthms.co/5fYKbU

## Expected

Example from another theme of how it should resize correctly:

Video: https://cld.wthms.co/IbV7vu

* User report: 16220616-hc
* Follow-up ticket: 2489284-zen

**Comment by mishivee** [comment]
Reported here as well: 17955066-hc

**Comment by KokkieH** [comment]
Another in https://wordpress.com/forums/topic/cubic-theme-masonry-gallery-display-issue/

**Comment by mdrockwell** [comment]
Another report here: 11067847-hc

**Comment by liviopv** [comment]
I got a related issue with the Tiled Gallery on Cubic.

When the block is set to Square Tiles, it will render the images as tall rectangles on the front end, instead of squares.

**Editor**

![Screenshot](https://d.pr/i/YL7xDn+)
Screenshot: https://d.pr/i/YL7xDn

**Front end**

![Screenshot](https://d.pr/i/PBw6Tm+)
Screenshot: https://d.pr/i/PBw6Tm

User report: #2910

**Comment by csonnek** [comment]
User in https://wordpress.com/forums/topic/gallery-tiles-stretched/ has the same issue that @liviopv reported: 

![tiled](https://user-images.githubusercontent.com/2814452/120366287-17ea8480-c2d5-11eb-8514-8257bfd8f282.jpg)

**Comment by happychait** [comment]
Another in 4607665-zen

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on the newer sites.

Slack ref: p1651059474355319-slack-C029FM1EH

cc @jeffikus
