### ISSUE TITLE
Twenty Twenty: GlotPress project is missing

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1753]
## Steps to replicate

1. Create a site in Portuguese
2. Create a new page and set as the front page
3. Check the "To the top ↑" link on the bottom right

## Result

The "To the top ↑" doesn't get translated to Portuguese.

## Expected

To also be translated to Portuguese.

## More info
The string is already translated on WordPress.com and WordPress.org:
- https://translate.wordpress.org/projects/wp-themes/twentytwenty/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8432442&filters%5Btranslation_id%5D=66699401
- https://translate.wordpress.com/projects/wpcom/pt-br/default?filters%5Bterm%5D=To+the+top

**Comment by nielslange** [comment]
@carinapilar On https://translate.wordpress.org/projects/wp-themes/twentytwenty/ I see the following translation statuses:

- Portuguese (Brazil) → [100%](https://translate.wordpress.org/locale/pt-br/default/wp-themes/twentytwenty/)
- Portuguese (Angola) → [30%](https://translate.wordpress.org/locale/pt-ao/default/wp-themes/twentytwenty/)
- Portuguese (Portugal) → [15%](https://translate.wordpress.org/locale/pt/default/wp-themes/twentytwenty/)
- Portuguese (Portugal, AO90) → [0%](https://translate.wordpress.org/locale/pt/ao90/wp-themes/twentytwenty/)

And on https://translate.wordpress.com/projects/wpcom%2Fthemes%2Ftwentytwenty/ I see the following translation statuses:

- Portuguese (Brazil) → [100%](https://translate.wordpress.com/projects/wpcom%2Fthemes%2Ftwentytwenty/pt-br/default/)
- Portuguese (Portugal) → [41%](https://translate.wordpress.com/projects/wpcom%2Fthemes%2Ftwentytwenty/pt/default/)

As mentioned on https://translate.wordpress.com/projects/wpcom%2Fthemes%2Ftwentytwenty/pt/default/

> Note: These translations will only be activated on WordPress.com when 85% of the strings have been translated. Currently only 41% are translated.

Is it possible that you've accidentally selected Portuguese (Portugal) instead of Portuguese (Brazil)? When using the Twenty Twenty theme and select `pt-br - Português do Brasil` both on my DOTCOM and DOTCOM testing sites I see `Para o topo ↑`. I only see `To the top ↑` when selecting `pt - Português`.

**Comment by carinapilar** [comment]
Thanks for checking @nielslange! It seems it's all set now, the translation project was missing for the theme and was created after I opened this issue. I'm glad you confirmed that the translation is correct now, I can see it here too, I'll close this thread.
