### ISSUE TITLE
Varia: Default background of cover block makes some colors hard to see

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#1822]
## Steps to replicate
1. Activate any of the Varia child themes (tested with Maywood, Barnsbury, Mayland)
2. Open the editor and add a Cover block. Notice the default black background, and how it makes dark color swatches hard to see.

![image](https://user-images.githubusercontent.com/4550351/75403356-9b435a80-595b-11ea-86e2-4cc3f1ee70e4.png)
 
It looks like Varia overrides the default editor behaviour. This is how the initial state of Cover block looks like in Twenty Twenty:

![image](https://user-images.githubusercontent.com/4550351/75403463-f2e1c600-595b-11ea-843e-127f0a6d5538.png)

It would be great if we could replicate the transparent grey background for improved readability.

**Comment by nielslange** [comment]
@alaczek Given the basic design of the Varia theme, it seems to be a conscious decision that the cover block has a black background by default:

![#1822-frontend](https://user-images.githubusercontent.com/3323310/75429205-000ead00-597c-11ea-9bb1-cd448d47cd3c.png)

Therefore, instead of changing the background color I've added subtile borders to the selectable colors so that they can be recognized easily.

<table>
<tr>
<td>Before:
<br><br>

![#1822-before](https://user-images.githubusercontent.com/3323310/75429406-52e86480-597c-11ea-9af1-397474b3e940.png)
</td>
<td>After:
<br><br>

![#1822-after](https://user-images.githubusercontent.com/3323310/75429410-54b22800-597c-11ea-8746-b2198fd4180c.png)
</td>
</tr>
</table>

Please let me know if you still think that changing the background color is the better option.

**Comment by scruffian** [comment]
This is no longer an issue as we have changed the placeholder screen for cover blocks:

<img width="837" alt="Screenshot 2020-11-04 at 17 16 45" src="https://user-images.githubusercontent.com/275961/98143843-87280380-1ec1-11eb-9cb8-0ea19217bdcf.png">
