### ISSUE TITLE
 Blocks in Columns Off Screen in Multiple Themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#1848]
![image](https://user-images.githubusercontent.com/545779/76436220-f32f8780-6385-11ea-9e60-1a627066d586.png)

cc @iamtakashi @alaczek

**Comment by ianstewart** [comment]
Repeated with Independent Publisher 2.

![image](https://user-images.githubusercontent.com/545779/76436446-3b4eaa00-6386-11ea-9688-306b53ed36e6.png)

**Comment by ianstewart** [comment]
Libre 2 …

![image](https://user-images.githubusercontent.com/545779/76436614-7224c000-6386-11ea-8e53-0ef5434a6f3f.png)

**Comment by ianstewart** [comment]
Ixion …

![image](https://user-images.githubusercontent.com/545779/76436707-8bc60780-6386-11ea-92ba-fcc95c3b57c2.png)

**Comment by ianstewart** [comment]
The experience can be quite poor. The above screenshots were taken using the blocks in the Alves Home Page Layout. 

To reproduce the following use the Barnsbury home page layout in the Apostrophe 2 theme …

![image](https://user-images.githubusercontent.com/545779/76440352-bb2b4300-638b-11ea-8003-9445bfe65ac7.png)

**Comment by kjellr** [comment]
I'm pretty sure that none of these themes include Group block styles. Since Gutenberg does not provide any front end styles for that block, it's broken out of the box. 

A relatively quick fix for most of these should be a rule like: 

```
.wp-block-group.alignfull .wp-block-group__inner-container {
    max-width: 730px; // Whatever the theme's usual content width is.
    margin: 0 auto;
}
```

Though to be complete, we should add rules for the standard and `.alignwide` variants of the Group block too. Those tend to be a bit more complicated.

**Comment by davipontesblog** [comment]
For reference: https://github.com/Automattic/themes/issues/7174

**Comment by kjellr** [comment]
> A relatively quick fix for most of these should be a rule like:

I did a little more digging, and while that would fix some of these layouts, the one in the first screen shot (Alves) is due to having a wide-aligned block inside of a cover block, which introduces a whole separate can of worms. Considering the span of themes that this impacts, I think this would be a relatively complicated fix.

**Comment by davipontesblog** [comment]
@kjellr on my related issue on Automattic/themes#7174 it shows affecting any wide-aligned blocks nested within a Group block too. I agree that the impact of this is probably large, especially considering lots of our page layouts have this nesting going on, and as soon as users move away from these themes onto other classic wpcom themes... this ought to happen.
