### ISSUE TITLE
Varia: Line-height setting isn't respected in the editor

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1895]
Gutenberg added the line-height option for paragraph block 🎉The setting is respected on the front-end, but in the editor. It should match with the front-end.

<img width="1018" alt="Screenshot 2020-04-01 at 14 49 48" src="https://user-images.githubusercontent.com/908665/78145662-0edbfa00-7429-11ea-846e-0e6a02412eb9.png">

cc: @allancole @ianstewart @alaczek

**Comment by iamtakashi** [comment]
@kjellr Once this setting lands in WP.com, View squad is expecting to release more than few block patterns using big fonts that take advantage of this setting. I've noticed this is resolved in Varya, but can this be fixed in Varia and the child themes?

**Comment by kjellr** [comment]
@allancole + @jffng do you think the solution over in Varya could be ported over here pretty easily?

**Comment by jffng** [comment]
In Varya, I don't think we did anything special here to handle Gutenberg's new line-height feature, because as of 7.9.1 GB inserts an inline-style:

<img width="1097" alt="Screen Shot 2020-04-24 at 12 32 51 PM" src="https://user-images.githubusercontent.com/5375500/80235506-ca0e4200-8627-11ea-8219-9df0c8e7842d.png">

This would override any editor styles, unless `!important` is being set by Varia or the child theme 😄. @iamtakashi am I understanding the problem correctly?

**Comment by kjellr** [comment]
Ah yes — 7.9.1 hasn't been adopted on WP.com yet because of some other potential conflicts. So it could just be that this will get resolved once that is able to go live.

**Comment by iamtakashi** [comment]
Oh, nice. I guess I tested it too soon :D Thanks for the info!
