### ISSUE TITLE
Varia-based themes do not have color options. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#1910]
Varia-based themes do not currently support color palette customization via the Customizer (or via Gutenberg, but that won't be possible until Global Styles ships). In the meantime, this prevents users from making a relatively basic aesthetic adjustment to their website. 

_Example of a non-varia theme that does include color options, Independent Publisher 2:_ 

![image](https://user-images.githubusercontent.com/1202812/78826337-56293400-79af-11ea-8605-0b7c32544145.png)

**Comment by JoshuaGoode** [comment]
Thanks for bringing this up! This has been discussed since before these themes were launched. WPCOM FSE was to help with this but those plans changed. 

Internal references with feedback and instances where this has been an issue for users:
p7DVsv-76L-p2
p7DVsv-6Xi-p2

**Comment by lancewillett** [comment]
I believe Twenty Nineteen also needs color annotations.

**Comment by allancole** [comment]
Just to clarify, Twenty Nineteen does have its own theme-specific custom color control but it only changes the _primary_ color. We chose not to use color-annotations since they are not available in the Gutenberg editor (color-annotations only address the customizer and the frontend—they don’t address the Gutenberg editor).

**Comment by scruffian** [comment]
Closing in favour of https://github.com/Automattic/themes/issues/3038
