### ISSUE TITLE
PDF Embed block in Twenty Twenty

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#1919]
## Steps to replicate

1. Paste a PDF URL into a page or post.
2. This will convert (on the published final page) to an embedded visual PDF
3. On theme TwentyTwenty the embed though is cut off - Screenshot - https://d.pr/i/01phFY
But on Hever or Barnsbury it shows more but not all of the page - https://d.pr/i/zS5wZR

## Expected

To see the whole PDF embed as per - https://wpcomhappy.wordpress.com/2020/03/11/allow-visual-pdf-embeds-in-posts-and-pages/#comment-27974

* User report: 
#9943206-hc
#2875726-zd

**Comment by thesacredpath** [comment]
@rickmgithub, thanks for posting this. I discovered it when working on another PDF viewer bug yesterday. It led me to test some other themes to see if it was more than just Twenty Twenty. The themes I tested were the following, which did not have the issue.

- Lovecraft
- Dara
- Hever
- Maywood
- Redhill
- Twenty Nineteen
- Penscratch 2
- Exford
- Karuna
- Aquene

Just thought I would add this info. It should probably be tested in all themes we have just to make sure it doesn't show up in others.

**Comment by jeffikus** [comment]
Confirmed that I experienced this but I want to test this further to make sure it's not a UX issue.

**Comment by scruffian** [comment]
This is happening because TwentyTwenty applies `height: auto` to all object elements. I don't think we should remove that code because it might be doing other things. I also don't think themes should have to make exceptions to rules like this to fix other features. The features should have the rules they need to overcome rules in themes. The best way to fix this IMO is to explicitly set the height inline in the object like this: D62535-code

**Comment by scruffian** [comment]
This is now deployed
