### ISSUE TITLE
Baskerville 2: allow the_content() to be called always

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#195]
In Baskerville, the conditional way that `the_content` is called on templates hides important aspects of a post. That happens, for example, on `content-image.php` and affects:

* Sharing buttons
* Like and reblog buttons
* Related posts
* WordPress.com ads on free sites

## Steps to replicate

1. Create a new post
2. Assign to it the post format Image
3. Add a Featured Imagem
4. Don't add any content to the post body
5. Publish it

## Result

If I don't have anything written on the post, I don't see any of the items mentioned above (related posts, sharing buttons, etc):

https://estradasebandeiras.wordpress.com/2017/10/12/chiang-mai-thailand/

So, to properly display my sharing buttons and related content, I need to force them to appear using some dummy content on my posts (ellipsis in this case). Example:

​https://estradasebandeiras.wordpress.com/2017/10/19/coyoacan-mexico-city/

Or empty paragraphs like in here:

https://estradasebandeiras.wordpress.com/2017/12/12/zocalo-mexico-city/

## Expected

From what I see, it would be ideal if `the_content` is always called whether it's empty or not, allowing other functions to hook on it.

***

Note: This was reported in Trac 9 months ago and wasn't moved to GitHub. This is a personal website, so no user reports.

In the old Trac ticket (4866) we are leaning towards a `wontfix` but I'm 100% sure why.  After all, we're not displaying important bits of a post (like JP related posts, like and share buttons, plus free ads) because of how we coded the theme. Couldn't we consider this a bug?

**Comment by laurelfulford** [comment]
Hi @eduardozulian! Thanks for bringing this up! 

In this case, I agree with the `wontfix` suggestion made in 4866-wpcom-themes. It's true that the current settings do not show certain content on certain post formats, which isn't "correct", but changing it now could cause pretty big visual changes on existing sites. For example, here's a single image post format now, with just a featured image, no content:

![image](https://user-images.githubusercontent.com/177561/50492520-f03cb700-09cc-11e9-9c2d-c80dad5ba6ff.png)

And here's how it will look if the conditional check is removed:

![image](https://user-images.githubusercontent.com/177561/50492537-0ea2b280-09cd-11e9-8c1b-35c9dc496152.png)

... which _is_ right, but could be a very unexpected change, especially since this theme has been like this for a few years now, and as far as I know this has been the only report of the issue.

It looks like using a standard post format is visually the same as the image post format for single posts when just using a featured image; I'm happy to help with any CSS needed to make sure it displays the same on the blog posts page. 

Please let me know if you have any questions about the above!
