### ISSUE TITLE
Varia: Adding/removing menu items to the Customizer adds shopping carts

### ISSUE THREAD

**Issue by jenlynnemc** [Automattic/themes#2022]
## Steps to replicate

1. Set theme to Exford
2. WooCommerce Plugin is active
3. Add a Menu item to the Menu in the Customizer

I also duplicated this on my test site where the only additional plugin was WooCommerce and I had the same results. 

## Result

For every Menu item added, an extra shopping cart appears in the Customizer.
When you switch to view the live site, the shopping carts do not display.

**Screenshots are from my test site.**
Customizer:
<img width="1374" alt="Screen Shot 2020-05-14 at 4 30 00 PM" src="https://user-images.githubusercontent.com/26546176/81978616-2ac6e400-9602-11ea-986f-a9e04346eea3.png">

Live SIte:
<img width="1224" alt="Screen Shot 2020-05-14 at 4 30 19 PM" src="https://user-images.githubusercontent.com/26546176/81978666-3d411d80-9602-11ea-88a3-32813c4938e1.png">

## Expected

When a menu item is added, instead just 1 shopping cart should remain.

* User report: [Chat #20965267-hc]
* Follow-up ticket: [ #2975294-zd]

**Comment by nielslange** [comment]
Hello @jenlynnemc 👋 Thanks for reporting this issue. It turned out that this issue is not caused by the Exford theme, but by its parent theme Varia. Every time menu items gets added or removed, a cart icon gets added. I've addressed this issue in https://github.com/Automattic/themes/pull/2024, thus, feel free to test the fix on your end. 😀

**Comment by jenlynnemc** [comment]
Thank you @nielslange!
