### ISSUE TITLE
Sela: Gallery display not aligned on iPhone SE

### ISSUE THREAD

**Issue by caimin-j** [Automattic/themes#203]
## Steps to reproduce

Go to users Destinations page:

https://tayaramuse.com/destinations/

## Result

Although it loads fine on a desktop browser, even when the browser is resized to mobile dimensions, on an iPhone SE the gallery looks like this:

https://tayaramuse.files.wordpress.com/2018/07/img_7208-2.png

This is a screenshot from the user. I'm seeing the same thing on my own iPhone SE.

## Expected

That the images would align.

* User report: https://mc.a8c.com/support-stats/happychat/transcript.php?id=4810326
* Follow-up ticket:  #1282577-zen
* User's site: https://tayaramuse.com/destinations/

**Comment by alaczek** [comment]
This is not something we can fix in the theme, as the issue here seems to be the way the user hand-coded the grid using `float: left`. I saw this method has been recommended to the user, and it's described on our [Advanced HTML page](https://en.support.wordpress.com/advanced-html/#columns), but in this case, when the browser window get's really small, there isn't enough space to fit in 3 square images, and so the grid breaks.

To make floats method work, the user would have to change the width of the last item in each grid to 30%.

Thankfully nowadays we have better ways to do this. Here's the flexbox solution:

```
<div style="display:flex;">
<div style="padding:0 10px 0 0;"><a href="https://tayaramuse.com/category/aruba/"><img class="alignnone size-full wp-image-366" src="https://tayaramuse.files.wordpress.com/2018/06/aruba2.jpg" alt="Aruba2" width="4000" height="4000" /></a></div>
<div style="padding:0 10px 0 0;"><a href="https://tayaramuse.com/category/cuba/"><img class="alignnone size-full wp-image-367" src="https://tayaramuse.files.wordpress.com/2018/06/cuba11.jpg" alt="Cuba1" width="4000" height="4000" /></a></div>
<div style="padding:0;"><a href="https://tayaramuse.com/category/egypt/"><img class="alignnone size-full wp-image-353" src="https://tayaramuse.files.wordpress.com/2018/06/egypt.jpg" alt="Egypt" width="4000" height="4000" /></a></div>
</div>
<div style="display:flex;">
<div style="padding:0 10px 0 0;"><a href="https://tayaramuse.com/category/greece/"><img class="alignnone size-full wp-image-354" src="https://tayaramuse.files.wordpress.com/2018/06/greece.jpg" alt="Greece" width="4000" height="4000" /></a></div>
<div style="padding:0 10px 0 0;"><a href="https://tayaramuse.com/category/jordan/"><img class="alignnone size-full wp-image-355" src="https://tayaramuse.files.wordpress.com/2018/06/jordan.jpg" alt="Jordan" width="4000" height="4000" /></a></div>
<div style="padding:0;"><a href="https://tayaramuse.com/category/turkey/"><img class="alignnone size-full wp-image-371" src="https://tayaramuse.files.wordpress.com/2018/06/turkey1.jpg" alt="Turkey.jpg" width="4000" height="4000" /></a></div>
</div>
```
Here I removed the floats, and the width, and I wrapped each row in an extra div with `display: flex`

It might also be a good time to revise that Advanced documentation page too. Flexbox is now supported in IE11 +, and all modern browsers, and is much better suited to create this sorts of layouts.

**Comment by caimin-j** [comment]
A belated thanks :) 

I added your update suggestion to the en-docs GH.
