### ISSUE TITLE
Rebalance: portfolio thumbnails misaligned

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#207]
The portfolio thumbnails are misaligned and overlapped on some sites.

## Steps to replicate
1. Go to https://wordpress.com
2. Go to My Sites > Settings > Writing
3. Enable the "Portfolio projects" content type
4. Go to My Sites > Sites Pages > Add
5. Create a page called "Portfolio"
6. Select "Portfolio Page" template in Page Attributes
7. Publish the page
8. Go to My Sites > Portfolio > Add
9. Add 6 projects with a featured image and content from the user's site
10. Publish each project
11. View the portfolio page

## Result

With my testing (with the user's content on my test site), each project thumbnail was displayed in the same layout as the [Rebalance demo site](https://rebalancedemo.wordpress.com/portfolio/) (no overlapping images). But on the users site, these thumbnails overlap and bunch up:

![rebalance-portfolio-thumbnails](https://user-images.githubusercontent.com/11627765/42940109-3d24737e-8b50-11e8-8d6d-3a142fdca010.jpg)

## Expected

I expected each portfolio thumbnail to sit separately from one another in the same layout as the portfolio page on the Rebalance demo site.

* User report: https://en.forums.wordpress.com/topic/portfolio-thumbnails-overlapping/
* User's site: https://climbmountains.blog/copywriter-portfolio/
* Discussion: p1531916072000181-slack-themes

**Comment by laurelfulford** [comment]
This sounds like this issue here: https://github.com/Automattic/jetpack/issues/9595

Jetpack's Lazy Loading images and themes using the 'imagesLoaded' JavaScript library to check that all images are loaded before initiating the Masonry layout aren't playing nicely together. 

The temporary work-around is to disable lazy loading images on the affected site. 

I'm going to close this issue, since it affects any theme that uses imagesLoaded.js, not just Rebalance. I'll follow up in the forum thread with the work around.
