### ISSUE TITLE
Varia: Add outermost gutters to Columns block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#2111]
Varia and the child themes don't have the outermost gutters in Columns block. This has been an issue for small screens. 

<img width="581" alt="Screenshot 2020-06-09 at 17 48 46" src="https://user-images.githubusercontent.com/908665/84176600-8e192a00-aa79-11ea-90d0-c3c3e2e2c76f.png">

Given how Twenty Twenty handles this, would you consider adding some padding like a half (or full) of the margin that the second column has?

<img width="563" alt="Screenshot 2020-06-09 at 17 49 10" src="https://user-images.githubusercontent.com/908665/84176618-92ddde00-aa79-11ea-9b3c-f7fb60d33d0f.png">

Related: #2070

cc @kjellr @ianstewart @alaczek

**Comment by alaczek** [comment]
> Varia and the child themes don't have the outermost gutters in Columns block.

I've been testing this, and it looks like they do. The Blog posts block issue is similar but technically not related as it's a different block.

In my experiments swapping layout grid block for columns block, I found that a full-width column block has 16px outer padding on both sides (which goes down to 8.5px on mobile), and it's a core style that comes with the block. In your example, the columns are wrapped in a group block without background - that's why there's no padding. [Here I removed the outer group block](https://blockpatterntest.wordpress.com/2020/07/17/webinar-without-layout-grid/) and the padding is there. Having said that, I personally think it would be nice to increase that outer padding to match that of a full-width group block with a background (32px on desktop).

**Comment by iamtakashi** [comment]
Nice catch! I can remove the group from this particular pattern. 

What @alaczek pointed out illustrates a UX issue. In layouts and patterns, it's common to wrap blocks with a group block to give a background colour and create "sections". But the users can easily remove the background colour, and when they do that, the blocks inside the group block bump the browser window on a small screen. This is because Varia themes rely on the paddings that `#main` provides on small screens. This wouldn't work if blocks are wrapped with a full-width group block. The  approach might be worth to reconsider unless group block always has the padding regardless of the existence of background colour.

**Comment by pbking** [comment]
I BELIEVE that this behavior will be addressed to what is explained as expected above by [this change](https://github.com/Automattic/themes/pull/3994).

In that change Varia & Children now introduce padding in top-level full-width groups (with or without a background color) which I believe addresses the original concern.

**Comment by scruffian** [comment]
This should now be fixed.
