### ISSUE TITLE
Seedlet Blocks: Broken default links when using menus in template parts

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2272]
This issue may be more of a tracking issue for Seedlet Blocks (as in, "we'll keep track of it") as it will likely need to be fixed "elsewhere".

**What I expected**

To be able to add a home and blog link to the menu for my header template part in the Site Editor with Seedlet Blocks.

**What I got**

This visual in the Site Editor:

![image](https://user-images.githubusercontent.com/545779/87961798-d9145d00-ca7b-11ea-8e92-bf245422cf22.png)

With this result on the front-end:
- Clicking "Home" produces no result.
- Clicking "Blog" produces error.

![2020-07-20 11 27 11](https://user-images.githubusercontent.com/545779/87961963-1bd63500-ca7c-11ea-9613-6ba433dfbfae.gif)

**Comment by Copons** [comment]
Looking at the video, I think that the Home link doesn't do anything because of how it's defined in the [header template](https://github.com/Automattic/themes/blob/8139e0452df2d226cc469f76a2d9a290eeb20659/seedlet-blocks/block-template-parts/header.html#L16):
`<!-- wp:navigation-link {"label":"Home","url":"#"} /-->`
The `#` alone doesn't reload the page, but simply tries to scroll to an anchor, which is not provided in this case, so it falls back to scrolling to the top — and if the page is already scrolled to the top, nothing happens visually.
I say "I think" because, when clicking Home, the `#` should be appended to the page address, which it doesn't seem to the case in the video. 🤔 

The Blog link doesn't work because it's not linked to the blog page, but to an absolute `blog/` string (notice the address of the errored-out page).
Assuming that the site has a Blog page, the link should be something like `https://iantesting12345.wordpress.com/blog`, or even just a relative `./blog` should work as expected.
Grasping at straws here, but could it be that the link has been created by searching for "blog" and then hitting <kbd>Enter</kbd> instead of clicking on the "Blog" page in the search results?

**Comment by MaggieCabrera** [comment]
With the latest changes to both the navigation block and the theme (and Blockbase in this case) I think this is not relevant anymore.
