### ISSUE TITLE
Image Slider for Gallery Post doesn't show in some cases

### ISSUE THREAD

**Issue by damiannep** [Automattic/themes#232]
## Steps to replicate
This issue occurs with the Baskerville 2 theme.

Case 1:
1. Create a new post with a gallery and some text
2. Assign it the **Gallery** post format and save post
3. Check the home page

Case 2:
1. Complete steps 1-3 in case 1.
2. Edit the post and remove all text, leaving the gallery behind.
3. Update the post.
4. Check the home page

## Result
The image slider does not show in either case 1 or case 2.

## Expected

The image slider would show in each cases, but if not, at least in Case 2.

* User report: #1806234-hc
* Follow-up ticket: #1348928-zd
* User's site: https://keanretki.com/

**Comment by alaczek** [comment]
Hi @damiannep!

Baskerville 2 has this quirky behaviour -- in order to display images in a slider on the blog index page, the images need to be attached (i.e. uploaded) to that specific post. If the user uploaded these images while editing a different post for example, or just dropped them to Media library, it won’t work.

You can check here if the images are attached to the post or not: https://[site url]/wp-admin/upload.php?mode=list

I looked at the post you mentioned in Slack, and it looks like the images are not attached. If you attach them from that Media library page above, the gallery should start working.
