### ISSUE TITLE
Baskerville 2: Posts on Homepage Overlap,  user noticed when switched over to Business plan/Atomic

### ISSUE THREAD

**Issue by kathleenjross** [Automattic/themes#234]
## Steps to replicate

![screen shot 2018-08-16 at 1 25 25 pm](https://user-images.githubusercontent.com/14097527/44226316-c7bec980-a15d-11e8-9c20-a59a54562670.png)

Business-plan user, https://urbexteam.com/, has Chrome, and noticed after upgrading to Business that 1) the posts on the homepage overlap or bump up against one another (if you refresh, it might fix the issue, but then it happens again), and 2) even though the homepage is set to show 15 posts, it only shows 9. 

## Result

I thought it was a cache issue at first, but I was able to see it on my own Atomic site: https://kross.blog/. 

## Expected

I'm unable to change via a cache, or browser, and there are no errors. It seems to be linked to Atomic sites, as it does not appear on free sites.

* User report: https://mc.a8c.com/support-stats/happychat/transcript.php?id=5757098
* Follow-up ticket: https://woothemes.zendesk.com/agent/tickets/1351936
* User's site: https://urbexteam.com/

**Comment by alaczek** [comment]
Do you think it's the same issue as #208 ?

**Comment by laurelfulford** [comment]
It looks like urbexteam.com has since switched themes, but they also have Lazy Loading images enabled right now. I'm not sure if this was the case when they were using Baskerville 2, but it it was, there is a known issue between it and themes that use Masonry or Isotope for layouts that could've caused this:

https://github.com/Automattic/jetpack/issues/9595

@kathleenjross I haven't had any luck replicating the issue on your site. Can you please confirm if any settings have changed, and if the behaviour was identical to what this use reported (posts overlapping) instead of the gaps described in #208? 

Also, were you able to recreate the strange issue with the posts-per-page dependency? Thanks!

**Comment by laurelfulford** [comment]
Since #208 is fixed, I'm going to close this issue as also fixed. This user is no longer using Baskerville 2, and the issue was likely related to #208 or their using Lazy Loading images.
