### ISSUE TITLE
Radcliffe 2: Site Title not Centered in Modern Bauhaus style pack

### ISSUE THREAD

**Issue by damiannep** [Automattic/themes#241]
## Steps

1. Activated Radcliffe 2 theme
2 Go to Customize > Style Packs
3 Switch to the Modern Bauhaus style pack

## Result

The site title is left aligned.

<img width="872" alt="radcliffe_title" src="https://user-images.githubusercontent.com/30090682/44661523-3546e180-aa0b-11e8-968d-c609b83f0034.png">

## Expected

I expected the site title to be centered.

* User report: #5990756-hc
* User's site: https://shoshandtim.com/

**Comment by alaczek** [comment]
Hi @damiannep!

This is by design. The style packs differ in a few ways, and one of the unique things about Modern style pack is that site title (and a number of other elements) are left aligned. You could offer custom CSS to the user to centre the site title, or recommend using one of the other style packs (all but Modern have site title centred).

**Comment by damiannep** [comment]
Thanks @alaczek. One confusing factor is that the thumbnail on the side where you select the style pack makes it look like the title will be centered in Modern Bauhaus but not in Radcliffe perfect. I think it would be nice if the thumbnail matched the behavior.
