### ISSUE TITLE
Seedlet: WooCommerce Variable Product Styles: "Clear" button text breaks to next line

### ISSUE THREAD

**Issue by tijosh** [Automattic/themes#2410]
## Steps to replicate

* Create a variable product
* Make sure one attribute for variation is at least 13 characters (important—in the below example, "Tanning Color" is 13 characters)
* Check product page

## Result

"Clear" link/button to clear variation selections breaks to next line

## Expected

"Clear" button stays on same line, or line break happens before the button

![Screenshot](https://d.pr/i/ifZduu+)
*Link to image: https://d.pr/i/ifZduu*

**Comment by MaggieCabrera** [comment]
This looks even worse between the lg and xl breakpoints:

![](https://d.pr/i/KzD74B+)

**Comment by jacklenox** [comment]
The root cause of this is this style:

https://github.com/Automattic/themes/blob/3992b5c9988d17ec64a3849ca225bbc315a505e4/seedlet/assets/sass/blocks/table/_style.scss#L15

And it seems [to be present in most, if not all, our themes](https://github.com/Automattic/themes/search?q=%22break-all%22)?

On initial inspection, this doesn't feel like desirable behaviour, and is the cause of other issues such as #2375.

Can we just remove it? And should we remove it everywhere?

**Comment by scruffian** [comment]
It was added as part of a really big commit: https://github.com/Automattic/themes/commit/4721b276a6b6a1cd4154b37d425c3f2824432dfa

I'm in favour of removing but a sanity check from @kjellr would be good...

**Comment by kjellr** [comment]
It looks like this rule has been there since day one (_dsnsystm was Allan's first version of Varia, from years ago). If it isn't causing obvious issues in other places, I'd just patch it in these specific cases rather than make a global change.

**Comment by scruffian** [comment]
I feel like if removing this does cause issues we'd be better to fix them in the block though...

**Comment by scruffian** [comment]
We also have a report here: https://github.com/Automattic/themes/issues/2120

**Comment by kjellr** [comment]
> The root cause of this is this style:

Oh sorry — I now see that this is only used for `table`, I thought it was site-wide. 😅 

In this case yeah, I think we can remove that rule and use the default.
