### ISSUE TITLE
Seedlet: Missing license information for Twenty Sixteen theme and color blending code

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2424]
Seedlet has a couple licensing notes that should be addressed: 

1. Seedlet needs to mention the use of Twenty Sixteen's [image filtering function](https://github.com/Automattic/themes/blob/63f020a88f90e1e7b565cd6e4e7b4705cabe167a/seedlet/image.php#L37-L46) in its `style.css` and `readme.txt` files. See our Twenty Twenty note in [`style.css`](https://github.com/Automattic/themes/blob/44c1567ebd92fe86599092619ccdd77aad5582e8/seedlet/assets/sass/style.scss#L48-L53) and [`readme.txt`](https://github.com/Automattic/themes/blob/44c1567ebd92fe86599092619ccdd77aad5582e8/seedlet/readme.txt#L78-L83) for an example. 
2. The [`seedlet_color_blend_by_opacity()`](https://github.com/Automattic/themes/blob/master/seedlet/classes/class-seedlet-custom-colors.php#L53) color function doesn't have a clear license. Since it comes from a 13 year-old blog post, we might consider re-writing if we're able to.

**Comment by jffng** [comment]
> The seedlet_color_blend_by_opacity() color function doesn't have a clear license. Since it comes from a 13 year-old blog post, we might consider re-writing if we're able to.

Do you think the current credit we provide in the theme is insufficient? How should credit be handled if no license is present?

**Comment by kjellr** [comment]
I think it just comes down to how strict we want/need to be. That part of the issue here was raised when Seedlet was forked for Twenty Twenty-One. That theme needs to be particularly strict, so the team opted to rewrite since the license is not clearly stated. 

Is it possible to replace the implementation here with what was written for Twenty Twenty-One instead?

**Comment by jffng** [comment]
> I think it just comes down to how strict we want/need to be. That part of the issue here was raised when Seedlet was forked for Twenty Twenty-One. That theme needs to be particularly strict, so the team opted to rewrite since the license is not clearly stated.

I see. I could be missing some context, but from looking at the TT1 custom color code, it seems like they re-wrote it because it didn't need to be as complicated as Seedlet's.

> Is it possible to replace the implementation here with what was written for Twenty Twenty-One instead?

TT1's custom color code just looks at the background color and determines whether the foreground color should be black or white: https://github.com/WordPress/twentytwentyone/blob/ba9f20cad89163761185c0467b346ba42541ae22/classes/class-twenty-twenty-one-custom-colors.php#L46

Seedlet uses a different function (the one without a clear license) to generate new hover and text selection colors:

https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/seedlet/classes/class-seedlet-custom-colors.php#L233
https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/seedlet/classes/class-seedlet-custom-colors.php#L254

I do think it would be nice to simplify this, but it would require some refactoring and testing to get right. My recommendation would be improving the credit if it's problematic, unless we can justify prioritizing this.
