### ISSUE TITLE
Syntax: Custom background image does not render in Chrome on (Samsung) Android devices

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#247]
## Steps to replicate

The user reported that their custom background image (set in **Customizer** > **Colors & Backgrounds**) does not display when they load their site on their Android devices, specifically their Galaxy S6 and Galaxy Tab A devices.

I saw from the site's source that the background image loads from here, around line 130:

```html
<style type="text/css" id="custom-background-css">
body.custom-background { background-image: url("https://redacted.files.wordpress.com/2018/09/redacted-image-name.png"); background-position: left top; background-size: auto; background-repeat: repeat; background-attachment: scroll; }
</style>
```

I didn't see any CSS rules that should block the background image from loading on mobile devices (I ran keyword searches to check for rules).

I loaded the user's site in Chrome on my Samsung Galaxy A7, running Android 8.0.0, and was able to replicate the user's issue:

![](http://cld.wthms.co/TWVSUd+)

By contrast, when I loaded the user's site in Firefox on the same device, the background image rendered:

![](http://cld.wthms.co/dYvpEw+)

## Result

The custom background image _didn't_ load when I loaded the site in Chrome for Android, on my Samsung Galaxy A7 device, running Android 8.0.0. It _did_, however, load when I used Firefox.

## Expected

The custom background image should load consistently in Chrome and Firefox browsers.

* User report: 1386233-zen
* User's site: https://speakwritetruth.wordpress.com/

**Comment by alaczek** [comment]
I'm stomped by this one. I tried a few things:
* setting background color on the user site to red - the background color was visible (I thought the background might be covered by some element)
* copy the path to the image and open in the browser (Chrome/Samsung S7) - the image was visible
* add the user image as a background to my test site and view in Chrome/Samsung S7 - the background was not visible
* activate different custom background image on my test site and view in Chrome/Samsung S7 - the background was visible

Based on the above, I think the issue here might have something to do with that background image. It's a huge image, but I don't see how this could be causing an issue :|

**Comment by alaczek** [comment]
Given that this is an old theme, and an issue seems to be an edge-case related to this particular iste/image used, I'm suggesting a `wontfix`.

**Comment by laurelfulford** [comment]
Yeah, wow, this one is quite weird. 

I agree that, given the age of the theme and the specific settings required for the background not to work, this makes sense to close as a wontfix. 

The original reporting site has also since been deleted.
