### ISSUE TITLE
Seedlet: Improve wrapping elements for the File block.

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2500]
When the file block wraps onto multiple lines (or generally doesn't leave enough room for the button), things can look pretty odd: 

![Screen Shot 2020-09-23 at 2 39 06 PM](https://user-images.githubusercontent.com/1202812/94055433-f0890280-fdaa-11ea-9528-607e047d646b.png)

![Screen Shot 2020-09-23 at 2 40 22 PM](https://user-images.githubusercontent.com/1202812/94055445-f41c8980-fdaa-11ea-86bc-e3c111feedf8.png)

We should enforce that the button should always be on the right on desktop, and appear properly left-aligned below the text on smaller screens.

**Comment by MaggieCabrera** [comment]
I'm having trouble with the desired layout for multiple reasons:

* breaking into a second line without knowing the width of the button seems like can only be done using something like `display: flex;` instead of `inline` and that moves the button all the way to the right, instead of staying in flow with the text (like your second screenshot). In your example, the text is long enough to push the button but not enough to break the line into two. I'm not sure how that can be forced.
* In the event of the text breaking into two lines using anything other than `display: inline;`, the underline of the link (which is a border bottom) breaks and moves all the way down to the bottom of the element.

<img width="712" alt="Screenshot 2020-09-30 at 12 07 32" src="https://user-images.githubusercontent.com/3593343/94672421-8aa1fb00-0315-11eb-8741-411b6a7ad77e.png">

**Comment by kjellr** [comment]
Ah, I see. What if we pushed the download button onto a second line all the time?

**Comment by scruffian** [comment]
@kjellr what do you think about this?
<img width="666" alt="Screenshot 2020-10-09 at 11 49 37" src="https://user-images.githubusercontent.com/275961/95574832-85cffc00-0a25-11eb-8772-33bab50934e9.png">

I'm not sure we need to ever drop the button down onto a second line...

**Comment by kjellr** [comment]
Users can modify the text of the button, so there are bound to be some cases when we do need to wrap this. 

I'm ok with stacking the button below the text at all breakpoints:

![Screen Shot 2020-10-09 at 7 59 53 AM](https://user-images.githubusercontent.com/1202812/95580592-98d2d400-0a05-11eb-8a6c-3e5022f4020c.png)
