### ISSUE TITLE
Gazette: Strange+Broken rendering of Blog Posts Block

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2504]
## Steps to replicate

Add the Blog Posts Block to a page in Gazette.

## Result

![image](https://user-images.githubusercontent.com/545779/94204412-d1f83980-fe86-11ea-99e8-1c630ffcee6e.png)

cc @davipontesblog

**Comment by jordesign** [comment]
I've got an active test in https://jordesign.wordpress.com/testing-blog-posts-block/. Interestingly I can't recreate it with a local installation. Maybe the discrepancy is that I can only install the Newspack version of the Blog Posts block instead of the adjusted WPCOM version?

```
.wpnbha .post-thumbnail {
    height:unset;
}
```

Solves the problem - but I'm not sure if it should be added to the theme CSS or handled at the block level?
And I also can't test it locally to confirm before issuing a PR.
