### ISSUE TITLE
Adapt archive / category page template (~4hrs).

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2524]

**Comment by MaggieCabrera** [comment]
For this issue I have:

* Styled the post excerpts (title, body, read more link): https://github.com/Automattic/themes/pull/2575
* Created a block pattern that has a styled Search block (but only partially works because of Gutenberg bugs): https://github.com/Automattic/themes/pull/2564

What's missing:

* The post subtitle
* The audio block after the excerpt for category pages
* Decide how we want to do the rest of the content of the Archive page (potentially adding blocks to the block pattern I created). We currently don't have blocks that lets us have Top posts and List posts by year.

**Comment by MaggieCabrera** [comment]
I'm going to close this issue since what is missing has already issues created for them
