### ISSUE TITLE
Snaps: Logo Shrinks on Mobile

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#258]
## Steps to replicate

1. Set a logo via the Customizer
2. View the site on a phone

## Result

Logo flashes full size for a split-second, then reduces to be much smaller than the container.

Screenshot from Samsung Galaxy S7: http://cld.wthms.co/oezY6Y
Screenshots from customizer https://d.pr/free/i/movQZm and browser inspector https://cl.ly/a89a491a060b

Confirmed on Slack (p1536637854000100-css-help) it also happens on iPhone 7 Plus.

## Expected

I expected the logo to display as the same size as shown in the customizer and browser inspector. However, on an actual mobile device it does not.

* Follow-up ticket: #1393141-zd
* User's site: https://filmstransit.com/

**Comment by laurelfulford** [comment]
I can't recreate this on my iPhone 6 (probably because the screen's a bit smaller than a 7), but I can recreate it on my Macbook.

I was also able to recreate on my own test site, so I don't think any of the settings on the site are a factor -- just plain old theme weirdness. Here's a clip of me reloading the front page; the logo flashes large before getting small again:

https://cloudup.com/cDFaEEwAYKa

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
