### ISSUE TITLE
Apostrophe 2: Infinite Scroll says "Shows 0 posts on each load." on AT sites

### ISSUE THREAD

**Issue by druesome** [Automattic/themes#260]
## Steps to replicate

1. Install Apostrophe 2 on Atomic site
2. Go to Settings > Reading in wp-admin
3. Look at "Infinite Scroll Behavior" setting

## Result

Under "Check to load posts as you scroll. Uncheck to show clickable button to load posts" it says "Shows 0 posts on each load."

<img src="http://cld.wthms.co/Hk1vPw+" width="600" />

## Expected

I expected to see a non-zero number. Perhaps the default 7 instead of zero?  This can be a little confusing for users who might think something is wrong with their site.  Despite this, Infinite Scroll works ok.

## Thoughts

Could it be because a value for `posts_per_page` was never set here?

https://github.com/Automattic/themes/blob/master/apostrophe-2/inc/jetpack.php#L9

This bug also happens on Affinity, as it doesn't have `posts_per_page1 set here either:

https://github.com/Automattic/themes/blob/master/affinity/inc/jetpack.php#L16

But not on Sketch, where it's set to `9`:

https://github.com/Automattic/themes/blob/master/sketch/inc/jetpack.php#L17

* User report: https://en.forums.wordpress.com/topic/my-home-page-wont-load-everything/
* User's site: https://travelswiththecrew.com/ * https://travelswiththecrew.com/wp-admin/options-reading.php

**Comment by laurelfulford** [comment]
Hey @druesome! The posts-per-page setting is not required in Infinite Scroll settings -- it should fall back to the default of 7 if it's not explicitly set in a theme (we usually only set it for themes with grid layouts -- like in Sketch, since it shows three posts per line, setting the posts per page to 9 prevents one lonely post from being alone in a row).

I can recreate this on a self-hosted site, too (on WP.com simple, you get a link pointing you to the setting in Calypso). My best guess is it's due to a recent change in Jetpack; I've moved the report here:

https://github.com/Automattic/jetpack/issues/10151

I'm going to close this since it doesn't seem to be theme-specific but let me know if you have any questions!
