### ISSUE TITLE
Spearhead: Bigger headings on mobile break words

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2666]
## Steps to replicate

Add a heading (h1) inside a cover block and check on a smaller screen

## Result

![](https://d.pr/i/R8OruW/RGFCYOeHMv+)

**Comment by MaggieCabrera** [comment]
Should we make this heading smaller on mobile, @kjellr ?

**Comment by kjellr** [comment]
I think that font size is actually fine for mobile, but there's a ton of unnecessary padding there: 

![Screen Shot 2020-10-26 at 2 18 58 PM](https://user-images.githubusercontent.com/1202812/97212007-349a6900-1796-11eb-84e7-0f556de14d53.png)

Would it be possible to remove some of that padding on small screens? 

![Screen Shot 2020-10-26 at 2 18 04 PM](https://user-images.githubusercontent.com/1202812/97211875-12a0e680-1796-11eb-8b1d-3eac3139e5e0.png)

cc @ianstewart since this may be a WP.com template thing.

**Comment by ianstewart** [comment]
This should be corrected in our starter design update for WP.com in …

https://github.com/Automattic/wp-calypso/issues/44151

cc @iamtakashi

**Comment by pbking** [comment]
I see that there is a blanket 'break-work' value for nearly all situations (.entry-content via Seedlet) but would it be prudent to pull that back to 'normal' for some elements?  (Like this cover block? Or maybe content with 'huge' fonts?)

**Comment by kjellr** [comment]
It's worth giving a try at least.

**Comment by MaggieCabrera** [comment]
The jetpack block is the one that is actually causing the words to break with these rules:

<img width="412" alt="Screenshot 2020-10-28 at 13 01 28" src="https://user-images.githubusercontent.com/3593343/97433435-cc768f00-191d-11eb-84b6-534a53ec6180.png">

I'm not sure why they went with this

**Comment by allancole** [comment]
I think we should fix this with Seedlet with [the Jetpack vendor Sass](https://github.com/Automattic/themes/tree/trunk/seedlet/assets/sass/vendors/jetpack). 

Then, we can report the word-break styles to Jetpack so they can consider another approach that’s maybe less aggressive.

**Comment by ianstewart** [comment]
Is there a Layout Grid issue to follow for the work-break and word-wrap defaults?

**Comment by MaggieCabrera** [comment]
> Is there a Layout Grid issue to follow for the work-break and word-wrap defaults?

@ianstewart  I opened one here: https://github.com/Automattic/block-experiments/issues/155
