### ISSUE TITLE
Twenty Seventeen: Sub menu with many items get cut off, doesn't scroll

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#268]
## Steps to replicate

1) With Twenty Seventeen active, create a custom menu containing a sub-menu with a high number of items - depending on your screen size, upwards of 14 menu items
2) Publish the menu, and then try to access menu items towards the bottom of the sub-menu.

## Result

Some menu items are cut off at the bottom of the screen, and there's no way to have them scroll up to make them visible as the top-level menu for this theme is stuck to the top of the page.

![menu](https://user-images.githubusercontent.com/11873759/45939248-63e7b600-bfd1-11e8-8ca1-a539919a552b.gif)

## Expected

For either the entire menu to scroll upwards, or for the sub-menu itself to be scrollable, but ultimately to be able to see menu items lower down on the sub-menus.

* User report: [forum thread](https://en.forums.wordpress.com/topic/menu-glitch-twenty-seventeen-theme/)
* User's site: https://whiskeysourwayfarer.wordpress.com/

**Comment by alaczek** [comment]
Hi @KokkieH ! Issues with default themes should be reported in the Core Trac (here: https://core.trac.wordpress.org/query?status=!closed&component=Bundled+Theme). Once fixed we (periodically) port them over to WordPress.com. 

I looked quickly at the open issues list and could not see anything similar to this one. Could you please make your report in the Core Trac and link it here?

**Comment by KokkieH** [comment]
Done: https://core.trac.wordpress.org/ticket/44989

Noting that I created this issue via the theme info overlay available to superadmins. Should that perhaps be updated for default themes to direct people to the Core Trac instead?

**Comment by laurelfulford** [comment]
That's a good question @KokkieH! I think the tricky bit with default themes is that in some cases things need to be reported to Core (if it's something that can be recreated on a self-hosted site), and in other cases, issues are WordPress.com-specific, so they'd need to be reported here (things like .com widgets, or functionality like custom colours and fonts). 

There's a section in the Fieldguide that touches on that -- do you think adding a link to that in the overlay for default themes would help? 

Going to close this one, since it's been moved to the Core trac.

**Comment by KokkieH** [comment]
> do you think adding a link to that in the overlay for default themes would help?

That would be helpful, yes, thank you!

**Comment by KokkieH** [comment]
Thank you!
