### ISSUE TITLE
TextBook: Featured page not positioned correctly when "Featured Content Description" set

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#27]
**Steps to replicate:**

1. In the Customizer's Theme Options panel, select a featured page.
2. Add a "Featured Content Title."
3. Leave "Featured Content Description blank and save changes.
4. In Chrome, view homepage on the front end.
5. Make browser window about 840px wide

**Result:** Featured page box overlaps menu and overflows its container at the bottom.

**Expected:** Featured page box should not overlap menu or overflow container.

![image](https://user-images.githubusercontent.com/4550351/36953634-5d7fb296-2070-11e8-8354-e4ff7d3bf958.png)

* User report: 891366-f
* User's site: https://educationaround.wordpress.com/
* Original ticket: 4975-wpcom-themes

**Comment by sixhours** [comment]
The featured highlighted post is absolutely positioned. If there isn't enough content in the featured header area (title or description, doesn't matter), and the highlighted post's content is too large, there's an imbalance that causes the box to move up under the navigation at certain screen sizes. 

1) One option is to adjust the media query such that the box stops being absolutely positioned sooner. This could affect how other sites are displayed at different screen sizes.

2) Another is to investigate an alternative solution using CSS Grid or Flexbox, to avoid absolute positioning entirely.

3) A third option is to call this a stress case and put in some Custom CSS for this customer to fix the imbalance.

I'm going to investigate option 2, since I think it's our best bet for solving this for all potential use cases.

**Comment by sixhours** [comment]
I experimented with a CSS Grid solution, but it doesn't fix the problem. We encounter the same behavior because the size of the featured page highlight will vary, and it depends on how much content is located around it to fill out the space.

A fourth solution I thought about is setting a `min-height` on the wrapper, to ensure it gives the highlighted page some space regardless of its size. This isn't perfect, since again, the size will vary depending on the content.

I'm inclined to call this a stress case and provide some Custom CSS to fix the issue on the customer's site.

**Comment by allancole** [comment]
Yeah, I think CSS-grid would be ideal, but that would definitely require a refactor. The `min-height` approach seems simple enough albeit not totally perfect. I doubt it would cause disruption for other so I’d be okay with going ahead and committing a fix for this over custom CSS.

**Comment by allancole** [comment]
Sooooo after fiddling with the code a bit, it looks like the `min-height` solution might not be the best way to solve this for every scenario. Agreed that we should call this a stress case, until we can sort out a refactor.

**Comment by sixhours** [comment]
The following CSS should do it:

```
@media screen and (min-width: 50em) {
	.header-image .site-header {
		min-height: 700px;
	}
}

@media screen and (min-width: 60em) {
	.header-image .site-header {
		min-height: 600px;
	}
}
```
