### ISSUE TITLE
Spearhead: Custom colors not working

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2701]
Custom colors in the customizer don't work in Spearhead
<img width="1440" alt="Screenshot 2020-10-27 at 13 35 10" src="https://user-images.githubusercontent.com/275961/97308866-3ed16b80-1859-11eb-9ec5-84cf008fcd63.png">

**Comment by jffng** [comment]
This will only be for dotorg sites since dotcom uses its own custom color mechanism, right?

**Comment by scruffian** [comment]
yes

**Comment by pbking** [comment]
In Seedlet's [functions.php](https://github.com/Automattic/themes/blob/trunk/seedlet/functions.php#L449) the custom colors values are added via `wp_enqueue_script` by way of the [class-seedlet-custom-colors](https://github.com/Automattic/themes/blob/trunk/seedlet/classes/class-seedlet-custom-colors.php#L40) class.

Later, in the child theme, spearhead adds css variables.  Since these are loaded AFTER Seedlet's custom variables those take precedence.
