### ISSUE TITLE
Spearhead: Block Placeholders missing border when selected

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2796]
To replicate, using Spearhead, insert a forms block or a columns block into the editor. While it's selected the placeholder border will be gone. When not selected the border will reappear.

In the screenshot below I have the forms block selected but not the columns block.

![image](https://user-images.githubusercontent.com/545779/98731623-9c8aab00-2363-11eb-9352-d53f56ade612.png)

**Comment by jffng** [comment]
There were some recent changes to how `dark-editor-style` styles are implemented by Gutenberg. As a result, we removed the `add_theme_support` for it in [this PR](https://github.com/Automattic/themes/pull/3011), and this should fix this issue. 

I tested on my sandbox with that PR added and looks like the issue is resolved: 

<img width="2040" alt="Screen Shot 2021-01-12 at 4 32 54 PM" src="https://user-images.githubusercontent.com/5375500/104377037-d9098d00-54f3-11eb-9fd4-c5b6cdbeb323.png">
