### ISSUE TITLE
Radcliffe 2: Homepage post titles overlap on mobile when a "large" heading font is selected

### ISSUE THREAD

**Issue by lakellie** [Automattic/themes#284]
## Steps to replicate

1. Set a simple site to use Radcliffe 2
2. Navigate to Customizer > Homepage Settings > set Homepage to display latest posts
3. Ensure multiple posts with featured images and relatively long post titles are published
4. Navigate to Customizer > Fonts > Headings and choose a larger font, like Playfair Display, and the "Large" font size (or larger)
5. View site on mobile (in my case, I viewed in Safari on iOS, but I experience the same when making the window very narrow on desktop as well)

## Result

Post titles overlap like this: http://cld.wthms.co/aJmKfz

## Expected

I would expect the post titles to display something more like this: https://cld.wthms.co/PCQwNK

* User report: #1492816-zen
* User's site: mumsgoneclimbingcom.wordpress.com
(They may change their Heading size after receiving my response to the ticket, but I was able to replicate this issue on my own test site as well).

**Comment by sanjeev00733** [comment]
Another report here:  https://woothemes.zendesk.com/agent/tickets/1569638

I have provided CSS to fix the issue on users site temporarily

**Comment by crunnells** [comment]
I see two possible fixes here: 

1. Override the Customizer font sizing for mobile; it's a partial bandaid because long post titles will still cause overlap, but it should happen _less_ often.
2. JS that checks the height of the `.entry-header` and the `.entry-thumbnail` containers, and set the `.hentry` height based on whichever is taller. 

The third would be to change the way we display featured images, so they're _true_ background images, instead of using positioning, but that's kind of a big refactor.

**Comment by laurelfulford** [comment]
This has been committed to WP.com in r53364-wpcom-themes. 

It looks like the original two ZD tickets have been closed, so I can't add comments there -- @lakellie and @sanjeev00733, can you each please follow up with your respective users?

The fix is to resize the post height after page load with JavaScript. Due to the nature of the issue and that that height can't be calculated until after everything has finished loading (to make sure the custom fonts are there), there is a delay before the height will adjust where the posts will still overlap. It might be good to mention that upfront, to set expectations.
