### ISSUE TITLE
Maywood: Block Editor Toolbar reflects font color changes in Customizer

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#2855]
In Maywood, if you change the text color in the Colors & Backgrounds section of the Customizer, the block toolbar in the editor uses the same color. So, when I change the text color to white, the toolbar icons seemed to disappear. I did not see this in any other Varia-based themes except Maywood. 

## Steps to replicate
1. Activate Maywood theme
2. Change text color in the Colors & Backgrounds section of the Customizer to white, and change the background color to a darker color.
3. Open a post in the editor and click on a block

## Result
The block editor toolbar looked like this: 

![image](https://user-images.githubusercontent.com/87168/103957054-8aa26a00-5152-11eb-8cc2-05ae9ea4fee6.png)

## Expected
I expected the block editor toolbar to use black font color.

* Ticket: #3499991-zd

Possibly related to: https://github.com/Automattic/wp-calypso/issues/47117 and https://github.com/Automattic/themes/issues/2856

**Comment by andrewserong** [comment]
I'm not sure how the theme color palettes work, but from doing an inspect element it looks like the CSS `currentColor` value in the toolbar is picking up the white color from the color palette instead of the black colour, as we'd expect. I can replicate by picking the dark theme featured color option in the Customizer (my site's active theme is Maywood):

![image](https://user-images.githubusercontent.com/14988353/100030648-1c2a7680-2e48-11eb-9718-815cec3ef097.png)

This is the style that is overridden:

![image](https://user-images.githubusercontent.com/14988353/100030760-5e53b800-2e48-11eb-9206-1cffc640ef83.png)

And the style that is applied:

![image](https://user-images.githubusercontent.com/14988353/100030828-7c211d00-2e48-11eb-8498-9d01a58e0c49.png)

**Comment by kjellr** [comment]
Linking a few other issues here — these appear to be similar and probably related: 

- https://github.com/Automattic/themes/issues/2856
- https://github.com/Automattic/themes/issues/2169
- https://github.com/Automattic/wp-calypso/issues/47117

**Comment by jffng** [comment]
Closed by #2879.
