### ISSUE TITLE
Prosperity: Testimonials Page Doesn't Display 2nd Page Properly

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#2949]
The Testimonials page displays a "More Testimonials" button instead of the page number buttons. When it is clicked, the second page of testimonials display in a single column instead of a grid like the first page.

## Steps to replicate
1. Add 6 testimonials to a Simple Site
2. On the Settings > Writing tab, set the following:
- Blog Posts Display 10 per page
- Testimonials Display 3 per page
- Turn off Infinite Scroll

## Result
Testimonials page displays a "More Testimonials" button:
![screenshot](https://d.pr/i/cdRTDi+)
Image URL: https://d.pr/i/cdRTDi

Clicking the "More" button causes the next testimonials to display large in a single column:
![screenshot](https://d.pr/i/gv3CvN+)
Image URL: https://d.pr/i/gv3CvN

## Expected
I expected the Testimonials page to display the page number buttons:
![screenshot](https://d.pr/i/rh4N8f+)
Image URL: https://d.pr/i/rh4N8f

And then display the second page in the same format as the first:
![screenshot](https://d.pr/i/ZhIRU5+)
Image URL: https://d.pr/i/ZhIRU5

## Workaround
I was able to get it to display properly by increasing the Blog Posts Display to any number greater than 10

* User report: #26646788-hc
* Follow-up ticket: #3607586-zd

**Comment by scruffian** [comment]
Moved to Trac

**Comment by dashkevych** [comment]
Hi @ccwalburn,
Thank you for reporting the issue. I am the author of the Prosperity theme.

I was able to reproduce the issue regarding the grid and I am going to release a fix by end of this week.

**Regarding navigation:**

By default, WordPress.com does not provide an option to disable Infinite Scroll. If we check the setting for Infinite Scroll, we can see the following:

![Infinite Scroll option at WordPress.com](https://snipboard.io/nsafRD.jpg)

This option does not disable the Infinite Scroll. It just changes its behavior. So, instead of showing posts automatically during a scroll, the user needs to click a button in order to load additional posts ("Disable to show a clickable button to load posts.").

Moreover, a WordPress.com core also adds a special class to the body element of the site:

![Infinite Scroll class added to the body element](https://snipboard.io/sZmb1S.jpg)

It seems like WordPress.com does not allow to completely disable the Infinite Scroll functionality (please correct me if I am wrong). This is the reason why a regular navigation is not shown.

I would like to mention that self-hosted sites with active Jetpack are able to completely disable the Infinite Scroll functionality:

![Infinite Scroll in self-hosted themes](https://snipboard.io/U67TaM.jpg)

So, I believe that it's more a WordPress.com issue rather than a theme issue. We can see the same behavior of the Infinite Scroll in a default WordPress theme: Twenty Twenty-One

![Infinite Scroll in default WordPress theme](https://snipboard.io/g32bh1.jpg)
