### ISSUE TITLE
Seedlet/Spearhead: IE11 error

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#3043]
Something has gone wrong with our CSS Variables pony fill in IE11 - neither Seedlet or Spearhead load in IE11.

**Comment by MaggieCabrera** [comment]
We've discussed this here: p1610960441157500-slack-C029FM1EH

This is only happening on production and not on our sandboxes.

There's currently 2 types of errors showing up for production. An issue with backticks on the primary navigation file (doesn't seem to be related to this but I'm pushing a PR to remove them anyway) and some CORS issues that seem to be causing the ponyfill to not work with the css on production. This issue seems relevant to the case: https://github.com/jhildenbiddle/css-vars-ponyfill/issues/62

<img width="1661" alt="Screenshot 2021-01-18 at 11 14 25" src="https://user-images.githubusercontent.com/3593343/104905415-98da5c80-5982-11eb-9e17-b0d28d722b86.png">

**Comment by MaggieCabrera** [comment]
Pending solving the CORS issue p3topS-Rh-p2

**Comment by MaggieCabrera** [comment]
After fixing the CORS issue, Seedlet now works on IE, Spearhead needs to have the same change for the backticks apparently.

**Comment by scruffian** [comment]
This was fixed by #3147
