### ISSUE TITLE
Twenty Twenty-One: Use WP.com's typical Customizer option to show/hide title on homepage.

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3125]
Twenty Twenty-One [does not show the page title on the homepage](https://themes.trac.wordpress.org/browser/twentytwentyone/1.1/template-parts/content/content-page.php#L16). 

Usually on WordPress.com, this is an option available in the Customizer, but for Twenty Twenty-One there's no way to opt-out. We should consider enabling this Customizer control here for consistency. 

---

Example of Customizer Control in Seedlet: 

![Screen Shot 2021-01-27 at 4 14 03 PM](https://user-images.githubusercontent.com/1202812/106054932-ae563180-60ba-11eb-9b81-3e2acd9eb1eb.png)

**Comment by andres-blanco** [comment]
@kwight @ianstewart I've made some progress on this. I took the functionality mostly from seedlet, but there's something to be aware of, the title in the "Homepage" (the one marked in /pages)[ is not being rendered](https://themes.trac.wordpress.org/browser/twentytwentyone/1.1/template-parts/content/content-page.php#L16), so when you toggle the checkbox in the customizer it does nothing visible. You can only see the results in the additional pages. In those pages the title will toggle according to the checkbox.

I could remove the condition in `template-parts/content/content-page.php` but this triggers two issues:
1. I have to modify the original theme upstream
1. It kind of breaks the design. When you look at Twenty Twenty One you can see that the page title is hidden on purpose. I figure this is to make the visible title ('The works of Berthe Morisot, 1800s-era French painter') easier to edit in Gutenberg, since it's a normal block.

So, there are two paths to follow:
1. Add the checkbox but not modify the original theme (currently implemented). In that case I believe the checkbox should have a better description, I am thinking of something not too confusing, but it's hard. There’s still the weirdness that the checkbox is inside the “Homepage settings” and the only thing it doesn’t change is your homepage...
1. Make the change upstream. I think we wish to avoid this since it will break the original design, as described above

D62137-code

**Comment by andres-blanco** [comment]
So after going over this with @blackjackkent we figured that applying this fix would be detrimental to the user experience. The theme is designed specifically to not show the home page title, so if you show the title it will look strange. 

Without title (default behaviour, checkbox checked):
![image](https://user-images.githubusercontent.com/375980/120512735-fefbd500-c3a1-11eb-98d9-4dd7f45ca98c.png)

With the title:
![image](https://user-images.githubusercontent.com/375980/120512825-1044e180-c3a2-11eb-9026-b004a4194c5e.png)

So my best guess is that this fix should not be applied.

**Comment by sixhours** [comment]
@andres-blanco Following up on my review, I agree; I think this is a wontfix.
