### ISSUE TITLE
Twenty Twenty-One: Starter Content Image URLs Incorrect

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#3162]
## Steps to replicate

* Change a site from any theme to using Twenty Twenty-One
* Select the option to use Twenty Twenty-One's homepage content

## Result

The content loads without the images showing correctly:

![Twenty Twenty-One Homepage - Bug](https://user-images.githubusercontent.com/4000628/106653908-67a68280-6565-11eb-81ae-57c292b0639e.png)

## Expected

The images would show the same way they do in the theme demo.

The starter content is using `twentytwentyonethemedemo.files.wordpress.com` as the source of the images, which is linked to a deleted site:

<img width="1624" alt="Markup 2021-02-02 at 14 48 03" src="https://user-images.githubusercontent.com/4000628/106654174-c79d2900-6565-11eb-8899-2e297cdca1ee.png">

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/52757

**Comment by sixhours** [comment]
I think this might have been fixed already, because the images loaded properly for me when I ran Headstart for Twenty Twenty One:

Demo site:
![tt1demo](https://user-images.githubusercontent.com/2124984/118820320-2a4fd180-b884-11eb-9ed7-93e63bf27c42.png)

My Headstarted sandbox:
![tt1sandbox](https://user-images.githubusercontent.com/2124984/118820355-30de4900-b884-11eb-9d1b-e99361ced8e4.png)
