### ISSUE TITLE
Seedlet: Global theme colours overriding Group block gradient colours.

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/themes#3187]
## Steps to replicate

Create a group block and select the background settings to be gradient. 
Try to change the selected colour of the first style which is a diagonally divided rectangle.

There's no way to select a custom colour for these gradient styles- 
<img width="331" alt="Screenshot at Feb 05 01-52-24" src="https://user-images.githubusercontent.com/40609190/106950747-da298500-6754-11eb-941b-05f7dfbfebd6.png">

## Result

When you try to change the darker colour of the diagonal colour style it changes to a smooth gradient instead. You cannot have any colour other than #3C8067 for the majority of the styles.

## Expected

As with other themes, I expected each gradient style to have customizable colours.

* User report: 27447050-hc
* Follow-up ticket: 3708657-zd

**Comment by WunderBart** [comment]
Looks like this gradient’s dark color is based on the current `--global--color-secondary` CSS variable. The green (#3C8067) color that you see is set by the Seedlet theme, which I suppose is the active theme in this issue. Here's where the color is set: https://github.com/Automattic/themes/blob/trunk/seedlet/classes/class-seedlet-custom-colors.php#L27.

**Comment by solstudioim** [comment]
The user came to chat again asking about the progress of this issue:

User report: 27591708-hc
Follow-up ticket: 3708657-zd

**Comment by ivan-ottinger** [comment]
Just noting here the user came back, asking for an update.
Chat: 27623710-hc
Ticket: 3708657-zd-woothemes

**Comment by Thelmachido** [comment]
Also, just noting that the user came back asking for an update today as well 
Chat: 27646507-hc
Ticket: 3708657-zd-woothemes

**Comment by pbking** [comment]
Unfortunately this appears to be a limitation of the Gutenberg Gradient picker as there is no way to assign [gradient stop points](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient()#composition_of_a_linear_gradient) in the control.

As with ANY gradient assignment, as soon as a user begins making customizations the gradient value is calculated based on the controls (and the pre-defined gradient option is no longer selected).  Since there are no controls for a color's stop point they are calculated to values that produce a gradual gradient.

Seedlet gets around this limitation by providing a calculation of a hard-lined gradient with the secondary and tertiary colors.  Customizing those colors is the only way to customize those gradients noted.

**Comment by scruffian** [comment]
This is technically possible but it's very fiddly:
<img width="1206" alt="Screenshot 2021-02-11 at 12 38 32" src="https://user-images.githubusercontent.com/275961/107637535-2b120f80-6c66-11eb-9069-d0b9e5ba4c9b.png">

Ideally users should be able to edit the colors in Gutenberg rather than starting from scratch. There is a Gutenberg issue for that here: https://github.com/WordPress/gutenberg/issues/28781

Closing this as the fix should be done in Gutenberg. Thanks for the investigation @pbking
