### ISSUE TITLE
Dara: Grid Page Template not shown on Static Front Page

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/themes#321]
## Steps to replicate

1. Assign the Grid Page Template to a published page.
2. Assign the published page with the Grid Page Template as the parent page of at least one other published page.
3. Assign the published page with the Grid Page Template as the static front page in the Customizer.

## Result

The published page with the Grid Page Template and child page appears normally, as seen here:

<img width="1179" alt="grid-page-template-1" src="https://user-images.githubusercontent.com/29981758/48151803-39577100-e290-11e8-9bf4-9c59431cdedd.png">

The grid disappears after the page is set as the static front page, as seen here:

<img width="1178" alt="grid-page-template-static-front-page" src="https://user-images.githubusercontent.com/29981758/48151880-7c194900-e290-11e8-8357-1b14fbd3c208.png">

## Expected

I expected the grid to remain displayed when the page is set as the static front page.

* User report: 7875983-hc
* User's site: https://hypotemp.blog/
* Replicated on: https://julesthenoo.wordpress.com/

**Comment by nagpai** [comment]
Unlike themes that have a "Front Page Template" in the templates dropdown within Page Attributes, Dara seems to apply the front page theme and override any existing template on the page designated as front page. (eg. Default, Full Width or Grid template). 

I would place this issue a feature request since as per the theme design we would expect the front page to only show the Dara front page design, when a page is selected as Static front page from the customizer. I will however wait for a Theam member to comment :)

**Comment by laurelfulford** [comment]
Thanks for the report, @juliasydnor!

What @nagpai says is correct, but it's not exclusive to Dara -- it's related to WordPress's core behaviour. When a theme includes a front-page.php, it's always used on the static front page. It's suppose to help with site setup when a theme has a particular front-page design, to save users from having to assign a specific template to the front page to achieve it. 

This can be a bit confusing, especially because it looks like you can change the template in the backend -- there's a WordPress core ticket related to that here: https://core.trac.wordpress.org/ticket/39773

I'm going to close this one, since it's not theme-related. Just let me know if you have any questions at all about the above! :)
