### ISSUE TITLE
Exford: link colors changed automatically

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/themes#3240]
## Steps to replicate

- User reports that their font colors changed sitewide without them changing anything. The text that changed was all linked and reflecting the link color in the customizer.
- When try to manually change individual link colors in page editor, change is not reflected.

<img width="1107" alt="1" src="https://user-images.githubusercontent.com/47717887/108841789-fcd6ed00-75e0-11eb-9c41-68ed1f1cab59.png">

<img width="1415" alt="2" src="https://user-images.githubusercontent.com/47717887/108841792-fe081a00-75e0-11eb-9c39-716148c447dd.png">

possibly related to this?? https://github.com/Automattic/themes/issues/3038

## Result

- All links now displaying as green, previously were individually set.
- In editor, cannot manually change color using toolbar options on right.

## Expected

- Link color should not change with theme updates.
- Should be able to manually change in page editor to override default

* User report: 27669545-hc
* Follow-up ticket: 3731157-zen

**Comment by liviopv** [comment]
I don't think that this is happening only on Exford.

I got a slightly different result on Alves, but one where the custom color added in the editor is still not applied:

![Screenshot](https://d.pr/i/0rNM7F+)
Screenshot: https://d.pr/i/0rNM7F

In this case, it seems to be pulling the user-agent link color.

It does the same thing on Seedlet, even when I set a custom link color in the editor:

![Screenshot](https://d.pr/i/APnqVj+)
Screenshot: https://d.pr/i/APnqVj

**Comment by pbking** [comment]
The HC seems to suggest that a user customized Exford to color the font links individually.  However, I understood that none of the Varia-based themes were able to do that. (#2566 is open to support that, however because of how some themes work I don't believe that ALL Varia child themes will make that available, Exford likely one that will not).

@liviopv you also seem to suggest the same for Alves, however I do not have the controls or ability to change the link color for individual elements (only by way of the customizer, changing all link colors, as you had pointed out). If you have further steps allowing for that can you elaborate?

**Comment by scruffian** [comment]
I think there are several different issues colliding here. I don't think this is connected to the `experimental-link-color` feature in Gutenberg, since this has never been available in Varia themes. I think the only way to customize link colors in Exford, Alves and other Varia themes is to use the custom colors in the customizer.

In this user's case I'm not sure why their colors changed, but it might be connected to this bug: https://github.com/Automattic/themes/issues/2360

For now I suggest the best fix for this is to set the colors in the Customizer as suggested in the ticket.

The Seedlet issue is unrelated. I have logged that here: https://github.com/Automattic/themes/issues/3243

I'm going to close this as I don't think there's anything more we can do.
