### ISSUE TITLE
Lodestar: Customizer Displays Menu Centered / Expected to Align-Left

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/themes#327]
## Steps to replicate

1. Install the theme https://wordpress.com/theme/lodestar/
2. Add a menu via the customizer (if you don't have one) and Publish
3. Notice that the menu is centered in the customizer but aligned left on the live site as shown in the screenshots below:
Customizer shows menu centered: https://cloudup.com/i6Vj26PbcWG
Live site shows menu aligned left: https://cloudup.com/c58Lj40tuwa

4. Add text via Customize > Theme Options > Header Top Text in either box
5. Notice that the menu is now aligned left in the customizer: https://cloudup.com/cmYYs-Nz1Zj 

## Result

While in the customizer the menu is showing as centered until you add text in the Theme Options > Header Top Text boxes. While on the front-end of the site the menu is always aligned-left.

## Expected

I expect the menu to align-left always in the customizer, as shown on the theme's documentation, and on the front-end of the sites. 

* User report: #7903207-hc
* User's site: while SU'd https://wordpress.com/customize/dialog.jetzt
* Slack discussion: p1541697598343300-slack-themes

**Comment by juliasydnor** [comment]
I had another report of this in #3856494-hc.

The `.has-top-content` class is being added to the body, even when nothing has been added to Customize > Theme Options > Header Top Text.

Because of that, this CSS is being applied, which I believe should only be applied when something has been added to Header Top Text.

```
@media screen and (min-width: 60em) {
	.has-top-content .main-navigation ul.nav-menu {
		text-align: left;
	}
}
```

The `.has-top-content` class is not being added in the Customizer, which is why the menu is correctly centered there with this CSS:

```
@media screen and (min-width: 60em) {
	.main-navigation ul.nav-menu {
		margin-bottom: 0;
		padding: 0;
		text-align: center;
	}
}
```

**Comment by laurelfulford** [comment]
Committed to WP.com in 53226-wpcom-themes.

@ash1eygrace and @juliasydnor -- can you please follow up with the users reporting these issues? Thanks!
