### ISSUE TITLE
[Blank Canvas Blocks] Implement color variable system

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3414]
Add custom color variables via theme.json to be used throughout the blocks.

A theme will supply the 'descriptive color' values in the palette.

The ponyfill leverages "custom" css color variables and expects the following CSS color values to always be available and used when styling elements (all of them are in the form --wp--custom--color--SLUG)
"foreground, background, primary, secondary, tertiary"

**Comment by pbking** [comment]
This should be ready to review; accomplished when refactoring from ponyville to blank-canvas-blocks and can be reviewed on https://github.com/Automattic/themes/pull/3417

**Comment by scruffian** [comment]
I thought the plan was to remove semantic colors from the color definitions until Gutenberg supports them - I still seem them in #3417

**Comment by pbking** [comment]
I understood the plan was to move them from the "root" configuration and back to "custom" because doing so made the Global Styles Editor work in a way that it wasn't intended (even if it was cool).

I don't think we should remove them completely.  Even if they work differently "semantic color configuration" is something I expect Gutenberg to eventually do so is something relevant for the ponyfill.

**Comment by MaggieCabrera** [comment]
From my understanding of https://github.com/WordPress/gutenberg/issues/29568 I expect to have something relatively similar to what Jason implemented in the custom block. My comment on our call was about the bit that was initially on root, since that wasn't doing it the correct way with the current implementation. The idea is to have this custom implementation and then refactor when the editor is updated using semantic definitions. It's clearer to have it in custom since we know that will definitely be subject to change in the future.

**Comment by pbking** [comment]
Root color variables have been removed via #3433.

The branch matches the description now, closing this.
