### ISSUE TITLE
Multiple Themes: Cover Block with White Background defaults to White Font, text goes "missing"

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#3483]
### Steps to reproduce the behavior

1. Go to Site - Pages and create a page.
2. Add a Cover Block to it, and make the Cover Block have a white background.
3. Add some text on top of that Cover Block.

#### What I expected to happen
The font color to be black, or some other contrasting color that would be visible on the Cover Block.

#### What actually happened
The font color automatically defaults to white, and hidden/lost on the Cover Block, since it blends into the background. 

### Context
#user-report

#### Browser / OS version
All

#### Is this specific to the applied theme? Which one?
Multiple themes. Tested on Hever and Coutoire. 

Could not replicate on Spearhead

#### Does this happen on simple or atomic sites or both?
Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all Cover Blocks on multiple themes. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/30731356/111044205-fe375080-83fb-11eb-8b20-9da501eae820.png)

![image](https://user-images.githubusercontent.com/30731356/111044200-f5467f00-83fb-11eb-8ae2-77bc2fc80252.png)

**Comment by alaczek** [comment]
I just encountered this in FSE with Blank Canvas Blocks and Myland Blocks. 

This makes creating some of the Blank Canvas patterns as starter designs problematic because they use Cover block extensively (seems like this issue does not affect the Blank Canvas theme).

**Comment by andres-blanco** [comment]
There are 2 ways to take on this issue that I can think of.
 
## Simplest way
Add a stroke to the text inside the cover block. This is something that's normally done for subtitles, given that they need to be displayed over constantly changing backgrounds. The result would look like this:

https://user-images.githubusercontent.com/375980/122425302-c513fc80-cf65-11eb-8713-ff9c436fe667.mov

*PROS*
* Simple to implement using css [text-stroke](https://caniuse.com/?search=text-stroke)
* Simple to apply on WP.com
* The stroke color can be changed to whatever we like

*CONS*
* If applied on the live site, not only on the editor, this will affect currently existing cover blocks. It's not a great difference, but pixel-perfect audience might not like it.
* If not applied to the live site it will generate a difference between what you see and what you get.

## Not so simple ways
The first place that pops up to add this fix is the cover block on the Gutenberg repo.
*PROS*
* The fix will affect a wider audience, not just WP.com.
* We might do something smarter given that we have access to the code. eg: comparing background and font color and add an indication if they are really similar. 

*CONS*
* It will take longer. Adding code to an OSS repo is slower and might be hard to implement something that actually works (color similarity(?)).

----
**I am inclined to the css text-stroke solution since it's easier and solves the immediate issue. If going this way I would need some input on wether to apply it to the live site or not.**

**Comment by andres-blanco** [comment]
On themes that work OK there are two guardrails for avoiding this behaviour. 
1. By default the text color inside a block contrasts with the background
2. If you force the text color to be the same as the cover bg you get this message in the color settings for the paragraph:
![image](https://user-images.githubusercontent.com/375980/122565182-9016b100-d01c-11eb-89db-c04a7fe14b75.png)

On themes that don't work the default color of the fonts do not contrast.

Working:
 * Blank Canvas
 * Spearhead
 * Seedlet 

Not working:
 * Twenty Twenty
 *  Hever 
 * Coutoire

**Comment by andres-blanco** [comment]
The themes that work have a css rule that applies directly to covers inner content, for example: [seedlet](https://github.com/Automattic/themes/blob/trunk/seedlet/assets/sass/blocks/cover/_style.scss#L12). That rule makes the text color the same as the one set as foreground in `Customizer > Color & Backgrounds`.

For themes that don't work this rule does not exists, so it defaults to a rule that sets the color to `#fff`.

**Comment by sixhours** [comment]
@andres-blanco It sounds like the solution used for Blank Canvas, Seedlet, and Spearhead might work for other themes, too. I would test that solution with the themes that don't work and see if it breaks anything visually. If not, it may just be a matter of applying that solution to each theme.

For any of the Twenty- themes, we'd need to open a ticket in core, unless this problem is specific to WP.com (I don't think it is since the cover block is a core block, too).

**Comment by andres-blanco** [comment]
Great! I will check all themes in the showcase and apply fixes to each individually.

**Comment by andres-blanco** [comment]
Related issues:
* https://github.com/Automattic/themes/issues/3329
* https://github.com/Automattic/themes/issues/1833

**Comment by andres-blanco** [comment]
This is a list of the current status of the "Recommended Themes" in the showcase.

THEME | Status
-- | --
Blank Canvas | WORKING
Twenty Twenty-One | WORKING
Spearhead | WORKING
Seedlet | WORKING
Twenty Twenty | NOT WORKING
Barnsbury | NOT WORKING
Dalston | NOT WORKING
Mayland | NOT WORKING
Rivington | NOT WORKING
Maywood | NOT WORKING
Balasana | NOT WORKING
Shawburn | NOT WORKING
Alves | NOT WORKING
Exford | NOT WORKING
Rockfield | NOT WORKING
Stratford | NOT WORKING
Coutoire | NOT WORKING
Morden | NOT WORKING
Stow | NOT WORKING
Hever | NOT WORKING
Leven | NOT WORKING
Independent Publisher 2 | NOT WORKING
Twenty Sixteen | NOT WORKING
Twenty Fifteen | NOT WORKING
Hemingway Rewritten | NOT WORKING
Ryu | NOT WORKING

**Comment by andres-blanco** [comment]
The PR https://github.com/Automattic/themes/pull/4086 (D63216-code) Fixes Varia and its child themes. The problem still persist in:

* Independent Publisher 2
* Twenty Twenty
* Twenty Sixteen
* Twenty Fifteen
* Hemingway Rewritten
* Ryu

I think all of these, except for Independent Publisher 2, are .org themes, so a different approach needs to be taken

**Comment by sixhours** [comment]
@andres-blanco Hemingway Rewritten, Independent Publisher 2, and Ryu are all Automattic themes as well. They might not be in the Github repository, though, so you'd only need to apply changes to the themes in SVN.

The Twenty-* themes are .org themes and probably need to be handled in core. :)

**Comment by kwight** [comment]
@andres-blanco Is anything else needed to close this out?

**Comment by andres-blanco** [comment]
There's still the .org fixes that I didn't get around to push forward since the process is more convoluted.

I will unassign myself since I don't think I will be able to tackle this in the current sprint.

**Comment by kwight** [comment]
The default themes have been left in the care of the Theme Team: pNEWy-e5R-p2

@andres-blanco will finish up Hemingway Rewritten, Independent Publisher 2, and Ryu to close out our pod work.

**Comment by alaczek** [comment]
This issue is also present in Baskerville 2 - maybe it could be squeezed in?
https://github.com/Automattic/themes/issues/3739

**Comment by andres-blanco** [comment]
Hemingway Rewritten, Ryu & Baskerville 2 fix: D63997-code

**Comment by kwight** [comment]
@andres-blanco I think you missed Independent Publisher 2 from the original list too. 👍

**Comment by andres-blanco** [comment]
> @andres-blanco I think you missed Independent Publisher 2 from the original list too. 👍

@kwight I submitted a fix in this PR https://github.com/Automattic/themes/pull/4217. It's a separate PR/Changeset because the fix is different and IP2 is the only one that's also in the git repo

**Comment by andres-blanco** [comment]
> This issue is also present in Baskerville 2 - maybe it could be squeezed in?
> #3739

@alaczek I submitted a fix for Baskerville 2 because it was exhibiting the same bug as described in this issue. I don't know if this will fix the issue you referred to #3739

**Comment by andres-blanco** [comment]
The changes on Independent Publisher 2, Baskerville 2, Ryu and Hemingway Rewritten are now deployed. Now, all its left is to fix Twenty Twenty, Twenty Sixteen and Twenty Fifteen to cover our "Recommended" themes.

**Comment by scruffian** [comment]
This seems like a core issue

**Comment by scruffian** [comment]
Fix here: https://github.com/WordPress/gutenberg/pull/33541

**Comment by scruffian** [comment]
This was closed by: WordPress/gutenberg#33541
