### ISSUE TITLE
Karuna: Uppercase Text Title and Headings on Gutenberg Editor

### ISSUE THREAD

**Issue by edwinho89** [Automattic/themes#351]
## Steps to replicate

1. Activate Gutenberg Editor on Karuna, and create/edit any posts with Gutenberg editor.

## Result

When editing you can see that "Title" has been transformed as "TITLE" automatically.

https://cloudup.com/cHQw6d0e1_L

Below is the result after setting into each of the heading:

https://cloudup.com/cPS4B8cY7d3

When the post is published, the Title is displaying correct, however all headings have been transformed into uppercase.

https://cloudup.com/c_ixfIOiky6

__________

The following CSS is obtained from [here](https://roomescapeartist.com/wp-content/themes/karuna/editor-blocks.css?ver=4.9.8):

```
/* Title */

.editor-post-title__block .editor-post-title__input {
	clear: both;
	font-weight: bold;
	font-family: Karla, sans-serif;
	text-transform: uppercase;
}

/* Headings */

.edit-post-visual-editor h1,
.edit-post-visual-editor h2,
.edit-post-visual-editor h3,
.edit-post-visual-editor h4,
.edit-post-visual-editor h5,
.edit-post-visual-editor h6 {
	clear: both;
	font-weight: bold;
	font-family: Karla, sans-serif;
	text-transform: uppercase;
}
```
__________
## Expected

Titles and heading texts displayed without being uppercase on Gutenberg editor.

* User report: #7941411-hc
* Follow-up ticket: #1568792-zen
* User's site: roomescapeartist.com

**Comment by laurelfulford** [comment]
I have corrected the post title in the theme. It looks like customer is on a business site, so will follow up once the fix has been deployed to their live site.

Looking at their site, I see that they have some Custom CSS to make the headers not use the uppercase styles, which is why the editor looks different than what they see on the front-end. So unfortunately, that will continue to not line up for them, but it will be correct for folks using the out-of-the-box version of the theme.

**Comment by edwinho89** [comment]
Hi @laurelfulford thank you for your quick and thorough explanation on the case! I just noticed the default styling for Karuna (https://karunademo.wordpress.com/style-guide/) had uppercase by default, my bad. 😄 I've let the user know upfront on what to expect on the next fix.

**Comment by laurelfulford** [comment]
Thanks @edwinho89! 

Just following up after (finally!) confirming these changes are live on business sites.
