### ISSUE TITLE
Radcliffe 2&Gutenberg: Wide width tables is left aligned

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#357]
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

1. Insert a table on the page/post via Gutenberg
2. Select the wide width option from the alignment bar
3. It gets aligned to the left due to the following CSS rule:
```
.wp-block-table.alignwide {
margin-left: calc(25% - 23vw);
margin-right: calc(25% - 23vw);
}
```
## Result
![image](https://user-images.githubusercontent.com/6737345/48648386-d3898880-e9f7-11e8-9c33-2814ec76d8a9.png)

## Expected
The table has to be centered.

Temp fix:

```
.wp-block-table.alignwide {
  margin: 0;
}
```

* User report: Slack-/C4WC5LYM6/p1542366377832200
* User's site: https://lamaisondescedres.net/packages/

**Comment by laurelfulford** [comment]
This has been fixed with the changes in #359.

I removed the CSS fixing the issue on the user's site, since it paired with the fix caused more issues :) 

@Robertght Can you please follow up with the user? I'm not sure if there's an associated ticket, the Slack reference above only includes the time stamp, not the channel, so I can't check the discussion there. Thanks!

**Comment by Robertght** [comment]
Thanks Laurel! Forgot to add it here too. Follow-up: #1578596-zen

**Comment by laurelfulford** [comment]
Great! Thank you, @Robertght! 😄
