### ISSUE TITLE
Twenty Sixteen: Blog Post Content Image Width with Gutenberg

### ISSUE THREAD

**Issue by kriskorn** [Automattic/themes#363]
## Steps to replicate

1. Go to Blog Posts -> Add.
2. Add some text and image content
3. Go to the blog post on the front-end 

## Result

1. Post created with Gutenberg:

![content-width-gutenberg](https://user-images.githubusercontent.com/12064241/48714452-6e15e180-ec1b-11e8-993c-9ff9a50af298.JPG)

2. Post created on a self-hosted site with Classic editor:

![content-width-org](https://user-images.githubusercontent.com/12064241/48714503-8128b180-ec1b-11e8-95f0-a94147c8fd39.JPG)

3. Post created on WP.com with Classic editor:

![content-width-wpcom](https://user-images.githubusercontent.com/12064241/48714543-9271be00-ec1b-11e8-870d-a8b2d6889304.JPG)

## Expected

I expected the image to still be 140% in width as defined on WP.com end, but it seems the new Gutenberg Imaeg block has width set to 100%.

* User report: #1578425-zd
* Follow-up ticket: #1578425-zd

* Old working post on user site - https://hellofrompeacecorpstanzania.wordpress.com/2018/11/10/kigoma/

* New broken post on user site - https://hellofrompeacecorpstanzania.wordpress.com/2018/11/16/kivukoni-fish-market/

**Comment by laurelfulford** [comment]
Hey @kriskorn! I'm in the process of testing this and moving it to the WordPress Core Trac, where the default themes live. 

In my testing:

1. Large images in the original editors worked (self hosted and on WP.com).
2. Large images in Gutenberg's Classic block worked (when you turn on Gutenberg, existing posts will automagically switch to use the Classic block, but you can also create a new post with this block).
3. Large images in Gutenberg's Image block did not work.

Does that line up with what you're seeing? I'm having a hard time telling in the above screenshots if the images aren't working because they're not far enough down the page (Twenty Sixteen only applies the 'wide' styles when images clear the post meta on the left, so they don't overlap). In the second shot, "Post created on a self-hosted site with Classic editor", it looks like the image and post meta are side by side; I'm less sure about the first.

Can you also confirm that the image being used is over 840px?

Just let me know if you have any questions about the above!

**Comment by laurelfulford** [comment]
Moved this issue here: https://core.trac.wordpress.org/ticket/45380

**Comment by laurelfulford** [comment]
I'm going to close this issue in favour of the Core issue above.
