### ISSUE TITLE
Seedlet: Navigation Block layout is different on editor and front-end

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#3684]
## Steps to replicate

1. Activate Seedlet
2. Add a Navigation block
3. Change the background color
4. See the result

## Result

1. In the editor, the background is only applied to the items not the whole menu
2. With a dark background, it's not possible to see/read the **Add a link** button
3. With the same background, hovering over also doesn't let you read the menu items

Editor | Front-end
--- | ---
<img width="700" alt="Captura de Tela 2021-04-21 às 18 10 17" src="https://user-images.githubusercontent.com/1136160/115621417-dd9cc900-a2cc-11eb-94a1-949186194875.png"> | <img width="699" alt="Captura de Tela 2021-04-21 às 18 10 49" src="https://user-images.githubusercontent.com/1136160/115621477-f3aa8980-a2cc-11eb-8670-954461286ad2.png">

## Expected

* The same menu style in both editor and public site
* Readable links

<small>Part of the Empathy Flow testing p9b1hy-1Fq-p2</small>

**Comment by mikachan** [comment]
I've tested this with Gutenberg 12.1.0 and WordPress 5.8.2 locally, and I'm now seeing the same in the editor and the front end, where the background is applied to the whole menu.

| Editor | Front end |
| ------ | --------- |
| ![image](https://user-images.githubusercontent.com/1645628/145986005-6e47854f-b2d0-40b9-911a-f009325d2a53.png)     |  ![image](https://user-images.githubusercontent.com/1645628/145986079-aa263935-15c6-4b9f-b0eb-01f16289ad22.png)   |

I can also confirm that the navigation text color changes to the selected color from the block styles, including the 'Add link' text, so I believe it should always be possible to see this link (unless the user chooses a color that doesn't contrast with the background.)

![image](https://user-images.githubusercontent.com/1645628/145987147-7fce9290-f035-4c3c-a60c-ad7b4a627ffd.png)

However, on wpcom, I can see the background is only applied to the navigation items. Although it looks like the text color behaves in a similar way to my local site, where it should always be visible:

![image](https://user-images.githubusercontent.com/1645628/145989006-82ffdf8c-ce54-47d4-b24b-bc376ad8b8c8.png)

This is using Gutenberg 12.0.2.

The difference seems to be because the `.wp-block-navigation__container` has `background-color: inherit;` on my local site, compared to `background: var(--global--color-background);` on wpcom. I'll try to narrow down where this difference is, but I think this is an upstream GB issue. I'll report back when I've found out more!
