### ISSUE TITLE
Quadrat: Form dropdowns are unreadable by default

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3810]
To demonstrate, here's the archives block, with the "Show as dropdown" option active: 

<img width="355" alt="Screen Shot 2021-05-10 at 12 53 11 PM" src="https://user-images.githubusercontent.com/1202812/117696543-6baef580-b18f-11eb-8b0a-939eb2d21b21.png">

@beafialho do you have a design for how these should look?

**Comment by beafialho** [comment]
Yes, here's how it should look:

<img width="580" alt="Captura de ecrã 2021-05-10, às 19 40 49" src="https://user-images.githubusercontent.com/65220155/117708401-ac2a6580-b1c7-11eb-8bd7-fd0c7410a935.png">

**Comment by beafialho** [comment]
Can be found in Figma [here](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/Quadrat?node-id=760%3A112)

**Comment by MaggieCabrera** [comment]
I've been at this and sadly there's no easy solution that will cover all the posibilities for these for multiple reasons. On one hand, each browser has a different appearance for the dropdowns, in particular the main problems are the arrows and Safari adding a glossy gradient on top of the select that is very visible if we remove the background-color. When removing the browser specific styles via appearance: none; we are removing the arrows as well. We can add the arrows manually using background-image but we can't use ::before or ::after on select elements, so we are limited there as well. Having an html wrappe rwould help but that's not an option since we can't alter markup of elements we don't know about (we don't know which kind of blocks will use selects).

Right now I see two solutions:

1- we remove the custom styling from the theme for these (font color and border) and let the browser style them how they like. We can control font-size, font-family and padding though. 

2- we remove the browser specific styles and add a custom arrow to these. But we won't be able to change the color for the arrow dynamically since we can't use pseudoelements. This means if the user changes colors for their theme, the arrow will always stay the same color regardless.

A possible option 3 would be adding a wrapper for select elements using JS and then we could style these properly, but I think it might be a bit overkill.

**Comment by kjellr** [comment]
Let's go with option 1 for now — that will start us out with working dropdowns by default, and we can customize further in the future if we'd like to.
