### ISSUE TITLE
Quadrat: Tidy up comment styles

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3898]
- Change comment content's font size to `var(--wp--preset--font-size--normal)` to mirror the article text size. 
- Adjust space above + below comment content to `20px`.
- Add `30px` of vertical spacing in between comments.
- Add `60px` spacing between the last comment and the "Leave a Reply" header. 

Before|After
---|---
<img width="828" alt="Screen Shot 2021-05-20 at 1 59 24 PM" src="https://user-images.githubusercontent.com/1202812/119027567-7bd78980-b974-11eb-8055-3356b1a99dcf.png">|<img width="828" alt="Screen Shot 2021-05-20 at 2 05 02 PM" src="https://user-images.githubusercontent.com/1202812/119027569-7d08b680-b974-11eb-9541-5c2f21877b7b.png">

<img width="828" alt="Group 6" src="https://user-images.githubusercontent.com/1202812/119028672-bbeb3c00-b975-11eb-98c1-d7770f9fdfd9.png">

**Comment by MaggieCabrera** [comment]
@kjellr the Reply button font-size is using em values and it's set at 13px. When I change the base font-size of the block, that makes the buttons bigger. I haven't seen them on the design. How do you want them to be related to the rest of the font sizes of the block? This is what it looks like after I use `var(--wp--preset--font-size--normal)` on the block:

<img width="817" alt="Screenshot 2021-05-21 at 10 56 55" src="https://user-images.githubusercontent.com/3593343/119111364-49d13080-ba23-11eb-9f00-1911e2bed92a.png">

**Comment by jffng** [comment]
Since Kjell is AFK maybe @beafialho can weigh in here.

**Comment by beafialho** [comment]
> I haven't seen them on the design. How do you want them to be related to the rest of the font sizes of the block?

Looking at what @kjellr had in the screenshots above, I think the buttons text can be set at 15pt (same size of the comment text) with the following dimensions:

<img width="693" alt="Captura de ecrã 2021-05-21, às 15 30 05" src="https://user-images.githubusercontent.com/65220155/119154266-e7d7f180-ba49-11eb-85cd-452e658877f2.png">

I suggest we change these buttons to be with a border instead of filled, looks better and doesn't compete with other buttons so much in my opinion.
