### ISSUE TITLE
Quadrat: No Logo or menu shown on single post pages or 404

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#4081]
### Steps to reproduce the behavior

1. Add a post
2. View the post URL
2b. View a URL that doesn't exist

#### What I expected to happen

Logo and site menu to appear consistently throughout the site

#### What actually happened

No menu or logo appear ons single post pages or 404s

#### Does this happen on simple or atomic sites or both?

Simple

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1661" alt="Screen Shot 2021-06-22 at 12 55 37 pm" src="https://user-images.githubusercontent.com/1842363/122856204-c1afb500-d359-11eb-86d6-6341072d32d7.png">
Pages

<img width="1659" alt="Screen Shot 2021-06-22 at 12 56 36 pm" src="https://user-images.githubusercontent.com/1842363/122856291-e310a100-d359-11eb-82ad-cdf0cef71f52.png">
Posts

**Comment by pbking** [comment]
This is some really strange behavior!
I see that the relevant template parts ARE being used, but the `<!-- wp:navigation -->` block isn't being rendered at all.  Other elements (added for testing) in that template part are showing up as expected... just not the navigation block.  

The behavior isn't present testing locally, only (so far) on a .com simple site.

I'm at a loss as to how to debug...

[EDIT] Actually further testing reveals that the navigation block isn't working ANYWHERE in Quadrat for me at the moment.  Not sure why that is but probably not a good evaluation of this issue.  I believe this is because .com doesn't have the `__unstableLocation` addition to the navigation block that Quadrat needs to show menus.  Will retest again once that has been released and deployed.

**Comment by scruffian** [comment]
I agree this seems to be a dotcom issue...

**Comment by jeffikus** [comment]
This needs a retest otherwise close it.

**Comment by jordesign** [comment]
Just re-tested and this is working as expected now (yay). Thanks folks!
