### ISSUE TITLE
Quadrat: Remove footer credit option from customizer in WPCOM

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4156]
## Steps to replicate

On WordPress.com we show this section in the customizer, but it doesn't work:

<img width="394" alt="Screenshot 2021-07-02 at 14 03 30" src="https://user-images.githubusercontent.com/275961/124278538-49f23f00-db3e-11eb-90fd-e872df11d328.png">

## Expected

We should remove this section for block themes for now.

cc @ramonjd @ianstewart

**Comment by ramonjd** [comment]
Thanks for the ping!

> On WordPress.com we show this section in the customizer, but it doesn't work:

Could you expand on this a little just to make sure we're experiencing the same issue?

For block themes, the Customizer controls the content of the footer credit **only where no footer credit and link to Wordpress.(com|org) exist**.

I just tested this by creating a new block theme site on WPCOM (TT1 blocks).
<img width="376" alt="Screen Shot 2021-07-05 at 11 38 27 am" src="https://user-images.githubusercontent.com/6458278/124407598-b7dd7700-dd87-11eb-8a69-17daada024e0.png">

<img width="289" alt="Screen Shot 2021-07-05 at 11 38 20 am" src="https://user-images.githubusercontent.com/6458278/124407595-b613b380-dd87-11eb-87a1-e66c66346dc9.png">


If a block theme site already has a valid footer credit, we don't show the default Customizer-controlled credit link.

I do see there is a problem in that, if a credit + link already exists in the footer block template part, the Customizer control has no effect.

Only when I delete the footer credit using the Site Editor does the Customizer filter kick in.

So perhaps we should just hide this control for block-based themes anyway. 👍 

On a side note, does Quadrat work differently to other block themes? 

I can't access the Site Editor when I switch to this theme, and therefore can't edit the footer template.

Or is that intentional?

It looks like [gutenberg_is_fse_theme()](https://github.com/WordPress/gutenberg/blob/wp/trunk/lib/full-site-editing/full-site-editing.php#L14) expects to find `/block-templates/index.html'` before it returns `true`, but no such file exists in `pub/quadrat`.

Thanks for your help!

**Comment by scruffian** [comment]
> I do see there is a problem in that, if a credit + link already exists in the footer block template part, the Customizer control has no effect. Only when I delete the footer credit using the Site Editor does the Customizer filter kick in.

Yes this is the problem I noticed too.

> So perhaps we should just hide this control for block-based themes anyway. 👍

I think that make sense, for now, until we have a better way for them to control it.

> On a side note, does Quadrat work differently to other block themes? I can't access the Site Editor when I switch to this theme, and therefore can't edit the footer template.

Quadrat is being built as a universal theme. It should be possible to switch the Site Editor on and off with this PR: https://github.com/Automattic/themes/pull/4154

**Comment by ramonjd** [comment]
Thanks for the clarification and quick feedback. 

Looked straightforward so I threw this up: D63768-code

**Comment by ramonjd** [comment]
Fixed in r228343-wpcom
