### ISSUE TITLE
Karuna: When Highlighting Page Content in Safari the Selection Indicator Extends Over Sidebar Widgets

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/themes#420]
When selecting text in Safari on Karuna post/pages with a right-hand sidebar, the highlight selector extends outside of the content area and over the sidebar widgets. The sidebar widgets are not actually selected.

## Steps to replicate

1. Open a page in Karuna with a right-hand sidebar in Safari. I used the Post "Open House" in the theme demo to replicate.
2. Highlight the page content, starting with the Page/Post Title.
3. See the selection indicator extend over the sidebar.

Screen Capture: https://cld.wthms.co/wjJYCb

## Result

When highlighting the page content in Safari, the selection indicator extends over the sidebar. 

Screenshot: https://cld.wthms.co/9rwXo1
Screenshot from theme demo: https://cld.wthms.co/SnivLQ

## Expected

The page content area should be highlighted, but the indicator should not extend over the sidebar.

Screenshot of expected behavior from Firefox: https://cld.wthms.co/YZvm9W

* User report: #8694327-hc
* User's site: https://dublife.net/2018/12/09/the-25-days-of-husky-christmas-17-days-til/

**Comment by laurelfulford** [comment]
I think this may have to do with how Karuna sets the width for the content area -- rather than setting it at 60% of the available space, it's 100% of the available space with a negative margin:

```float: left;
margin: 0 -40% 0 0;
width: 100%;```

That being said, this doesn't appear to affect actually copying the content, it's just a bit confusing when you're trying to select it, so I'd consider this a lower priority issue.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
