### ISSUE TITLE
Independent Publisher 2: Gravatar Date and About Me Spacing

### ISSUE THREAD

**Issue by sarahfg** [Automattic/themes#428]
## Steps to replicate

1. Update your time format in the Writing settings to `F j, Y g:i A`
2. Make sure the Author Bio is set to display under Customize > Content Options.
3. View a single post. 

## Result

As a result when you head to a post and check out your Gravatar profile at the bottom you will see the time and About Me overlap with bio like this http://cld.wthms.co/VxuEiQ

## Expected

You would expect the text on the date to not overlap the About Me text.

* User report: #1617190-zd
* User's site: https://johnjronline.wordpress.com/2018/12/12/austin-road-rage-star-wars-edition/

**Comment by nielslange** [comment]
@sarahfg _"Better late than never!"_ While you've created this issue quite a while ago, I just stumbled upon and fixed it in https://github.com/Automattic/themes/pull/1779. I see that the customer is using a different theme meanwhile, but give the fact that Independent Publisher 2 is a very popular theme, others might benefit from this fix, thus, feel free to test the PR. 😉

**Comment by goodjohnjr** [comment]
> @sarahfg _"Better late than never!"_ While you've created this issue quite a while ago, I just stumbled upon and fixed it in #1779. I see that the customer is using a different theme meanwhile, but give the fact that Independent Publisher 2 is a very popular theme, others might benefit from this fix, thus, feel free to test the PR. 😉

Hello @nielslange,

I am just a free WordPress.com user so I will not be able to test it until it is live here on WordPress.com, but thank you very much.

I probably would be using the Independent Publisher 2 theme now if links were underlined, I wonder if they would consider adding underline to all links?, and because I am trying out the new Twenty Twenty theme (which has several bugs that I need to report).

Have a nice day,
-John Jr

**Comment by danieldudzic** [comment]
Thanks for the fix, @nielslange :)
