### ISSUE TITLE
Business: Missing fonts panel on Customizer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#432]
#### Steps to reproduce 

- Start with a WordPress.com site or a self-hosted WordPress (WordPress.org) site 
- Install Business theme on the site, either using the `Activate theme` button on [this page](https://wordpress.com/theme/business), or download from that page and upload on WordPress.org site
- Visit Customizer at `{example.com}/wp-admin/customize.php`

#### What is expected 

The `Fonts` tab is available on the Customizer.

#### What happens instead 

The `Fonts` tab is missing on the Customizer.

#### Extra notes

All other WordPress.com themes have the `Fonts` tab on the Customizer, or at least from what I have seen so far. I would also expect it to be available on all themes, going by this [support document](https://en.support.wordpress.com/custom-fonts/) - `Head to the Customizer’s Fonts panel to check out our collection of free Google Fonts, available to all sites`

**Comment by arunsathiya** [comment]
#1646729-zen

**Comment by alaczek** [comment]
This was a deliberate decision (custom colors are also not available). With Business we focused on full Gutenberg support, and flexibility. The customization tools we have now are not compatible with Gutenberg. This is especially true with custom colors, since Gutenberg already allows to set custom background/text color for blocks. This is why as an experiment we decided to not include support for custom fonts and colors.

We might want to change the language on that support doc going froward.
