### ISSUE TITLE
Skatepark: Templates:Page templates: search

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4322]
There's no Search page designed so we will default to inherit Blockbase's. Leaving the issue open so that designers can review if they want to make any tweaks to it for Skatepark.
/cc @melchoyce

**Comment by MaggieCabrera** [comment]
![Screenshot 2021-08-11 at 10-28-02 Search Results for “test” – free](https://user-images.githubusercontent.com/3593343/128997061-8db92059-664d-4f1e-8d4c-0593a0854bbf.png)

This is the current state of the Search page, that's being inherited from Blockbase (the header part is coming from Blockbase too because the Skatepark one has not been merged yet, that will update once it lands). @melchoyce I see that the post titles on blockbase are using h5s (which I find odd) and that's why they are showing on uppercase (being post-title blocks is giving them the bigger font-size in return). What do you think we should do about this page?

**Comment by melchoyce** [comment]
That is weird 😕 If we can do h2 for the page title and h3 for the result titles, I think that'd work well. Could we also throw a search block at the top of the page? Can mock up if you'd like.
