### ISSUE TITLE
Skatepark: Templates: Page templates: 404

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4323]
There's no 404 page designed so we will default to inherit Blockbase's. Leaving the issue open so that designers can review if they want to make any tweaks to it for Skatepark. 
/cc @melchoyce

**Comment by MaggieCabrera** [comment]
![Screenshot 2021-08-11 at 10-27-29 Page not found – free](https://user-images.githubusercontent.com/3593343/128996885-8a8dd9d3-3491-4693-bb08-041528bc11c0.png)

This is the current state of the 404 page, that's being inherited from Blockbase (the header part is coming from Blockbase too because the Skatepark one has not been merged yet, that will update once it lands). @melchoyce do you think we should do anything about this one?

**Comment by melchoyce** [comment]
I think left-align the heading and add some additional padding to the bottom of the page content and we're golden. Maybe 150px total between the search form and the footer?
