### ISSUE TITLE
Twenty Nineteen: Top Posts & Pages Widget Has Unexpectedly Large Spacing When Using Image List Option

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#441]
## Steps to replicate

- Add Top Posts & Pages widget to footer with the Image List option

## Result

<img width="1093" alt="screen shot 2018-12-18 at 6 49 16 pm" src="https://user-images.githubusercontent.com/42454301/50190133-fd371780-02f5-11e9-9a3f-b341ebc40d5a.png">

## Expected

Tighter spacing between images and text in the widget.

* User report: #1653241-zd
* User's site: https://johnjronline.wordpress.com/

**Comment by laurelfulford** [comment]
I can recreate this issue.

This widget is in Jetpack; it looks like all of Twenty Nineteen's Jetpack widget styles are also being managed there: https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/compat/twentynineteen.css

@crunnells normally we'd add the WP.com-specific widget styles to a wpcom-style.css in the theme itself, rather than Jetpack -- is there any reason why they're in Jetpack with Twenty Nineteen? Just wondering since it makes it trickier for us to roll out fixes to some sites (like on AT) as quickly. 

This report might need to be moved to the Jetpack repo, depending on your reply -- I'll hold off til then :)

**Comment by allancole** [comment]
This issue was merged into a future release of Jetpack. Leaving this issue open until the next version is released.
