### ISSUE TITLE
Twenty Nineteen: Option to Display Gravatar in the Author Bio Section

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#442]
## Steps to replicate

- Switch to Twenty Nineteen theme
- Navigate to Customize > Content Options
- Make sure Display Author is enabled
- View post page

## Result

<img width="1057" alt="screen shot 2018-12-18 at 6 55 48 pm" src="https://user-images.githubusercontent.com/42454301/50190393-1096b280-02f7-11e9-9e8e-de0093c124fb.png">

Author bio is displayed without Gravatar image.

## Expected

An option should exist in Customize > Content Options to optionally display your Gravatar profile image.

* User report: #1653241-zd
* User's site: https://johnjronline.wordpress.com/2018/12/18/alice-calls-luther-luther-bbc/

**Comment by laurelfulford** [comment]
Thanks for the report, @mdrockwell!

In Content Options, Display Author refers to the author name shown in the post meta, under the title:

![image](https://user-images.githubusercontent.com/177561/50531448-e2675e80-0abe-11e9-8c3b-2946bff60599.png)

The author bio that displays under the post is functionality baked right in to the Twenty Nineteen theme; because of that, any enhancement requests or bugs should be reported to the Core Trac: 

https://core.trac.wordpress.org/
