### ISSUE TITLE
Stow: Color annotations - link color is the same as base text color

### ISSUE THREAD

**Issue by liviopv** [Automattic/themes#4430]
### Steps to Reproduce

1. Apply the Stow theme to a site
2. Open the editor and create an hyperlink in a paragraph block

### What I expected to happen

The linked text should have a different style than the base text to indicate it's a link

### What actually happened

The linked text and the base text look the same. Screenshot https://d.pr/i/vY8aRA

### Context

Customer report #31170486-hc

### Operating System

macOS

### OS Version

11.5.1

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

Stow

### Simple/Atomic

Simple

### Number of Users Impacted

All users

### Available Workarounds

Overriding link styles with CSS.

### Reproducibility

Consistent

### Other information

Possibly related to https://github.com/Automattic/themes/issues/3242

**Comment by xatzikidhs** [comment]
### **There are many ways to fix this bug. Try one of the following:**


_**1st Solution**_

**HTML**
`<a href="www.google.com" class="link">This is a link</a>`

> You also need to include `<link rel="stylesheet" href="style.css">` in your html file.

**CSS**
```
.link{
  color: red;
}
```


_**2nd Solution**_

**HTML**
```
<style>
  #link { color: #FF0000; } /* CSS link color */
</style>

  <a id="link" href="www.google.com">This is a link</a>
```

**Comment by jordesign** [comment]
Confirmed that there is no :link or :active style applied by the theme to differentiate it from regular text. This is due to the default/starter color annotation in the theme having *very* similar colors for 'Foreground' and 'Primary' color (which are used for text and link colors respectively).

As such - this is working as designed - but the actual color annotations are making it hard to see.

'Stow' has relatively low usage - so low priority seems correct for this.

**Comment by formosattic** [comment]
+1 33256877-hc

Shared CSS as temporary fix.
