### ISSUE TITLE
Skatepark: Make text-indent the default for first paragraphs

### ISSUE THREAD

**Issue by melchoyce** [Automattic/themes#4445]
Right now, the text-indent is a block style on the paragraph block. This works, but I wonder if there's a way we could make it the default, where all first paragraphs in a container would be indented. Ideally, it would be something you can toggle on/off in the Global Styles panel. Since that isn't possible yet, maybe we could make it a customizer setting?

[ ] Indent all first paragraphs

Open to all suggestions!

**Comment by kjellr** [comment]
This seems like a better approach to me — if the indent is applied consistently by default, it'll be less perplexing to the user.

**Comment by MaggieCabrera** [comment]
Right now we have two different classes for text indent, mainly because on the designs the amount indented in relation to the width of the paragraph looks different when the width of the paragraph is much bigger:

<img width="388" alt="Screenshot 2021-08-20 at 10 30 31" src="https://user-images.githubusercontent.com/3593343/130204748-23c6a615-938a-4554-9a62-af1c44714198.png">
<img width="1066" alt="Screenshot 2021-08-20 at 10 30 10" src="https://user-images.githubusercontent.com/3593343/130204751-4098baf6-5b3c-47f7-9e62-573258851437.png">

We were using 5 and 10em respectively, should we streamline it to 5em so that it doesn't look bad on smaller paragraphs? I'm also worried about other non-paragraph blocks being affected by a general rule of "first paragraph in a container gets the indent", I can't think of an example where that could happen right from the top of my head but I will explore to see what exceptions we could find to this kind of rule.

**Comment by kjellr** [comment]
Yeah, it's worth a try. 

> We were using 5 and 10em respectively, should we streamline it to 5em so that it doesn't look bad on smaller paragraphs?

Maybe this would be a good opportunity to try out a container query? It won't be widely supported, but it could be a good enhancement for the future.

**Comment by scruffian** [comment]
What about using ch units?

**Comment by MaggieCabrera** [comment]
> What about using ch units?

I tried that, it's the same problem, it's not the same amount of characters in the design for both widths of text.
