### ISSUE TITLE
Twenty Nineteen: Inconsistent Spacing between different objects on a page- Posts, Footer, Header

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/themes#448]
I'm seeing a lot of empty space which could be compacted and made neat for this theme.

## Steps to replicate

* Apply the theme, add a post, check for the spaces between the Header and Post title, Post end and Footer.

## Result

We can see a lot of and inconsistent spacing (on my test site)-

Between Header and Post title-

<img width="1045" alt="screenshot 2018-12-24 at 6 51 40 pm" src="https://user-images.githubusercontent.com/40609190/50400526-4fbc7c00-07ad-11e9-9461-bc9c7b6bd7e4.png">

Between Post end and Footer-

<img width="1045" alt="screenshot 2018-12-24 at 6 52 05 pm" src="https://user-images.githubusercontent.com/40609190/50400549-7084d180-07ad-11e9-8e79-d373e1284f0d.png">

Screenshots provided by the user earlier- 

![post space annotation 2018-12-22 235203](https://user-images.githubusercontent.com/40609190/50400657-73cc8d00-07ae-11e9-8dee-5d67d35c0fcc.jpg)
![footer annotation 2018-12-22 234508](https://user-images.githubusercontent.com/40609190/50400661-7d55f500-07ae-11e9-944e-b7f0ba981208.jpg)

## Expected

User expects a cleaner look in this, the spacing should be less according to them and moreover, should be consistent. 

PS- User has switched their theme now to Independent Publisher 2.

* User report: #1653241-zd]
* User's site: [https://johnjronline.wordpress.com/](https://johnjronline.wordpress.com/)

**Comment by laurelfulford** [comment]
Thanks for the report, @ahmadbaig1!

Since Twenty Nineteen is a default theme, and this issue doesn't have to do with how the theme interacts with WordPress.com functionality specifically, could you please move this report to the WordPress Core Trac here?

http://core.trac.wordpress.org/

I'm going to close this copy of the ticket, since it's not something that would be changed in the WP.com copy of the theme. Just let me know if you have any questions at all!
