### ISSUE TITLE
Blockbase: Refine comments styling

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4515]
The current comments styling in Blockbase looks quite unfinished:

<img width="715" alt="Screen Shot 2021-08-31 at 11 54 37 AM" src="https://user-images.githubusercontent.com/1202812/131536952-f3156d57-6ce9-45bd-be1e-6e80df88154b.png">

This effects all of the child themes (Quadrat, Skatepark, etc.). I'd like to suggest a few minor CSS updates so we can get this into a more workable state: 

<img width="693" alt="Screen Shot 2021-08-31 at 12 00 12 PM" src="https://user-images.githubusercontent.com/1202812/131537002-8d7b987f-5b2d-4b71-8432-a8e91297ffe8.png">

1. Increase vertical spacing between each comment to `calc(1.5 * var( --wp--style--block-gap ))`
2. Increase spacing above and below the comment paragraph content to mimic the normal paragraph block's spacing (`var( --wp--style--block-gap )`)
3. Change the "Reply" button to a text link instead.

**Comment by MaggieCabrera** [comment]
Mmmh, I'm not seeing the same as you with the latest from trunk for both the theme and GB:

<img width="625" alt="Screenshot 2021-09-07 at 10 15 34" src="https://user-images.githubusercontent.com/3593343/132309793-fbfaa136-0dad-4b10-9d72-778419f6bc1e.png">

Also, both Quadrat and Skatepark comment figma designs featured a button instead of a link for the reply link, just a wanted to confirm that we'd be backtracking on that

**Comment by MaggieCabrera** [comment]
As to the spacing between paragraphs, the thing is if the user only presses enter, the HTML generated is one paragraph with <br> for each linebreak. If the user writes actual HTML, then the paragraphs have proper separation:

<img width="397" alt="Screenshot 2021-09-07 at 11 48 17" src="https://user-images.githubusercontent.com/3593343/132324070-2cc614c5-5bbb-4789-8f2b-7f14752a2a31.png">
