### ISSUE TITLE
Site Creation: Theme chosen from Choose a Design changes after site is created

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#4538]
## Steps to replicate

- create a new site 
- follow the site creation process until it asks you to 'Choose a Design'. Themes suggested were: Overton, Cassel, Mayland, etc. 
- choose any theme like Overton, Cassel, Fredrickson, Brice, Edison, Balan, Bowen, Easley, Camdem, Vesta or Gibbs
- finish creating the site 
- go to Appearance  > Themes, the theme you chose before has changed to something else. 

<img width="1562" alt="Screen Shot 2021-09-07 at 3 25 51 PM" src="https://user-images.githubusercontent.com/36863633/132356249-a735310a-6cc3-4bd4-9cea-0bb565ef0007.png">

## Result

I chose Easley when creating the site, when the site was created, the theme changed to Maywood. I created a second site, I chose Bowen, after the second site is created, the theme became Coutoire. 

## Expected

The selected theme from 'Choose a Design' will be the same when I go to Appearance > Themes. 

* User report: team testing, empathy testing

**Comment by kathrynwp** [comment]
This is because only some of the "Designs" shown in that screen are "real" themes. The others are just pattern variations of existing themes. i.e. Easley has a specific set of dummy content, but the theme is always Maywood. Agree, it's confusing.

There has been a project to convert some of those "Designs" to real themes over the last few months, but not all have been done and I'm not sure if it's in the plans to convert all of them to themes.

cc @ianstewart @alaczek
