### ISSUE TITLE
Photos: Custom HTML block on WordPress Editor positions itself outside the content region, to the far left

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#455]
#### Steps to reproduce 

- Start with a WordPress.com site 
- Activate `Photos` theme on the site 
- Enable WordPress Editor (Gutenberg) if the site does not use WordPress Editor already
- Create a post/page
- Add a `custom HTML` block
- Publish the post/page

<img width="1281" alt="screenshot 2018-12-29 at 19 04 30" src="https://user-images.githubusercontent.com/18581859/50538850-a276a900-0b9c-11e9-9cbf-0e1094fa37c8.png">

#### What is expected 

The custom HTML block appears within the post/page's content region

#### What happens instead 

The custom HTML block appears outside the content region, on the far left of the view/page/screen

<img width="1281" alt="screenshot 2018-12-29 at 19 04 36" src="https://user-images.githubusercontent.com/18581859/50538852-a7d3f380-0b9c-11e9-8bf7-950d78ca4f64.png">

In this image, the hyperlinked word `Arun` is the custom HTML block content.

#### Notes

From what I see, this happens only with the `Photos` theme and not with other themes. I tested against Twenty Nineteen, Dara, Sela, Photo Blog themes.

<img width="1281" alt="screenshot 2018-12-29 at 19 05 32" src="https://user-images.githubusercontent.com/18581859/50538862-bcb08700-0b9c-11e9-8ee8-9a593e160162.png">

**Comment by crunnells** [comment]
I'm not sure there's much that can be done here reliably. There's no wrapper, and no code comments around the "block" so that I can at least _isolate_ the code with JS. The _only_ option I can think of is to extend/filter the Custom HTML block and always add a `<div>` around the content, but I'm not sure if that's the role of the theme or not. Otherwise, I'll have to re-write the CSS to use a different method for positioning the content.

**Comment by laurelfulford** [comment]
Thanks for looking into this @crunnells! 

Those options sound pretty intense. Personally, I'm leaning towards `wontfix` here -- it sounds like we're possibly looking at some major changes to the theme here, and there is a work around that works for all plans. Also, I feel like the cases where people would be using this block to add an inline or element-free bit of content would be pretty rare. If that turns out to be wrong and we get more reports, we can always reopen this.

**Comment by crunnells** [comment]
Thanks for the input @laurelfulford! Closing this as a `wontfix` for now.
