### ISSUE TITLE
All themes: Gutenberg caption color unreadable on dark backgrounds

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#459]
## Steps to replicate
1. Set up a theme on a Free or Personal site which has a dark color scheme available. I tested with *Gateway*'s dark gray or *Escutcheon*'s default. 
2. Set up two posts, one in Gutenberg and one in the old editor, with images with captions.

## Result
The Gutenberg caption is unreadable and dark gray; the other caption is an expected light color in keeping with the rest of the theme text.

## Expected
Both captions should be identical. In the initial user report, the user found the issue persisted even after converting back to the classic editor, and created a new post to avoid these.

## Additional info
One example here: [Gutenberg](https://limitedepsilon.wordpress.com/2018/12/28/caption-test-1/) | [classic](https://limitedepsilon.wordpress.com/2018/12/28/caption-test-2/)

`.wp-block-image figcaption` has its own color set, where the classic editor caption inherits the body color. 

* User report: #9081773-hc
* Follow-up ticket: #1672452-zd

**Comment by laurelfulford** [comment]
Just circled through to check which themes have this issue - they are: 

* Affinity
* Canard
* Gazette
* Independent Publisher 2
* Intergalactic 2
* Photos
* Rebalance

#463 covers a number of these - testing that next!

**Comment by laurelfulford** [comment]
Fixes for these themes have been committed to WP.com in:

* Affinity - 53231-wpcom-themes
* Canard - 53232-wpcom-themes
* Gazette - 53233-wpcom-themes
* IP2 - 53235-wpcom-themes
* Intergalactic 2 - 53236-wpcom-themes
* Photos - 53237-wpcom-themes
* Rebalance - 53238-wpcom-themes

... so that's all the themes that have Gutenberg styles built in fixed. Themes without (like     Escutcheon) will continue to use Gutenberg's default caption colour of grey. For now, this is a `wontfix`. 

@goblinartificer It looks like the ZD ticket is closed - can you please follow up with the user who reported this issue?
