### ISSUE TITLE
Quadrat: Buttons Hover and Colors Incorrect in Several Occasions

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4602]
In the WP.com demo site, some buttons aren't looking as intended:

- The "Learn More" button has the correct hover effect, but the default text is white
- The "Subscribe" button has an incorrect hover effect, it should turn into an outline button

https://user-images.githubusercontent.com/65220155/133407456-407bc632-75e7-4d7f-bf64-034c18b16813.mov

- In the contact form, the "Send Message" button has a Regular font weight, it should be the same as others (Bold)

| Editor      | Demo Site |
| ----------- | ----------- |
| <img width="465" alt="editor" src="https://user-images.githubusercontent.com/65220155/133408276-6ed3381d-6246-4763-923a-bac5a05b2379.png">   | <img width="411" alt="site" src="https://user-images.githubusercontent.com/65220155/133408308-d1453fcb-1165-4ddf-8e08-a0c207223302.png"> |

**Comment by danieldudzic** [comment]
I believe the above issues are caused by Jetpack styles.

@scruffian has opened an issue related to this: https://github.com/Automattic/jetpack/issues/15227

The problem with the Contact Form button is that the styles are getting overwritten by:
_wp-content/mu-plugins/grunion-contact-form/css/grunion.css_
```
.wp-block-jetpack-button button {
    padding: 20px 30px;
    border: inherit;
    font: inherit;
}
```
