### ISSUE TITLE
Blockbase: Left/right aligned buttons are not aligned correctly

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#4610]
## Steps to replicate

These buttons currently expand beyond the default width and appear in the gutter:

![image](https://user-images.githubusercontent.com/1645628/133448455-c15d4972-5553-4325-a29c-708443961f58.png)

Example block markup:

```
<!-- wp:button {"align":"right"} -->
<div class="wp-block-button alignright"><a class="wp-block-button__link">Right aligned<br></a></div>
<!-- /wp:button -->

<!-- wp:button {"align":"left"} -->
<div class="wp-block-button alignleft"><a class="wp-block-button__link">Left aligned<br></a></div>
<!-- /wp:button -->
```

**Comment by pbking** [comment]
I'm not sure that the desired behavior CAN exist outside of the button container, at least not with the new alignment functionality from Gutenberg.  This is the same behavior as any block-based theme I have tested with (not just Blockbase-based).

The below code achieves the desired layout.

```
<!-- wp:buttons {"contentJustification":"left"} -->
<div class="wp-block-buttons is-content-justification-left"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Left Aligned Button</a></div>
<!-- /wp:button -->

<!-- wp:button /--></div>
<!-- /wp:buttons -->

<!-- wp:buttons {"contentJustification":"right"} -->
<div class="wp-block-buttons is-content-justification-right"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Right Aligned Button</a></div>
<!-- /wp:button -->

<!-- wp:button /--></div>
<!-- /wp:buttons -->
```

I DO SEE that Varia (and likely most other themes that aren't using the block-based alignment strategy) are behaving as the description states as expected behavior.  If this is something to address it will need to happen upstream in Gutenberg.

**Comment by scruffian** [comment]
> If this is something to address it will need to happen upstream in Gutenberg.

In that case we should open and issue there and close this :)

**Comment by mikachan** [comment]
There's a related issue and discussion for this over on GB here: https://github.com/WordPress/gutenberg/issues/33385

Should we close this in favour of the GB one?

**Comment by scruffian** [comment]
I think that makes sense

**Comment by mikachan** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/33385
