### ISSUE TITLE
videomaker: Create a demo site on dotcom

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4643]

**Comment by scruffian** [comment]
The demo site has already been created: PdomoO-2-p2

@beafialho, now the patterns have been merged would you be able to update the demo site?

**Comment by beafialho** [comment]
Yes, I'll update it

**Comment by MaggieCabrera** [comment]
@beafialho is the demo site finished or is there something left to do?

**Comment by beafialho** [comment]
I think the [demo site](https://videomakerdemo.wordpress.com) is at a good point in terms of content. What do you think @kjellr?

**Comment by kjellr** [comment]
I think we have just a couple tasks for the demo site still: 

- The homepage template needs to have [these dates changed or removed](https://cloudup.com/cF_yEDL9zSm) so that the videos don't resemble posts. Users need to see that area and know that it's just a manually-created grid of four videos, not a list of posts. ([More details here](https://github.com/Automattic/themes/issues/4892#issuecomment-967116923))
- We should add a laurel pattern somewhere (maybe to the About page?)

**Comment by beafialho** [comment]
> The homepage template needs to have these dates changed or removed so that the videos don't resemble posts. Users need to see that area and know that it's just a manually-created grid of four videos, not a list of posts. (More details here)

Do I need to change it manually in the demo site?

> We should add a laurel pattern somewhere (maybe to the About page?)

I was thinking of adding the laurel pattern to each project page. It might make more sense to make them about each specific project:
<img width="1044" alt="Captura de ecrã 2021-11-12, às 14 45 08" src="https://user-images.githubusercontent.com/65220155/141485261-c4068b6b-1abb-4900-9503-ff26006be46a.png">

**Comment by kjellr** [comment]
> Do I need to change it manually in the demo site?

Yeah, I think so. After a pattern's been inserted it won't keep in sync with any updates to the pattern. 

> I was thinking of adding the laurel pattern to each project page.

That sounds good to me!

**Comment by scruffian** [comment]
@kjellr are you happy with the demo site? Is there anything left to do here?

**Comment by kjellr** [comment]
The demo site is all set. 👍
