### ISSUE TITLE
videomaker: Pre-launch: screenshot.png

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4648]

**Comment by MaggieCabrera** [comment]
@beafialho I don't see a screenshot of the theme on figma, do you have one you want us to use?

**Comment by beafialho** [comment]
Yes, we usually create theme screenshots [in this file](https://www.figma.com/file/J5n3eQdcJsPsjLJtsDUjYM/?node-id=0%3A1). Let's use this one:

![videomaker_screenshot](https://user-images.githubusercontent.com/65220155/139049936-5e8940f9-3f07-4eba-bb65-5020c8cd9a23.jpg)

**Comment by MaggieCabrera** [comment]
mmh, I think that screenshot works for the dotcom showcase but this issue is about the theme screenshot that goes under appearance/themes when you install it and those are usually different:
<img width="713" alt="Screenshot 2021-10-27 at 12 47 06" src="https://user-images.githubusercontent.com/3593343/139051631-a85c8197-620e-459e-9511-7a155fb755bc.png">

**Comment by beafialho** [comment]
That's right. I think this one will do then:

![videomaker_screenshot](https://user-images.githubusercontent.com/65220155/139057950-e58a4b05-6124-415d-8cb2-e6614b7a8094.jpg)

**Comment by MaggieCabrera** [comment]
Thank you!

**Comment by scruffian** [comment]
For future reference I think it should be 1200x900

**Comment by beafialho** [comment]
Thanks, I'll save that for future reference and resized it to those dimensions.

![videomaker_screenshot_1200x900](https://user-images.githubusercontent.com/65220155/139232983-e2b393cc-9c5d-43a2-811c-d2cca3a26947.jpg)
