### ISSUE TITLE
Separate Blockbase "opinion" from "ponyfill"

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4704]
There are a number of things Blockbase is doing that are opinion rather than polyfill.

This issue covers the idea of extracting and leveraging that opinion in the best way.

See: https://github.com/Automattic/themes/pull/4692#issuecomment-926833152

**Comment by MaggieCabrera** [comment]
We already have something like this with the button styling. We provide a Blockbase base and an alternative option (the outline version that Quadrat, Skatepark, Geologist, and I believe Videomaker are using). In the case of the button styles, we have an extra sass partial that is added by the theme that needs it on top of the base styles that Blockbase provides but it's not being added by Blockbase itself to avoid bloating its CSS.

Ideally, we would have Blockbase be the simplest it can be and add extra options as opt-in for the child themes but that may not be the case every time.

In the case of the header, since most of the time it's going to require extra css, I think it would be a good thing to provide multiple options for it from the parent theme perspective. Have multiple sass partials for each header style and have the child theme decide which one they are going to implement, as well as a different template part provided too. Kind of like a block style but for the whole template part?

**Comment by jeffikus** [comment]
Closing this, can we separate out the tasks into individual issues?
