### ISSUE TITLE
Twenty Seventeen: Menu doesn't stick on scroll

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/themes#475]
## Steps to replicate

After activating Twenty Seventeen and setting up the menu, scroll on any page should make the menu sticky. However, if you scroll down a bit and then hit refresh a few times, the sticky menu disappears and doesn't come back on further scrolling.

Tried testing on the self-hosted version of the theme and couldn't replicate. 

The problem doesn't appear when Browser Inspect Tools are open and configured to ignore caching.

**## Result**

This is how it looks like when broken. Missing sticky menu - https://cld.wthms.co/b10qs4

**## Expected**

This is how it should work - http://cld.wthms.co/rjEhxk

* **User report:** #9188489-hc
* **Follow-up ticket:** #1683022-zd
* **User's site:** https://simonevnine.com/ (The problem appears on all pages)

**Comment by pauljacobson** [comment]
Hi there

Our customer followed up on this issue. I explained that we're investigating the issue.

**Comment by Robertght** [comment]
The user share more details with us - I hope it will help:

> The problem with the (non-)stickiness of the menu is correlated with another issue about how the header image and blog title appear. When the menu does stick, they appear normally. But when it doesn’t stick, the blog title is too high relative to the header image (on the home page) or there is a blank band of variable height between the header image and the menu (on non-home pages). Perhaps this will help diagnose the problem. And of course, it ought to be fixed in any case.

**Comment by ChrissiePollock** [comment]
@laurelfulford Do you know who we should ping regarding this issue? Or should we report in trac?

**Comment by laurelfulford** [comment]
Hey @ChrissiePollock! This is the right spot, based on this line in the description:

> Tried testing on the self-hosted version of the theme and couldn't replicate.

We'll keep this ticket up-to-date as we have updates!

**Comment by laurelfulford** [comment]
@achyuthajoy Out of curiosity, have you been able to recreate this on another WP.com site? I can see it on the users site, but so far haven't had luck replicating on my own test site.

**Comment by laurelfulford** [comment]
I think I've figured out the cause of this issue:

Twenty Seventeen will make the menu sticky, unless it spans three rows of menu items -- then it will always stay at the top. This is a failsafe, to make sure a really tall menu isn't allowed to stick, covering most of the content.

The user's site has Custom Fonts, and the current font is a bit smaller than Twenty Seventeen's default. If you refresh the page a few times, you can see the menu originally spans three rows, then shrinks slightly and displays as two when the custom font is put in place. 

I think this is also causing the problem with the site title placement -- Twenty Seventeen's code is all firing faster than the custom font code, so it's placing the side title based on the three-row menu that's there briefly. Turning off caching gets the JavaScript firing closer together, preventing this. 

This is a really odd case that would require a very specific menu length, and a very specific font size -- it hasn't come up before in the two years since the theme launched, and trying to change the timing of these different JavaScript functions could get ugly. I think the best fix in this case would be to provide some Custom CSS, to make the menu, at this length, always two rows tall.

One way around this would be to reduce padding on the menu items, before the Custom font is loaded -- when they use the default font size, they will be crammed together a bit, but display as normal with the custom font size:

```
@media (min-width: 48em) {
	html:not(.wf-active) .main-navigation a {
		padding-left: 0;
		padding-right: 0;
	}
}
```

This will probably need to be removed if ever the font is changed, but it should help with these exact settings! I will follow up in the ZD ticket with a comment.

**Comment by rantoncuadrado** [comment]
Hi @laurelfulford 

The user reports this suggestion doesn't completely fix the issue. Could you please iterate on this?

User answer:

"
... It is possible that it helps a bit (i.e. I get the sticky menu and correct title placement on average more than without it), but it does not totally solve the problem. Pages which load correctly almost always load incorrectly when refreshed, and pages still sometimes load incorrectly on a first attempt.

I also gathered another datum which suggests that this is not the problem (or at least, not the whole problem). I tried changing the fonts back to the default. This does indeed make the menu appear on three lines and so renders the sticky menu inoperative, as your technician predicted. But there were still problems with the placement of the title. On the home page, it would still often appear in the middle of the image instead of at the bottom (but curiously, it now never seems to appear a quarter of the way up, as it previously did). And on non-home pages, there was still often a blank strip between header image and menu. However, with the fonts smaller, as I have them, the two things, lack of stickiness in the menu and the problem with the placement of the title (and on non-home pages, the extra blank strip) still always correlate.

Not sure what to make of this, but I do appreciate your efforts to solve it. I hope we can find a definitive solution!
"

Thanks, Laurel.

**Comment by laurelfulford** [comment]
Thanks for passing all of that on, @rantoncuadrado!

This is definitely an odd issue. I've been trying to recreate the remaining issues on the user's site (the title placement, and the blank strip between the menu and header), but but so far haven't had any luck.

Have you been able to recreate this? I'm not sure if it's a browser-specific thing, or maybe there's another factor I'm missing.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
