### ISSUE TITLE
Hemingway Rewritten: inline text color changes don't display in editor

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#4831]
### Quick summary

When you add a paragraph block, highlight a word and change the color of that word inline, it doesn't show the color change in the editor, but it does reflect in the preview.

https://user-images.githubusercontent.com/42655541/137045046-5b16beab-9d97-464b-a3c6-f4aa453b43e0.mov

### Steps to reproduce

1. Add a paragraph block with some text
2. Select a word within that text
3. Use the toolbar additional options to access the Text Color feature and change the color of the selected word
4. See no change in the editor
5. Preview the page to see the change

### What you expected to happen

I expected the color change to reflect in the editor as well as in the preview.

### What actually happened

The color change only shows up in the preview and remains black in the editor.

### Context

A customer reported this. I confirmed the behavior in my test Simple site which is what the screencast recording included is from.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Hemingway Rewritten (haven't tested in other themes)

### Reproducibility

Consistent

**Comment by jordesign** [comment]
High usage theme here - placing as high priority.

**Comment by mikachan** [comment]
I think this must've been fixed by https://github.com/WordPress/gutenberg/pull/35514, as the text color changes seem to be working now. We looked at some similar issues around that time that were all fixed by this issue, and this also looks very similar.

Here is what I'm currently seeing on Hemingway Rewritten:

https://user-images.githubusercontent.com/1645628/146572826-e88fab2a-ac5d-4892-9bfd-55dde01db5c5.mov

I'll close this issue for now, but please reopen if you see the issue again.
