### ISSUE TITLE
Blockbase: Search in navigation alignment

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4843]
## Steps to replicate
When adding a search form to the navigation block, the alignment is off:

<img width="473" alt="Screenshot 2021-10-14 at 18 50 08" src="https://user-images.githubusercontent.com/275961/137370343-84391ee0-8733-4814-a40f-d4a9c2e3c102.png">

**Comment by pbking** [comment]
Removing the top padding [here](https://github.com/Automattic/themes/blob/trunk/blockbase/sass/blocks/_search.scss#L4) brings it into alignment.  (I'm not sure why that padding was there to begin with so that's probably a good removal).

![image](https://user-images.githubusercontent.com/146530/137385840-4f9524d9-b313-45a9-821e-17ab32fe6259.png)

But it only works if there's no label.  What should we do if there IS a label?  It doesn't look great...

![image](https://user-images.githubusercontent.com/146530/137386022-2cbef109-f8b9-4e6e-b3b8-c6fa2fa1e3f8.png)

But I'm not sure what could be done.  Is that good enough?

**Comment by scruffian** [comment]
I think that's good enough for now...
