### ISSUE TITLE
Twenty Eleven: Automatic Unwanted GIF Resizing

### ISSUE THREAD

**Issue by allykmyta** [Automattic/themes#487]
## Steps to replicate
1. Create a new post
2. Upload a .gif file into media and embed into post
3. Ensure that the media file settings for the .gif are set to Full Size (this is usually by default):

![Screenshot example](http://cld.wthms.co/acIot4+)

## Result

Once the .gif is embedded, it shows briefly at the correct size and then reduces back to a small thumbnail. Every time the browser refreshed, this appears again.

[Example Video](http://cld.wthms.co/ZQqMpa)

## Expected

Once the .gif is embedded into a page, it should stay at the correct size without being automatically resized to a smaller thumbnail.

* User report: #8599370-hc
* Follow-up ticket: #1702105-zen
* Users Site/Post: https://irlisthenewrpg.com/2017/05/30/this-almost-ark-of-safety/
I was able to provide a workaround for this issue which can see in ticket response.

**Comment by laurelfulford** [comment]
Thanks for the report, @allykmyta!

Out of curiosity, did you test this with other themes as well? It seems odd that Twenty Eleven would be doing anything that would affect this, but I've been surprised what themes have effected before :) 

If it's only happening with Twenty Eleven, do you know offhand if it can be recreated on a self-hosted site, too? If so, this report should be moved to the Core Trac (since this is a default theme). 

http://core.trac.wordpress.org/

Just let me know if you have any questions about the above!

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
