### ISSUE TITLE
Lodestar: accented characters different sizes in menu

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#491]
Certain accented characters are larger in link text added to the menu.

## Steps to replicate

1. Go to My Sites > Customise > Menus
2. Select a menu (e.g. Primary)
3. Click Add Item
4. Select "Custom link"
5. Add `Serviços` as the link text
6. Publish
7. View the menu on the front end of the site

## Result

`ç` is larger than the other characters. The same happened whether the word Serviços was entered all lowercase or all uppercase.

![lodestar-character-size](https://user-images.githubusercontent.com/11627765/51174340-7acb5480-18af-11e9-8221-0ed1c9bf73ab.jpg)

The size differences also occurs with other accented characters — `ç`, `å`, `ę`, `ė`, `ē`, `æ`.

<img width="248" alt="lodestar-character-size-2" src="https://user-images.githubusercontent.com/11627765/51174377-8dde2480-18af-11e9-98c5-2bd812262115.png">

## Expected

`ç` to be displayed in the same font size as the rest of the text.

## Browsers

Not browser specific.

* User report: https://en.forums.wordpress.com/topic/c-in-abnormal-size-in-menu/
* User's site: https://extinal.com/

**Comment by laurelfulford** [comment]
Unfortunately, it looks like this is a known issue with the Karla font used in the Lodestar theme:

https://github.com/google/fonts/issues/1232

It's marked as an issue that should be fixed in that repo; in the meantime, the best fix might be testing out one of the custom fonts. Unfortunately it's tough to change the font in the theme's design now without causing issues, but it's a good thing to keep in mind going forward, when selecting fonts for future themes.

These ones look like they're closest in character to that font:

* Arimo
* FF Basic Gothic
* FF Dagny Pro
* Lato
* Noto Sans

I'll follow up in the forum thread with those suggestions; in the meantime, I'm going to close this issue.
