### ISSUE TITLE
Libretto: Byline does not display unless site has more than one user

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#495]
## Steps to replicate

1. Activate Libretto on a site with no other users.
2. Enable "Display author" in *Customize* > *Content options*

## Result

No byline displays either on specific posts or on the Posts page.

## Expected

As with sites with multiple users, the byline displays on both the Posts page and specific posts.

## Details
* User report: #9458323-hc
* User is going to resolve it by adding another user, since they do not have CSS access.

It looks like this also works, though:

    .byline {
        display: block;
    }

**Comment by laurelfulford** [comment]
Thanks for reporting this issue, @goblinartificer!

This is actually working as expected in Libretto -- it was a way, pre-Content Options, that we avoided having an identical byline repeated on every single post on a site. There's code in the theme that checks, and only displays the byline if there is more than one author with a published post.

We don't do this in themes anymore because, with Content Options, folks running sites can decide themselves whether they want a single author to show, or not.

It's tough for us to change this now in Libretto, as it will affect all sites using this theme, very possibly in unexpected/unwanted ways. So I'm going to close this as a `wontfix`. 

Can you please follow up with the user and let them know?

**Comment by goblinartificer** [comment]
Hey @laurelfulford , thanks for explaining that - it's good to hear why and how things work! The user's just added another admin in order to show the byline, so that works for them :)

**Comment by laurelfulford** [comment]
Great! :) This is definitely one of those things that caused a lot of confusion -- glad that we've moved away from doing it!
