### ISSUE TITLE
Ixion: Cover Block show half image when full width and fixed background

### ISSUE THREAD

**Issue by gpmw** [Automattic/themes#499]
- Add a cover block to a page
- Add an image
- Make it full width and fixed background The block only shows half the image.

## Result
The block only shows half the image.
http://cld.wthms.co/6D9hvb

## Expected
Shows correctly in the editor but not in the preview or live page.
http://cld.wthms.co/OQIWNo

* User report: #7971157-hc
* Follow-up ticket: #1723994-zen
* User's site: [#](https://freetester01162019.wordpress.com/9-2/)
This is my test site as the user didn't want to wait.

**Comment by laurelfulford** [comment]
The 'fixed' image option makes the image the same size as the browser window; because Ixion's cover block is shorter, it appears to crop a lot of the image.

Ixion's cover block height is just using the Gutenberg's default, so if we do change it in this theme, we should probably check the others, too.

I would appreciate a second opinion on this one, as this is technically working as expected, but I do understand why it would seem confusing. 

(I also see the same thing in the editor as I do on the front-end -- @gpmw, if you have a screenshot of this displaying the full issue in the editor, it'd be appreciated! I can take a closer look at this).

**Comment by gpmw** [comment]
Here is the editor view:
http://cld.wthms.co/mLOyKC

Here is the Live view:
http://cld.wthms.co/cZ8Rui

**Comment by alaczek** [comment]
Check out my PR @laurelfulford - I used the same styles as in Business. I also tested a bunch of other blocks that allow for `.allignfull`, and it looks clear to me.

**Comment by laurelfulford** [comment]
Right! That weird issue in Chrome. This is what I get for using Firefox :)

**Comment by laurelfulford** [comment]
Looks good, @alaczek!

This was merged into WP.com in 53229-wpcom-themes, and added a comment to the ZD ticket.
