### ISSUE TITLE
Videomaker: Full width not working on post template

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5024]
Looks like alignments are not working properly on the post template. Tested with the content from pcrugM-lB-p2

![Screenshot 2021-11-12 at 13-23-11 Alignments – Skatepark](https://user-images.githubusercontent.com/3593343/141466665-e2ba62c6-c01e-4997-b49b-63d046956d12.jpg)

**Comment by eduardozulian** [comment]
@scruffian during some team testing at p7DVsv-dCW-p2 I was able to still reproduce this when starting a new template or working with a Page template:

<img width="1563" alt="Captura de Tela 2022-01-25 às 16 08 40" src="https://user-images.githubusercontent.com/1136160/151043002-8f7f5476-41f7-41d1-b392-7a59885250bc.png">

Further context in p7BLOB-4mD-p2#comment-5295

**Comment by scruffian** [comment]
I think this is the expected behaviour. Content will only have full and wide alignment options when the container has inherit default layout which can be set by the "inherit default layout" control. This isn’t set on the videomaker template, so wide and full alignments aren’t available in the query templates. You can still use them within posts, and you can also set that control on the group block inside the query template which will make these controls available.
