### ISSUE TITLE
Consider adding a search icon to the Geologist + Zoologist footers

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5025]
Let's try adding a search to the footer of Geologist + Zoologist. It should: 

- Use `var(--wp--custom--font-sizes--tiny)` text (We might need a block style to accomplish this, since we don't want that to apply to all search blocks).
- Have half of the normal `var(--wp--custom--form--padding)` around the input field. 
- Be the width of the content column.
- Only be available on the archive pages, on single post/pages. 

I think we should give this a try in a PR and see what we think. To avoid messing with folks' live sites, we may need to implement this in a way that doesn't add it to existing non-FSE sites. 

Mockup: 

<img width="904" alt="Screen Shot 2021-11-12 at 7 54 33 AM" src="https://user-images.githubusercontent.com/1202812/141470601-b8018ed9-197f-4477-bd3e-2b0518bdc9b9.png">

**Comment by MaggieCabrera** [comment]
I think we could consider making a block style on Blockbase for a small version of the search block, since we usually have a big one on the search page/404 and having a smaller one on the header/footer is common too.

It's important to consider that the search block font size rules [changed recently](https://github.com/WordPress/gutenberg/pull/35723) (they weren't working on theme.json correctly before) and maybe our current rules need a bit of adjusting so this would be a good opportunity to revisit that.
