### ISSUE TITLE
Varia: Markdown + half-adopted editor styles = invisible markdown editing

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#5036]
## Steps to replicate
- Use a site that has a Varia theme
- Set the background color to something dark, and the text to something light.
- Start a new post or page
- Type /markdown to start a new Markdown block
- Add a little sample markdown, like this:

`# Hello World!

Programmed to work and not to feel
Not even sure that this is real
- Louie Zong`

So far I've confirmed this in Hever and Varia itself, and confirmed Zoologist does not suffer from this issue.

## Result
While editing the Markdown, the block editor shows an input that takes on the foreground (text) color, but forces a white background. So if I'm using a dark color scheme, I can't see much:

<img width="1482" alt="Screen Shot 2021-11-15 at 2 55 21 PM" src="https://user-images.githubusercontent.com/3476361/141862888-4ea3dfb4-e31a-49a4-bad0-3257728f1101.png">

## Expected
Either the Markdown block should use its own style, or it should accept the both the background and foreground color for the site. Maybe the background color for input in Varia is a bit too opinionated, since other themes seem fine.

* User report: Currently just a Twitter DM; [pb here](2ab6f-pb/)
* Follow-up ticket: I've asked the user to create a post in the forums so we can follow up there, but if necessary, we can use the link above to reply.

**Comment by KokkieH** [comment]
The user has created a forum thread in https://wordpress.com/forums/topic/nearly-no-contrast-for-background-and-font-in-the-markdown-editor-hever-theme/

**Comment by jordesign** [comment]
Scrubbed and confirmed this taking place in Stow as well - seems to affect all Varia themes

**Comment by Gustavo-Hilario** [comment]
I think this is a duplicate: https://github.com/Automattic/jetpack/issues/19285

Another user reported this issue here:

- [ ] 5463824-zen

They are using the block-based theme – `Remote`. 

I learned this could be fixed by using a different color other than white.

![Markup on 2022-08-09 at 08:10:44](https://user-images.githubusercontent.com/50875131/183633919-4c26105d-b1a7-4cc8-9858-81c27be5eb53.png)

**Customer also notes this happens with the Syntax Code block**
