### ISSUE TITLE
Baskerville 2: Grey background color added to Horizontal Rules

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#5247]
### Quick summary

The CSS for Baskerville 2 now seems to add a grey background color to HRs. This is effecting other elements/ blocks like the CoBlocks 'Dynamic HR' block.

### Steps to reproduce

1. Activate Baskerville 2 theme.
2. Create a page/post with a 'Dynamic HR' block. Confirm it appears with no background in the editor

<img width="732" alt="Screen Shot 2021-12-23 at 6 50 07 am" src="https://user-images.githubusercontent.com/1842363/147148976-a4fbca27-f993-4b96-9d6e-7adfe99f39f4.png">

### What you expected to happen

That the Dynamic HR would appear as it does in the editor

### What actually happened

The block shows a grey background
<img width="654" alt="Screen Shot 2021-12-23 at 6 49 59 am" src="https://user-images.githubusercontent.com/1842363/147148734-0477f85e-2aa1-4bac-a743-d839e3f769f2.png">

### Context

User report - #17727991-hc

### Theme-specific issue?

Baskerville 2

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Custom CSS can be used on Premium Plan and higher to remove the background.

```
.post-content hr.wp-block-coblocks-dynamic-separator {
    background: none;
}
```

**Comment by jordesign** [comment]
This seems to be the offending code in the Baskerville 2 stylesheet

```
.post-content hr {
	background: #eee;
	border: 0;
	height: 5px;
	margin: 2em auto;
	width: 50%;
}
```

Also noting it seems to effect the 'Separator' block (which also uses an HR) - but it is less obvious

**Comment by danieldudzic** [comment]
Fix: D72197-code

**Comment by mikachan** [comment]
I can't seem to replicate this on my sandbox, for some reason the coblocks CSS is slightly different for me. Here's what I can see on the front end:

![image](https://user-images.githubusercontent.com/1645628/148374068-d7e1eca2-d003-400e-97e3-bfbe8db5ecb6.png)

This is a Dynamic HR and then a Separator block. The background on the Dynamic HR is being overwritten by the coblocks CSS because of the `!important` on the background-color:

![image](https://user-images.githubusercontent.com/1645628/148375079-84d9d11f-8457-4e88-9f50-db769990da01.png)

But on the user's site, there is no `!important` here, so the background color isn't overwritten. I think to get around this, we could change the selector for `.post-content hr` to: `.post-content hr:not(.wp-block-coblocks-dynamic-separator)`.

If we remove `.post-content` from the HR selector in the CSS then the borders from `.wp-block-separator` overwrite the themes CSS of `border: 0` for normal HRs, so I'm not sure this is a good solution:

![image](https://user-images.githubusercontent.com/1645628/148374754-694d9355-b139-4bfa-9b7b-9f4d956d7082.png)

**Comment by pbking** [comment]
Confirmed @mikachan's observations and tested their solution.  I was able to reproduce both the original issue and the HR issue noted.  Diff for that change which fixes with no side effects can be found here: D74996-code

I believe that is ready to ship.

**Comment by pbking** [comment]
Deployed
