### ISSUE TITLE
Twenty Nineteen: Archive pages not displaying posts according to customizer 'Content Setting'

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#528]
Moved over from: https://core.trac.wordpress.org/ticket/46178

@rantoncuadrado - can you please add short links to the original user report - thank you!

---

Full post option in customizer > Blog Display is not being respected in some archive pages. 

Example:

With this option selected, https://YOURWEBSITE/category/X shows excerpts, while

https://YOURWEBSITE/category/X/page/1/ shows, as expected, whole posts.

Option screenshot:

http://take.ms/hiXqK

## Steps to replicate

1. In the customizer set to 'Display full posts for blog and archive' pages.
2. View archive pages on site

I've been able to reproduce the issue in another test site.

## Result

* On the blog page the full post shows as expected.
* Going to an archive page though shows excerpts on the first page 
* However, it works properly, showing full posts in subsequent archive pages -when you click on the 'Older posts' button.

**Comment by rantoncuadrado** [comment]
Sure thing, Laurel, thanks for copying the report here. So, next time... I suppose I'd need to create the issue here? Or should I still post it in the core?

User ticket: #1772649-zen

**Comment by allancole** [comment]
This is gonna be a tricky one. The best way to fix this is by making a change to `archives.php`. to allow the Full post (`the_content()`) to display in archives by default instead of excerpts (`the_excerpt()`). This would need to be committed to `/core` but it would definitely cause disruption for wporg users’ archive pages—especially for those they don’t use Jetpack and prefer to have excerpts on archive views. 

An alternative solution would be to change the **Blog Display** option description so it no longer suggests the ability to change the Archives page. ie:

Before: “Choose between a full post or an excerpt for the blog and archive pages.”

After: “Choose between a full post or an excerpt for the blog.”

**Comment by svnsbck** [comment]
Sorry to snoop in here. I'm the user that ran into/found this bug and naturally have an interest in getting it fixed (considered that I would like to have full posts shown), but the solution simply calling it "Choose between a full post or an excerpt for the blog", wouldn't fix anything in my opinion., Archive pages still would show full-posts after the first page, which also wouldn't be, what the user wants.

And again... sorry for snooping in.

**Comment by allancole** [comment]
Hi @svnsbck, you are right that my second suggestion doesn’t actually fix the issue. The ideal solution is what I suggested first, but that’s not possible at the moment for various reasons. 

Instead, I submitted a Pull Request to fix this via Jetpack for WordPress.com: https://github.com/Automattic/jetpack/pull/11305

Leaving this issue open until that PR is merged and included in a future Jetpack release.
