### ISSUE TITLE
Pictorico: Having the search bar as optional

### ISSUE THREAD

**Issue by correliebre** [Automattic/themes#533]
## Current state

The Pictorico theme currently has a search bar at the top of the header, in between the title and the menu area. 
![](http://cld.wthms.co/QIXH5P+)
There's no option in the Customizer to remove that search bar.

## Enhancement request

It would be great if there were an option in the Customizer to either activate or deactivate that search bar. Something like the features we currently see under [Content Options](http://cld.wthms.co/reUbWk), that would give the chance to choose whether to have the search bar or not. 

* User report: #10147799-hc

**Comment by laurelfulford** [comment]
Thanks for this enhancement request, @correliebre!

Unfortunately, given that it's been almost five years since Pictorico was launched, it's not a theme that we'll be adding new functionality to.

I'm going to close this as a `wontfix` -- can you please follow up with the user if needed? Also, just let me know if you have any questions about this -- thanks!
