### ISSUE TITLE
Seedlet & Varia: The error message displayed on the posts page has incorrect text

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/themes#5379]
## Steps to replicate

Issue was raised here with a description: pd4QKa-r4-p2

Short version: We seem to have a slight issue in the /blog-feed page error showing in the wording of the error. As it is not a homepage, but rather something else. 

The issue seems to be only connected to the Varia and Seedlet themes and their child themes as well.

**Comment by Thelmachido** [comment]
Pulling more information from pd4QKa-r4-p2  to here for context 

**Summary**
The new 404 page that’s displayed when no posts are published on the site says that the home page is configured to display the latest posts. This is not necessarily true, as the issue can also occur on pages that are not set as the home page, like the posts page.

**Steps to reproduce**
1. On a site that doesn't have any posts published 
2. Assign a post page in Appearance > Customiser
3. On the front of the site, open the page you assigned to display posts in Customiser
4. An error message will be displayed on the post page, saying “Your site is set to show the the most recent posts on your home page – but you don’t have any posts published.”

**Issues with the error message**

- The error message is displayed on a posts page rather than a home page, however its text says “home page”. This can cause some confusion for users who actually set a static home page.

- Also, the definite article “the” is actually added to the text twice by accident: “…the the most recent…”

I think in general, the new error message is a great idea as this is a common issue among users, and the message now points them in the right direction on how to set it up properly. However, to avoid confusion I would suggest changing the text to something like this:

“This page is set to show the most recent posts – but you don’t have any posts published.”

**_Example screenshots_**

![404de](https://user-images.githubusercontent.com/41231764/173802009-7e94ba22-6588-4bf8-8ced-e9ec2051d7aa.png)

![404en](https://user-images.githubusercontent.com/41231764/173802033-6e5e4d61-9404-403c-92d9-41bb84965fd6.png)

**Comment by bobmatyas** [comment]
This was fixed on Seedlet: https://github.com/Automattic/themes/blob/4e7b04281c5cffe7c969fea7526621574fd15321/seedlet/template-parts/content/content-none.php#L24

Screenshot:

<img width="974" alt="Screenshot on 2022-07-11 at 14-29-36" src="https://user-images.githubusercontent.com/45246438/178334115-31135dda-e972-4ffd-a917-260d87783f45.png">
