### ISSUE TITLE
Blockbase + co: Global styles colors are lost after changing settings in the customizer

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5387]
Related conversation: p1642735935059000-slack-C01DF571R5Y

Let's check that any color changes done via GS are not wiped out when changing any other settings in the customizer

**Comment by supernovia** [comment]
Thank you!

**Comment by pbking** [comment]
I believe that with recent versions of Gutenberg the structure of where the "user palette" information has changed, however the location that the customizer uses continues to also work, (in that colors saved via the customizer show up).  Because they are different though we aren't "pulling" from the "new" location and any color customizations made in the Global Styles panel are lost.

Digging deeper to see if I can find when this change happened in Gutenberg and what steps we can take to mitigate it.

**Comment by pbking** [comment]
I see that the 'User JSON' that is stored by the Global Styles panel in the FSE looks like this (or at least is presented like this via `WP_Theme_JSON_Resolver_Gutenberg::get_merged_data()-get_raw_data()`):

```
{
    "settings": {
        "color": {
            "palette": {
                "theme": [
                    {
                        "slug": "primary",
                        "color": "#ba1900",
                        "name": "Primary"
                    },
```

Whereas the Customizer stores the same information:
```
{
    "settings": {
        "color": {
            "palette": {
                "custom": [
                    {
                        "slug": "primary",
                        "color": "#73e000",
                        "name": "Primary",
                        "default": "#ba1900"
                    },
```

**Comment by pbking** [comment]
I think I see what's going on here.

Recent changes to Gutenberg eliminated our ability to see what values came from the THEME.JSON and what values came from CUSTOMIZATIONS from GLOBAL STYLES.

This seems to be a bug in Gutenberg, and perhaps related to this issue: https://github.com/WordPress/gutenberg/issues/38185

Because of this the code used to "clear out customizations" when the user sets the values to the default is clearing things out when it shouldn't. 

This can be mitigated by simply saving the color customizations (and never clearing them).  

This has the side effect of transitioning the structure of the stored values from "palette:theme" to "palette:custom" (which I believe to be the correct place to store) any time the customizer publishes changes.

Due to the Gutenberg error noted above the customized color values aren't showing in the editor with either structure ("palette:theme" or "palette:custom")
