### ISSUE TITLE
Blockbase: Social Menu does not display correct social icons

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#5546]
### Quick summary

When using theme Blockbase -- and FSE is *OFF*, Social Menu is not behaving as expected. The menu will display Share icon (something like this `<`) instead of the intended icon.

### Steps to reproduce

1. Activate theme Blockbase
2. Now, make sure FSE is OFF
3. Create a menu, give it a title "Social" and assign it as Social Navigation menu/Social menu
4. Add menu item using custom links as usual (per this guide: https://wordpress.com/support/menus/social-links-menu/ )
5. See the icons not displaying the expected icons (on this example, on my test site, the links are Twitter and Youtube.)
<img width="1779" alt="Screenshot 2022-02-07 at 4 14 10 PM" src="https://user-images.githubusercontent.com/44726232/152750845-5c53faec-8aeb-4647-93b3-d0a1c094e0a9.png">

### What you expected to happen

For the social icons to appear

### What actually happened

It displays the share icon instead

### Context

I'm not sure if this is intentional since Blockbase is an FSE theme and maybe it's expected to use FSE feature, so it should use Social Icons Block instead? 🤔  https://wordpress.com/support/wordpress-editor/blocks/social-links-block/

Also, I see a similar issue mentioned here, but I think it should be resolved?
https://github.com/Automattic/themes/pull/4467#issuecomment-907050936

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Blockbase

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement/No workaround

### Workaround details

I edited my response here. 

The workaround is... Inconsistent. I can do this workaround on my test site, but it doesn't work on another:

1. Go to Settings > Full Site Editing
2. Activate FSE
3. You should see "Editor" under Appearance
4. Click it
5. _Do nothing_. You can play around with some blocks or Click All The Things™️ but you can definitely leave the editor without saving anything
6. Deactivate FSE
7. Ta-da, the icons reappear
<img width="1410" alt="Screenshot 2022-02-07 at 4 27 05 PM" src="https://user-images.githubusercontent.com/44726232/152751450-92208d5f-3ae5-4763-a0e6-9bdd3b2451b3.png">
 
(Don't mind me as I'm going "... why and how" here.)

However, again, please notice the workaround is **inconsistent**. It worked on one of my personal site, but not on others

**Comment by retnonindya** [comment]
Another report here:
4755744-zd-woothemes

**Comment by Greatdane** [comment]
Weirdly, on a self-hosted site, this seems to cause a critical error.

**Comment by scruffian** [comment]
I'm finding this hard to replicate. I can see it on danielwalsh.net but not on my test site with the FSE flag disabled. Are there other steps needed to deactivate FSE?

The root of the problem seems to be that some sites return `twitter` as a service for these links but in other cases we return `twitter-profile`.

**Comment by Greatdane** [comment]
@scruffian - on a self-hosted site as well? I was able to replicate on both (with different results).

**Comment by scruffian** [comment]
I haven't been able to replicate on a self hosted site. Can you run through the steps?

**Comment by supernovia** [comment]
> Can you run through the steps?

I'm able to pretty consistently replicate it, even with a brand new site, so long as I don't choose FSE.

- Create a new site. Choose to write a post.
- Use /wp-admin/nav-menus.php to create a social menu and set its location to social. Save changes.
- View the site. Notice the links look like this:

<img width="170" alt="Screen Shot 2022-03-12 at 12 41 05 PM" src="https://user-images.githubusercontent.com/3476361/158032553-4dc9c9ba-40e3-44b9-b9fb-80396b957945.png">

I'm getting the same issue in Zoologist, but the very same menu works in Hever as well as Skatepark, so it seems to be a theme-related issue.

**Comment by supernovia** [comment]
Also, I want to note this user ([AP link](https://app.agorapulse.com/inbox/twitter/95251?oldestFirst=true&item=1502690523110387712)) already has FSE active, so that isn't a workaround in this case. But their templates and template parts are all in the default state. If we click Edit Site, I see this, as though the navigation doesn't actually exist yet:

<img width="371" alt="Screen Shot 2022-03-12 at 12 58 03 PM" src="https://user-images.githubusercontent.com/3476361/158033141-fd5deb1e-30b4-4cfb-ad2f-d24569d33137.png">

I won't edit their template for them; since they're default they should just work.

If I view the site and check the source, I get this list item. Notice **wp-social-link-** doesn't specify a social network.

`<li style="color: var(--wp--custom--color--primary); " class="wp-social-link wp-social-link- wp-block-social-link">`

It's missing the `wp-social-link-twitter` class that makes it work in other themes:

`<li style="color: #000000; " class="wp-social-link wp-social-link-twitter wp-block-social-link">`

**Comment by mxhassani** [comment]
Similar case in 4855269-zen

Was able to replicate on a simple site but not on an AT site 

Customizer in simple sites shows the "Social menu" location on simple sites:

![image](https://user-images.githubusercontent.com/81776920/158055355-7fa467fc-99fc-420a-af9b-0b9b9aaca955.png)

It doesn't show it on AT site: 

![image](https://user-images.githubusercontent.com/81776920/158055491-558af369-1508-400f-901d-d8a333226f23.png)

**Comment by scruffian** [comment]
Are you able to share some example sites where this is a problem? Thanks!

**Comment by mxhassani** [comment]
@scruffian My test sites are here:

* [AT](mxhtestwoo.wpcomstaging.com) (Was using Skatepark theme then switched back to Blockbase)
* [Simple](mxhpremium.wordpress.com)

**Comment by scruffian** [comment]
On https://mxhpremium.wordpress.com/, the links aren't social links - they don't go to well know social networks - they are in fact internal links, so I wouldn't expect the icons to work.

On https://mxhtestwoo.wpcomstaging.com/ I am seeing the correct icons at the moment
<img width="121" alt="Screenshot 2022-03-14 at 12 25 13" src="https://user-images.githubusercontent.com/275961/158171619-b1e97ba0-4e28-4eef-9505-96a4e9e9e6c8.png">

Was it broken on Skatepark? Would you mind switching it back to the broken state?

**Comment by mxhassani** [comment]
@scruffian The links may have changed during testing but the issue is still there. 
[Simple](PdgIMe-qy-p2) site setting: 
![image](https://user-images.githubusercontent.com/81776920/158240675-5f3ef49d-dbba-4f09-9233-8af62f4ff741.png)

[AT](https://mxhtestwoo.wpcomstaging.com/) settings:
![image](https://user-images.githubusercontent.com/81776920/158241155-7ff5ce9b-ce1d-4be5-a96a-7aeb9222cffc.png)


![image](https://user-images.githubusercontent.com/81776920/158241529-b7537ab8-4407-4b0c-98ae-3c1a4626d0a7.png)

There is no control over the social menu.

-
[AT site](https://mxhtestwoo.wpcomstaging.com/) After switching back to Skatepark: 

![image](https://user-images.githubusercontent.com/81776920/158241898-886c63b2-4df6-432e-8c3c-3eef1063e3ee.png)

-

Are there any cases where it's normal to see different menu locations options for the same theme? 

Feel free to SU and test with the two sites

**Comment by alliebbush2** [comment]
This is also occurring for this user in this ticket: 4866649

**Comment by scruffian** [comment]
This seems to be an issue on dotcom, where the navigation items aren't being detected at social profile links. I can't work out to replicate it.

**Comment by jffng** [comment]
This should be fixed + deployed by D77088-code.
