### ISSUE TITLE
Archeo: Make header and footer wide-aligned

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5599]
Currently, the header and footer are not in alignment with the rest of the default page content. They should both be wide aligned. 

Currently: 

<img width="1512" alt="Screen Shot 2022-03-01 at 2 12 24 PM" src="https://user-images.githubusercontent.com/1202812/156233911-b5557c88-46bd-49e1-a224-0a24b5391b6f.png">

<img width="1512" alt="Screen Shot 2022-03-01 at 2 13 07 PM" src="https://user-images.githubusercontent.com/1202812/156233913-674926a0-d169-43f2-a97f-5000dc70799c.png">

**Comment by madhusudhand** [comment]
@kjellr I have done a quick check. Following are the observations.

Header and footer both seems to be aligned good with post except for a minor alignment for post title.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/1935113/156498343-119e8eaa-fd1f-4a09-b28c-f35c50e86d20.png">

Also aligned with **Selected writings** section

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1935113/156498977-bd70b99c-ece8-4c5e-8c5b-078f0f5074f2.png">

As you mentioned, only the default body doesn't seem to be aligned with header and footer.

Are you suggesting to
1. shrink header, footer and post to match with body
2. or expand body area to match header?

**Comment by madhusudhand** [comment]
Also the footer text is not centre aligned in smaller screens.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/1935113/156500794-58101650-9a49-4d7a-9f2a-020659b04141.png">

**Comment by MaggieCabrera** [comment]
@kjellr I'm working on this one, and none of the home page patterns are actually wide aligned, do we want to change that? 
The header not aligning to the right text on the first pattern is because of the padding in the pattern. We can remove just that and keep everything aligned full width or we can align everything wide, including the header, but that makes everything look a bit smaller than the design (and the last pattern gets a padding right for the floating image).

I'm going to make a PR with the first option, which I think looks closer to the design with less changes and headaches but you let me know if you prefer everything wide aligned.

**Comment by MaggieCabrera** [comment]
Nevermind! the padding right is added by the media+text block styles and can only be overridden via CSS, so I'm not sure what to do here, I guess the option is make everything wide aligned then?

**Comment by kjellr** [comment]
Interesting! I'd assumed that the content was all wide-aligned. 🤔 Let me dig into your PR on Monday and we'll sort out a solution here.
