### ISSUE TITLE
Dyad 2: Unable to change site header image - remains blank

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#56]
## Steps to replicate

User is unable to change the site header on https://allnaturalbeautyandhaircare.com using the Dyad 2 theme. Even though a new image is selected, the header background remains black.

![](http://cld.wthms.co/cOE092+)

I installed the theme on a test site and was unable to reproduce the issue. In my test site, the header image updated as expected.

## Result

Selecting a new header image had no effect. This includes selecting one of the default header image options.

## Expected

When selecting a new header image, the site header should update to present the selected header image.

* User report: 1051778-zen
* User's site: https://allnaturalbeautyandhaircare.com

**Comment by laurelfulford** [comment]
Dyad's header behaviour's a bit confusing; I think that's what's causing the problem here:

Dyad will only use the Custom Header image if you're not using Featured Content. If you're using Featured Content (like this site is), the background image will be coming from those posts' Featured Images instead. 

To get a background image displaying, a featured image could be added to that featured post: https://allnaturalbeautyandhaircare.com/2018/02/08/the-journey-begins/.

Or, to use the Custom Header image, the Featured Content could be removed entirely. 

Since this is working as expected, I'm going to close this.

**Comment by pauljacobson** [comment]
Thanks for your feedback, @laurelfulford. I'm not sure that this addresses the issue in this case. Even if the Featured Content section of Customizer is cleared (so no specified tag), the site header image doesn't load:

![](http://cld.wthms.co/z84qZD+)

**Comment by kathrynwp** [comment]
The default tag is "featured" - have them try removing the "featured" tag from this post:

"Why Shop All Natural And Organic  ?"

**Comment by laurelfulford** [comment]
Good call @kathrynwp -- thanks!

@pauljacobson You'll know the featured content is no longer being displayed when the label "featured" no longer shows above the main text in that area, and the section displays the site's tagline rather than a post, with no excerpt below -- kind of like:

![](https://cldup.com/o4-gHG0H2n.thumb.jpg)

**Comment by alaczek** [comment]
@pauljacobson I'd suggest the same - remove the tag from the post and see if that helps. In any case, I don't believe this to be a Dyad issue - it's much more likely to be a problem with Featured Content.

**Comment by laurelfulford** [comment]
Looks like this has been sorted on the user's site -- it's showing the custom header image now, not a featured post -- so I'm going to close this one.
