### ISSUE TITLE
Livro: Newsreader font is no longer loaded

### ISSUE THREAD

**Issue by markhowellsmead** [Automattic/themes#5705]
## Steps to replicate

The Newsreader font is still defined in CSS but the font file/s are no longer loaded.

## Result

The website typography appears in the standard browser fallback serif font.

## Expected

The Newsreader fonts in the assets folder should be loaded by the theme.

**Comment by jffng** [comment]
Thanks for the report, we just made the switch to [load the fonts via theme.json](https://github.com/Automattic/themes/pull/5609) since Gutenberg was upgraded, my guess is this is an artifact of some caching.

Newsreader is loading on the demo site, so I'm going to close this:

<img width="1904" alt="Screen Shot 2022-03-18 at 11 44 57 AM" src="https://user-images.githubusercontent.com/5375500/159035940-8af11be2-995b-4172-ae21-7aa58033f1e1.png">

**Comment by markhowellsmead** [comment]
@jffng Font still not loading even with caching disabled on the site and it's running the latest version of the theme (1.0.9). There is no reference in the source code to the WOFF files. If I look at the documentation for theme.json, there is no reference that the src attribute is supported for `fontFamilies`.

**Comment by jffng** [comment]
The Webfonts API was recently added https://github.com/WordPress/gutenberg/pull/37140, and the theme.json documentation needs to be updated accordingly. This feature is not in core yet, are you running the Gutenberg plugin?

**Comment by markhowellsmead** [comment]
No, I'm using the Theme directly from https://wordpress.org/themes/livro/. The Gutenberg plugin is highly unstable and often breaks functionality, so it's not possible to use it on a production site. I'm guessing that this issue is happening for the 200+ other non-WordPress.com users too, unless they're using the plugin.
