### ISSUE TITLE
FSE Beta: Custom palette colors go away when saving a change in the Customizer

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#5740]
### Quick summary

The custom palette disappears when saving a change in the Customizer

### Steps to reproduce

1. Set a custom color inside FSE using the **"Styles" > Colors > Palette > Custom** option
2. Assign the color
3. Save the changes
4. Preview the site. All good!
5. Go to the Customizer and make a change, like the font, and save changes
6. Notice the custom color is gone

https://user-images.githubusercontent.com/3696121/149391819-b0dd8897-caf5-49f3-9749-b9c39041fa07.mp4

### What you expected to happen

For the custom colors to be preserved.

### What actually happened

The custom colors were lost.

### Context

Dogfooding

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I tested using the Zoologist theme

### Browser, operating system and other notes

macOS Monterey 12.1 (21C52)
Chrome Version 97.0.4692.71 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by mikeicode** [comment]
I should have mentioned, it was a Blockbase child theme I was using, so that makes sense ^.

**Comment by pbking** [comment]
This was intentional but perhaps not the best. Blockbase used to store user customized theme colors in the "custom color" space. When it was refactored it started clearing the user color space on save so that the theme-stored values would be used. Rather than clearing them all this should probably instead only clear those "custom" values that are meant to be stored at the theme level.
