### ISSUE TITLE
Blockbase theme generates a warning in console

### ISSUE THREAD

**Issue by ghost** [Automattic/themes#5760]

**Comment by pbking** [comment]
The error is because the CSS is build from SASS and has the following in the ponyfill.css: `/*# sourceMappingURL=ponyfill.css.map */` signifying that there is a map file to see how the styles originated before compilation.  However our build process removes "unnecessary" resources when building the zip (and the .map files are considered unnecessary).

Fixing the problem would require that we EITHER:
* Don't build map files when compiling the sass
* Remove metadata from the .css files when building theme zips
* Include the map files in the theme zips

I'm not sure which option is better.  Since it doesn't impact the site working in any way (just the developer experience) I'm not sure that any of the options will be of high priority to address.
