### ISSUE TITLE
[Remote] Contact form field text size is very small

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5777]
Like #5776, I'm not sure if this is something we'll sort out on the theme's end or not. But logging it just in case. 

The text size for single-line form fields is really small: 

<img width="693" alt="Screen Shot 2022-03-28 at 10 17 59 AM" src="https://user-images.githubusercontent.com/1202812/160418262-024bf137-1d48-43ef-a8da-322af21f3be1.png">

**Comment by mikachan** [comment]
I think this would be a fix in Jetpack rather than the theme.

At the moment, the `textarea` font size is set to `inherit` (via `.contact-form textarea` [here](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/contact-form/css/grunion.css#L38)). There doesn't seem to be any similar overrides for the `input` boxes. If I set `inherit` on the inputs as well, the font size defaults to the normal preset, the same as `textarea` does, so this is a possible solution.

**Comment by MaggieCabrera** [comment]
Closing this in favor of https://github.com/Automattic/jetpack/issues/23729
