### ISSUE TITLE
Pendant: Display only the first category

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5872]
Maybe omitting categories isn't a good practice, but I'd like to know your opinion: is it possible to avoid this visually when there are plenty of categories? Perhaps showing only the first or main category. Or having "Antique & Vintage Jewellery _and More_"

<img width="1489" alt="Captura de ecrã 2022-04-14, às 16 45 30" src="https://user-images.githubusercontent.com/65220155/163426393-97df9163-7fc6-4d1e-a712-6a08512f2c1f.png">

**Comment by pbking** [comment]
I'm not sure that this is a thing that can be accomplished with the block... I think I COULD do some CSS trickery to make anything after the first be `display:none` but that seems dangerous in practice since then there wouldn't be an option for a user to leverage multiple should they want to.

A better solution, I think, is to just add a single category to the post giving that control to the user to decide.

**Comment by beafialho** [comment]
> A better solution, I think, is to just add a single category to the post giving that control to the user to decide.

Giving users control also seems like the best approach to me. I'm not sure I get your solution though, do you mean leaving it as it is?

**Comment by pbking** [comment]
Yea, that what I mean; just leaving it as-is and if the user only wants to show one category they just assign one category to the post.

Going to close this with that in mind, but if you have other thoughts on the matter please open it back up.
