### ISSUE TITLE
Twenty Nineteen: Request for a search box in the header

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#593]
## Feature request

This theme doesn't have a handy search option. Because the widget areas are only in the footer, there isn't a convenient way to search for posts short of scrolling to the footer in the hope that there's a search option there.

## Suggested solution

I don't know how this could be implemented but I'd love to have an option to add a search bar to the site header from the Customizer.

**Comment by laurelfulford** [comment]
Thanks for this report, @pauljacobson!

Since this isn't specific to the WP.com-version of the theme, it should be reported in Core Trac. I did a quick look, and it looks like this isn't the first time it's been requested :) https://core.trac.wordpress.org/ticket/45917

I'm going to close this issue in favour of that one!
