### ISSUE TITLE
Rainfall:  Search Template

### ISSUE THREAD

**Issue by ajlende** [Automattic/themes#6177]
We created a search template for Rainfall that looks like this. What are your thoughts?

![rainfall search template](https://user-images.githubusercontent.com/5129775/178242565-86d53283-191c-4da9-ad9b-6e62cb2dc005.png)

@beafialho

**Comment by beafialho** [comment]
Thanks @ajlende. A few comments:

- For the query block with the posts, it might be better to switch the order of the images in every template that has this appearance, so that when there's no featured image the list looks more balanced.
- The distance between the separators in the query loop should always be the same.
- I also added an example of how the search bar should look [here](https://www.figma.com/file/oz0a2czNn0UNt9onrh8T5a/Rainfall?node-id=798%3A211).

Also adding a screenshot of what I mean:
![Search](https://user-images.githubusercontent.com/65220155/178250210-b8b86c7b-0800-4ebc-afe4-5802ce7ba77f.jpg)

**Comment by scruffian** [comment]
This is now done
