### ISSUE TITLE
Livro: Add white/light style variation

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#6276]
Livro does not have an option to switch to a "white/light" style. We should add a style variation for this, effectively inverting the colors that are the default.

## Expected

@simison @beafialho can you please help to clarify the design requirements here, if this is a simple matter of switching colors or if there was something else more specific in mind for this?

**Comment by mtias** [comment]
We discussed this with @beafialho a few weeks ago. Just a a version that has dark text on a pure white background.

**Comment by beafialho** [comment]
That's right, just a change in color. Besides the "White" one, I also created a "Cream" one. Since this theme is suitable for long reads, it could be a nice addition.

They can both be found [here](https://www.figma.com/file/ALdcQWdMu3wmdoNv59VwYl/Livro?node-id=508%3A11).

White:
![White](https://user-images.githubusercontent.com/65220155/180747433-31538ab5-b58b-44c1-9d5a-1a003466efd1.png)

Cream:
![Cream](https://user-images.githubusercontent.com/65220155/180747423-ba99667a-0392-4ed3-8930-403028efa9e4.png)

**Comment by jeffikus** [comment]
#6359 has been merged and deployed. Closing this, if the button issue persists @vcanales please open up a separate issue. Thank you!
