### ISSUE TITLE
Lettre Theme: “Leave a reply” why is it in italics?

### ISSUE THREAD

**Issue by ebinnion** [Automattic/themes#6658]
### Quick summary

See pbAok1-3fI-p2#comment-5563 for more details, screenshots, figma, etc.

The figma calls for "Leave a reply" to not be italic. But, it is.

### Steps to reproduce

1. Start at wordpress.com logged-out
2. Click Newsletter tile and work through use case
3. At the end of the flow, publish a post and view frontend of site
4. Verify that "Leave a reply" is in italic

### What you expected to happen

Leave a reply to not be in italics

### What actually happened

The opposite

### Reproducibility

Consistent

**Comment by alaczek** [comment]
I'm not seeing the Leave a reply title in italics on either Simple or Atomic, so this must have been fixed at some point:

Simple site:
<img width="721" alt="image" src="https://github.com/Automattic/themes/assets/4550351/ed40e5bd-e233-4fc5-9043-4fdcb36488f4">

Atomic site:
<img width="715" alt="image" src="https://github.com/Automattic/themes/assets/4550351/6f692ccf-d0b8-44d5-b5b4-1f718d6e3e85">
(we're working on addressing the missing gap under the title on Atomic)

**Comment by pkuliga** [comment]
Closing it since the "Leave a reply" is not in italics. Tested on Simple and Atomic.

<img width="668" alt="Screenshot 2024-03-12 at 09 03 17" src="https://github.com/Automattic/themes/assets/4068554/3ebfd802-4591-482a-9a8a-559c0aae1c97">

<img width="668" alt="Screenshot 2024-03-12 at 09 03 09" src="https://github.com/Automattic/themes/assets/4068554/ee7c1a72-d60e-47c7-b585-eed4f8ace05c">
