### ISSUE TITLE
[Bug]: Archeo: The 'Layered images with headline' pattern has block errors on wpcom

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6673]
### Quick summary

The pattern included in Archeo named "Layered images with headline" has a block error on wpcom.  

<img width="318" alt="image" src="https://user-images.githubusercontent.com/146530/196539736-189651e4-d283-4443-8ca3-20ceb8cc3beb.png">

This pattern is included in the "Home" page so when a user replaces their homepage with the theme content this markup is included.

The pattern is rendering as expected locally.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/146530/196539968-6d0ee2a8-1eb1-4eef-9fbb-9bdea7e6d7d0.png">

From what I can tell the markup is the same and nothing has jumped out as being incorrect.

### Steps to reproduce

Activate Archeo.

Add the pattern "Layered images with headline"

### What you expected to happen

There wouldn't be block markup errors

### What actually happened

There are block markup errors

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

**Comment by mikachan** [comment]
When I click 'attempt block recovery' or when I headstart Archeo, and then copy the paragraph from this pattern, I see a double paragraph element, like this:

```
<!-- wp:paragraph {"style":{"typography":{"textTransform":"uppercase","fontStyle":"normal","fontWeight":"100","lineHeight":"1"}}} -->
<p style="font-style:normal;font-weight:100;line-height:1;text-transform:uppercase"><p style="font-size:clamp(64px, 6vw, 100px);font-style:normal;font-weight:100;line-height:1;text-transform:uppercase">Palace of <br>the Circus at <br>Chichen-Itza, <br><em>bas-relief</em> of <br>tigers</p></p>
<!-- /wp:paragraph -->
```

I'm wondering if the editor wants this to be two paragraphs instead of one for some reason, maybe in order to apply the styles/settings?

This doesn't explain why it doesn't error like this locally, but thought this might help trigger some ideas.
