### ISSUE TITLE
Blank Canvas 3: Reconsider the Font Scale 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#6721]
### Quick summary

Hi, this is not a bug report but more of a suggestion. 

We could give a little more contrast in sizes in Blank Canvas 3. Especially between `small` and `medium`. https://github.com/Automattic/themes/blob/c98ca110e779c0f496e70a7d8fa813c79de54deb/blank-canvas-3/theme.json#L95

**Context:** @alaczek and I noticed a pattern using the Pattern Assembler doesn't quite have a good contrast in the scale. This pattern uses small and medium, but as you can see, they are very similar.

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/908665/201170390-3e9026bc-5c0c-472b-8fb3-bcae459011f6.png">

### Steps to reproduce

Test Pattern Assembler `pbxlJb-2wa-p2`

### What you expected to happen

They should have a better font scale that has good contrast in sizes.

### What actually happened

The small and medium sizes have very little contrast in size.

**Comment by iamtakashi** [comment]
Forgot ping. @onuro

**Comment by onuro** [comment]
@iamtakashi I agree. The medium and small sizes are copied from TT3 being unchanged. I'm testing 2 options:

### 1. Medium max(fluid) font size to be _1.25rem_ instead of 1.125:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/645713/202024553-9adb62c1-62eb-4e90-abbf-6564ee098292.png">
In the BC3 the default text size is also medium.

### 2. Medium font size to be unchanged but less "small" size:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/645713/202025579-eddf8113-6bd9-4c3e-ae36-4fa7c1aa6e9e.png">


What do you think?

**Comment by iamtakashi** [comment]
> 2. Medium font size to be unchanged but less "small" size:

What's the max size of small in this case?

**Comment by onuro** [comment]
> What's the max size of small in this case?

Min 0.875rem and max 1rem

**Comment by richtabor** [comment]
@iamtakashi is this still relevant? Thanks!

**Comment by iamtakashi** [comment]
@richtabor I don't think so. I'm closing the issue but reopen it if it needs.
