### ISSUE TITLE
Muscat Theme: Homepage title looks too large on mobile

### ISSUE THREAD

**Issue by fushar** [Automattic/themes#6813]
### Quick summary

When I open my site that is using Muscat theme on my mobile phone, the title font size looks way too large and we need so scroll way down to see the blog posts. Is this intended?

|![image](https://user-images.githubusercontent.com/1525580/210732255-942f95ea-5968-406f-bdfe-b020ed58e8bc.png)|![image](https://user-images.githubusercontent.com/1525580/210732371-ff9c9b1d-34e9-46e3-802a-8fab7e154ed2.png)|
|-|-|

### Steps to reproduce

Open the site with Muscat theme on your mobile phone.

Alternatively, it can be easily reproduced if you open Site Editor and click View -> Mobile:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/1525580/210732354-822487e6-fdc7-491b-9642-66df30e8f936.png">

### What you expected to happen

The homepage title (and the whole homepage) is readable and is comfortable to read

### What actually happened

The homepage title is way too large

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by annezazu** [comment]
The same is happening when going through the onboarding flow on WordPress.com. The big, bold header ends up looking cut off. @jeffikus can you look into this and ensure fluid type is doing what it's supposed to do on this theme so that it looks good?

![image (31)](https://user-images.githubusercontent.com/26996883/214895416-5cdd4103-3110-4b1c-b2ba-d2be95a18107.png)

**Comment by jeffikus** [comment]
@beafialho is this possibly related to the original technical issue you mentioned here pNEWy-fBL-p2 ?

**Comment by beafialho** [comment]
This seems to be working now, I'll close this issue.
