### ISSUE TITLE
Feature request: Notification while switching from a Retired theme

### ISSUE THREAD

**Issue by nazilya06** [Automattic/themes#6948]
### Quick summary

The user would like to receive a notification while switching from the Retired theme, stating that returning to the retired theme won't be possible.

The notification might sound like this:
"If you switch to another theme, you will not be able to change back to a theme that has been retired. Retired themes are not available to activate again, even if you have used it before.”

### Steps to reproduce

1. Once the website is using the retired theme 
2. Go to Appearance → Themes. Choose the theme 
3. While clicking on Activate, a notification should pop up asking to confirm the change and explaining the consequences.

### What you expected to happen

The notification (alert) will let the user know it is impossible to revert the theme change. 

It will decrease the amount of Zendesk tickets about "why am I not able to find my old theme".

### What actually happened

Currently, there is no warning about not being able to switch back to the Retired theme. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

https://woothemes.zendesk.com/agent/tickets/6052765

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

### Workaround details

-

**Comment by Aurorum** [comment]
We did a lot of work around this in Automattic/wp-calypso#40793, but it was ultimately decided that this feature should not proceed. I can't recall the details, but I think it was partly about encouraging users to switch from retired themes rather than adding obstacles/warnings. 

I don't believe that decision has been reversed, so I'd recommend closing this.
