### ISSUE TITLE
Lettre: Update inline space from 200px to 100px

### ISSUE THREAD

**Issue by simison** [Automattic/themes#7069]
Via p9Jlb4-787-p2

@crisbusquets wrote:

> Right now, the div with `.wp-block-spacer` has an inline height of 200px. This seems to work well on big screens, but on mobile it takes up too much space.
>
> I would suggest reducing it a bit, maybe 100px, so that the reader can read more content without scrolling. I’m aware that our customers can modify this in the Editor, but perhaps we can adjust this in the basic Lettre theme.
> 
> Here’s a comparison:
> 
> ![Image](https://github.com/Automattic/themes/assets/87168/c9a299cc-1c10-41f0-ba74-f3dc603e00a3)
> 
> ![Image](https://github.com/Automattic/themes/assets/87168/af159bdd-41e8-48f6-ba2f-a555b656b9cd)
> 
> And mobile:
> 
> ![Image](https://github.com/Automattic/themes/assets/87168/d719368d-8a7a-4977-8356-a6964358eddc)
> 
> ![Image](https://github.com/Automattic/themes/assets/87168/ed04f115-702a-4107-80da-0745869665da)

**Comment by edanzer** [comment]
@crisbusquets @simison - The height of the block (200px) is based on a setting in the spacer block from WordPress core. Unfortunately, the block settings do no allow for different heights based on screen size (many of the more sophisticated block do allow this, but the core block does not). 

If we do it via custom css, we're kind of going outside the 'normal' WordPress way of doing things, which creates complications. For example, to change this, users would need to know that we added custom css, find the css, and updated it there, rather than updating it visually from the block editor. 

Thoughts on how we'd want to handle this?

**Comment by simison** [comment]
@edanzer we can have the space 100px across desktop and mobile, works well on both then.
