### ISSUE TITLE
Text size for Lesson Progress and Exit Course LM Default Theme

### ISSUE THREAD

**Issue by Luchadores** [Automattic/themes#7112]
### Steps to Reproduce
1. Start a lesson with the default LM theme active.
2. Notice how the Lesson Progress and Exit Course fonts in the header are too large. 

### What I Expected
The fonts for the Lesson Progress and Exit Course should be ~18px~ 16px, not 24px. They look too big right now in comparison with the title of the Course on the left side. 

### What Happened Instead
The fonts are at 24px, paragraph size, too big for the header.

### PHP / WordPress / Sensei LMS version
Latest Jurassic Ninja site + Sensei test packages from [here](p6rkRX-6lo-p2).

### Browser / OS version
Chrome Version 113.0.5672.126 / Ventura 13.3.1 (a)

### Screenshot / Video
Live
<img width="1728" alt="image" src="https://github.com/Automattic/sensei/assets/10038976/12319d50-d6d5-4f49-8f1c-a7a64f18ad22">

Design
<img width="1613" alt="image" src="https://github.com/Automattic/sensei/assets/10038976/72e493cc-2a30-4583-afb6-82e128886d6a">

**Comment by donnapep** [comment]
Hi @Luchadores. The font size of lesson progress and Exit Course is actually already 18px, whereas the course title is 24px. These elements actually use fluid font sizes, so they'll range between 14 and 18px. I'm guessing it looks bigger because of the different font families that are being used?

![Screenshot 2023-05-30 at 8 39 43 AM](https://github.com/Automattic/sensei/assets/1190420/17799d00-473d-4193-8457-b79157cd3fa4)

**Comment by Luchadores** [comment]
Could be? That specific theme design uses SF Pro Text for the UI elements.

**Comment by donnapep** [comment]
Would you like me to make it smaller (say `16px`)? Or should we just close this issue?

**Comment by Luchadores** [comment]
If possible, yes. Let's lower it for this theme to 16px for the top bar. Thank you @donnapep 🙌
