### ISSUE TITLE
What does the `optOutOfParentStyleVariations` option do?

### ISSUE THREAD

**Issue by martisj** [Automattic/themes#7295]
https://github.com/Automattic/themes/blob/564a3d8023d81196acd6b6a341e604108d3c34a3/blockbase/theme.json#L96

I can't find it in the JSON schema either: https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json

**Comment by pbking** [comment]
It's a custom attribute used by Blockbase (or specifically Blockbase Children).  You can see it's usage [here](https://github.com/Automattic/themes/blob/trunk/blockbase/inc/rest-api.php#L18).

It prevents child themes from surfacing the Blockbase variations to the user (for cases where the child theme design doesn't work with the Blockbase variations).  Those variations weren't originally made available to users and when that change happened we introduced that custom property so that child themes could opt out.
