### ISSUE TITLE
Erma: Posts without featured images are invisible on the front-end

### ISSUE THREAD

**Issue by dsas** [Automattic/themes#7355]
### Quick summary

Adding a post without a featured image means that the post doesn't show up anywhere, though a gap is reserved for it.

There's no hint that this is the case, the theme info page doesn't mention it, there's no in-product help

Posts | Display
-------|------
<img width="1631" alt="Screenshot 2023-09-11 at 12 09 56" src="https://github.com/Automattic/themes/assets/93301/54b5e4f4-de03-400d-a1c1-14b94e0d3122"> |<img width="1555" alt="Screenshot 2023-09-11 at 12 09 25" src="https://github.com/Automattic/themes/assets/93301/ad5c5307-700a-4aa9-b542-2c98ea9a99cc">

### Steps to reproduce

1. Activate the [Erma theme](https://wordpress.com/theme/erma/)
2. Create a post without a featured image
3. Create a post with a featured image
4. Look at the homepage

### What you expected to happen

To see two posts

### What actually happened

Only the post with the featured image can be seen 

### Browser

Mozilla Firefox

### Context

Testing while investigating another customer reported issue

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Add a featured image to every post

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated.  This does appear to be working by design (as the Query Loop Block that creates the homepage will show no result for posts without a featured image), but this is a bit of a confusing design.

![Markup on 2023-09-11 at 14:08:12](https://github.com/Automattic/themes/assets/27249804/0e766062-0011-419c-a8eb-d67980868bbe)

📌 ACTIONS
- Added to bug scrub planning

**Comment by beafialho** [comment]
This theme was designed for someone who wants to build a portfolio, which means they'd always want to add a featured image to each post/project. The layout from the screenshot could be achieved manually, without a query loop, but in my opinion it's a much more cumbersome way to manage and edit your posts/projects. A portfolio theme should work seamlessly and differently than a blogging theme. I don't see the point in changing this template, because this theme is built for visual content and I agree with @dsas's workaround suggestion.

To make this even clearer, I added the following to the description in the showcase:

**Erma is a WordPress portfolio block theme that features gorgeous imagery and modern layouts. With two unique style variations and elegant templates, Erma is the perfect choice for artists, designers, and other creative professionals looking to showcase their work in an eye-catching way. The theme's design is clean and sophisticated, allowing your portfolio pieces to take center stage. Erma was designed primarily for visual content, which means that featured images are essential to achieve a beautiful homepage layout.**
