### ISSUE TITLE
Hever theme CSS cascade order changes buttons on Atomic sites

### ISSUE THREAD

**Issue by msilbers** [Automattic/themes#7374]
### Quick summary

On a simple site using Hever, you can set buttons to be colors set from Customizer, including Primary and Secondary color, as well as custom colors. This all works.

Once the site goes Atomic, any button set to Primary will be overridden by the color set for buttons on the overall site, ignoring the button block selection. It also changes the styling.

### Steps to reproduce

1. Create a simple site using Hever
2. Head to Customize > Colors and Backgrounds and change the Primary Color to pink (for example)
3. Add a button block and set the background to the Primary Color
4. Install a plugin to go Atomic

### What you expected to happen

Nothing

### What actually happened

The buttons turn black (or whatever color is overriding)

### Context

reported by a customer in 6817329-zen

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

test page: https://teristhsadkdsjadlsaksajdkfds.wpcomstaging.com/10-2/
the button on that page is set to Pink

simple site image:
<img width="466" alt="Screen Shot 2023-09-15 at 5 38 15 PM" src="https://github.com/Automattic/themes/assets/31680407/1fa9bf3a-e9d7-44fe-b2b1-927842972af4">

Atomic image with no other changes:
<img width="461" alt="Screen Shot 2023-09-15 at 5 42 39 PM" src="https://github.com/Automattic/themes/assets/31680407/d54e676f-36da-4549-9318-36acca52fbd9">

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

None

### Workaround details

We can add CSS back from the theme itself, into Additional CSS in the customizer, so that it comes later in the cascade

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple/Atomic – Could Not Replicate/Duplicate

📌 FINDINGS/SCREENSHOTS/VIDEO
On my test site using theme Hever, the buttons blocks responded the same way on Atomic as they did on Simple.  Primary, Secondary, Foreground, and Background color changes also impacted the buttons blocks consistently.  Changing the Tertiary color did not impact the button, but this was consistent across Simple/Atomic, so that look to be a separate quirk of the theme.

**Simple**

https://github.com/Automattic/themes/assets/27249804/78e29c6f-cb96-47dd-89b3-82813515aca5

**Atomic**

https://github.com/Automattic/themes/assets/27249804/797c5807-6993-4a88-8525-654e8ef1e743

---

However, the live site does show the unstyled buttons - this is actually a symptom of a Page Optimize conflict, which is reported here: https://github.com/Automattic/themes/issues/7309

https://github.com/Automattic/themes/assets/27249804/1b22f1ca-f94f-4a0b-a9df-a803ca0b3720

Deactivating the Page Optimize plugin, or disabling "Concatenate CSS Styles" is a workaround for that issue. 

📌 ACTIONS
- Closed as duplicate
