### ISSUE TITLE
Rebalance: Jetpack Search results modal doesn't load

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#7440]
### Quick summary

I was able to reproduce the user's issue with their theme, Rebalance, the Jetpack Search results modal doesn't load with it.  It worked fine when I tried Twenty Twenty Three.

I'm not sure if it's for the Theme team to handle, please transfer to https://github.com/Automattic/wp-calypso/ as needed. Sorry!

### Steps to reproduce

1. Create a Simple site
2. Select the theme Rebalance
3. Go to Jetpack > Search, then get the Free license
4. Still under Jetpack > Search, check that `Enable Jetpack Search` is enabled
5. Add a Search block anywhere
6. Test Search on the live site

### What you expected to happen

Search results modal should display.

### What actually happened

- Entirely blank page displays.
- It order for the results modal to show, I need to manually reload the page, or load the search URL directly (for example: `https://url-example.wordpress.com/?s=love`)

### Context

Customer report: 7181532-zd-a8c

### Platform (Simple, Atomic, or both?)

Only tested Simple.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

User another theme.  I tested with Twenty Twenty Three, and Jetpack Search worked fine.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
With Theme: Rebalance active on a free site, adding a free Jetpack Search Subscription does cause the Search results page to white-screen, rather than load search results:

**Jetpack Search (Free) active**

https://github.com/Automattic/themes/assets/27249804/d3446547-b2c1-4030-a432-12ed38e55887

**No Jetpack Search subscription added**


https://github.com/Automattic/themes/assets/27249804/93efcb52-3efe-4346-b9ad-a51e93da7e94

Switching to another default classic theme, Twenty Nineteen, did allow the search function to work:


https://github.com/Automattic/themes/assets/27249804/69d44ffe-a834-4b4c-95e9-7f6596c71865


📌 ACTIONS
- Triaged
- Added to Bug Scrub Planning
- CC @jeherve just as an FYI

📌 Message to Author
@formosattic - I read the customer's ticket, and they mentioned that the theme is working with Search on their other free sites. Those other sites do not have any Jetpack Search subscription at all - so it may be that they mistakenly added that, thinking that was needed.  If they cancel the free Jetpack Search subscription, then the site in question will work like their other sites do.

**Comment by formosattic** [comment]
Hi @cuemarie, seems like it's not entirely due to the subscription, user replied:

> I unchecked the "enable instant search" it started working.

I checked on my test site (still with Rebalance), but the page was still blank with Instant Search turned off, so I'm not sure what else is at play on the user's site.

**Comment by Robertght** [comment]
New report in https://wordpress.com/forums/topic/search-widget-in-footer/?view=all#post-4065895

I was able to replicate this and I believe it's quite important.

It only happens when the Instant Search is turned on, so turning it off is the only workaround that I could find.

Rebalance is currently active on 308,372 sites.

@wojtekn Can Groundskeeping look into this?

**Comment by wojtekn** [comment]
It seems that on Rebalance theme when I open the search window, the body gets opacity set to 0:

![Image](https://github.com/user-attachments/assets/49e85b1f-2abb-4164-a87b-491144031084)
