### ISSUE TITLE
[Bug]: Unclear how to change the background color on Overlaid theme

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#7564]
### Quick summary

The background color on the Overlaid theme doesn't apply to the archive template. 

### Steps to reproduce

1. Go to Appearance → Editor
2. Click on Styles → Colors → Background
3. Choose a color and save the changes. 

### What you expected to happen

The background color to be changed. 
![Screenshot_1](https://github.com/Automattic/themes/assets/129587477/ddb97978-5a5c-4dd1-ab67-5b237a00d57a)

### What actually happened

The background color doesn't change for the archive template.
![Screenshot_2](https://github.com/Automattic/themes/assets/129587477/c914cb24-3564-41de-8595-002c93fad935)

### Browser

Google Chrome

### Context

7475398-zen

### Platform (Simple, Atomic, or both?)

Both

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Partially Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
What happens is that the default theme setup gives a false impression that the Cover Block uses a narrow vertical image and a coloured background, when the image actually includes the "background" to give the theme its distinctive effect. 

Changing the background color works, but it doesn't affect the theme visually. The "background" only changes when the user changes the Cover Block image.

📌 ACTIONS
- Triaged
- Changed the title to make the issue clearer

📌 Message to Author
@AnjanaV93 see the explanation above.

@henriqueiamarino I know the theme is intentionally designed like this to achieve its particular look, but it also makes it very hard to understand how to customize the theme, since the source of the colored background is not obvious. It'd be important to document this particularly somewhere (possibly on https://wordpress.com/theme/overlaid/ and in the corresponding theme page on WordPress.org) so users have a least a chance to find how to customize this.

**Comment by filipanoscampos** [comment]
@liviopv Just tested this on my self-hosted site and could reproduce it.

Asked the themes team about this: p1704719924524229-slack-C029FM1EH

**Comment by henriqueiamarino** [comment]
Correct, @liviopv and @filipanoscampos, the theme was intentionally designed to offer a possibility our cover block does not offer yet. As soon as possible, I'll develop an update that uses a small/medium-centered image as a background to our query loop. In the meantime, I will add a note to the theme page as recommended — thanks for keeping this topic going.

**Comment by henriqueiamarino** [comment]
@liviopv @filipanoscampos, can you please review this paragraph? Please feel free to correct and implement. I will add it to the theme's page.

**The image used on the Cover block on the Homepage includes a frame of color (primary color) to work as intended, as the Cover block doesn't allow this control yet. So, after changing your primary/background, you will also have to update your image on an image editor of your preference. As soon as this feature is available, the theme will be updated, and all design tasks will be limited to the Editor.**

**Comment by filipanoscampos** [comment]
Thanks @henriqueiamarino.

How about something simpler such as:

To recreate the theme's effect of the image surrounded by color, please edit your image on the image editor of your preference to add color to both sides of the image.

**Comment by henriqueiamarino** [comment]
Simple is always better. Doing it, thanks.

**Comment by henriqueiamarino** [comment]
The issue was explained and documented on the [Theme Page](https://wordpress.com/theme/overlaid/), so users now have a chance to find out how to customize this.
As soon as this feature becomes available, the theme will be updated, and all design tasks will be limited to the editor.
