### ISSUE TITLE
Tenku theme: horizontal scroll on Single Posts template

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#7589]
### Quick summary

There's a horizontal scroll happening on the Single Posts template in Atomic sites only causing an excess of white space down the right side of the posts.

### Steps to reproduce

1. Activate Tenku on an Atomic site
2. Preview or view a post (that is using the Single Posts template with the default Header template part)
3. Scroll horizontally

### What you expected to happen

There to be no horizontal scroll.

### What actually happened

Any posts using the Single Posts template on an Atomic site are getting the horizontal scroll: ![jIewYJ.png](https://github.com/Automattic/themes/assets/42655541/91d9f5fc-5f12-4b03-9d58-bb9ef0e5b7f1)

### Browser

Google Chrome/Chromium

### Context

Customer report: 7546304-zen

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

I was able to replicate the behavior on my Atomic site.

I tried creating a new Single Posts template and the same issue occurred. 

It seems to be caused by the Search block in the default Header. Deleting the Search block resolves the issue. But the Pages template has the same layout, Header template part, and Search block and the issue doesn't occur there. So I'm not sure why the following is true:

This CSS seems to be the issue:

```
.wp-block-search__label {
    width: 100%;
}
```
Adding the following CSS fixes the issue:
```
.wp-block-search__label {
    width: 0;
}
```

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Adding the following CSS fixes the issue:
```
.wp-block-search__label {
    width: 0;
}
```
Using a different header template part also resolves the issue.

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue on my side. Both, preview and view a post that use the Single Posts template load fine for me:
![Markup on 2024-01-08 at 21:44:06](https://github.com/Automattic/themes/assets/9025643/688b96af-f56f-4519-a49d-81b6347852e1)
![Markup on 2024-01-08 at 21:41:42](https://github.com/Automattic/themes/assets/9025643/5167199c-1077-4d81-bb66-5cff85c60ec5)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by kspilarski** [comment]
Using the Tenku theme, posts using Single Posts template allow scrolling to the right. Using the CSS workaround fixes it. 
I was only able to replicate this on AT sites. There's no issue on simple sites using the Tenku theme. 

https://github.com/Automattic/themes/assets/36863633/eaf01272-3b2c-4556-af86-34992bc5cc74

7720452-zen

**Comment by ClassicRKR27** [comment]
I have another report of this here: 7735307-zd-a8c

The CSS workaround fixed it immediately.

**Comment by ClassicRKR27** [comment]
Another report here with the Twenty Twenty-Three theme this time: 7846600-zd-a8c

**Comment by jp-imagines** [comment]
Sharing a bit more information about that most recent report from @ClassicRKR27 (also discussed in p1709736147034119-slack-C03TY6J1A).

On that site, at least one page wasn't affected: the homepage. Digging into the browser inspector, it seems the _Page Optimize_ plugin may be the culprit here. I haven't had time yet to test this on another site yet, and I'm not certain it's the exact same issue for the original reports with Tenku, but the fact that this can only be replicated on Atomic suggests these may all stem from the same issue.

On that site's homepage, the "search label" element (`.wp-block-search__label.screen-reader-text`) is assigned a width by two different sections of inline CSS:

* First, it's assigned a width of 100% by `wp-block-search-inline-css` (specifically for the `.wp-block-search__label` selector).
* That is then overridden by a width of 1px from `wp-block-library-inline-css` (specifically for the `.screen-reader-text` selector).

The end result is the label appears at a tiny size that has no impact on horizontal scrolling, as intended.

On posts and other pages, the reverse happens: it's assigned a 1px width from a minified CSS file _first_, then it's assigned a 100% width from `wp-block-search-inline-css` (which isn't minified). The result is that the invisible label is rendered _way_ larger than necessary or expected.

Re-applying the `Needs triage` tag here, and pinging @maciejpilarski for re-triaging. If this can be replicated on multiple themes, it should probably be moved to `wp-calypso`?

**Comment by Neha93517** [comment]
Zen-7930214
The issue with YouTube video in comments causing the overflow ( previously reported here Zen-7846600 for a different element)

Workaround provided:
iframe {
    max-width: 100%;
}
Here is an example screenshot of what it looks like: (Replicated on test site)
![chrome-capture-2024-3-26 (2)](https://github.com/Automattic/themes/assets/54591499/b245b386-edcc-4e3e-a9b2-9367008c3e91)

Theme:  Twenty Twenty-Three

**Comment by tanjoymor** [comment]
The original issue as reported (by me) can no longer be replicated.

📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Authors
@jp-imagines I also wasn't able to replicate the scenario you outlined anymore either.
@Neha93517 This appears to be an unrelated issue. Please open a new issue if this still needs further investigation.
