### ISSUE TITLE
Classic themes x Woo: Woo single product page is not displaying the product when the site is using classic theme

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#7648]
### Quick summary

When the website has a classic theme active, the Woo single product page is not displaying the product when the site is viewed by guest. The product page on the live site only visible by the site admin.

So far, this issue happens on the following theme:
- Rowling
- Anemone (retired)
- Penscratch 2
- Lovecraft

### Steps to reproduce

1. Make sure the website is AT and has Woo active with products.
2. Activate any classic themes, e.g. Rowling
3. Open/view a single product page on incognito tab or a different browser to ensure you visit the page as a guest/not-logged in to the website
4. Notice the product is "missing"
5. Open/view the single product page as a logged-in, and you should see the product page works and displays the product as expected

### What you expected to happen

The single product page works and displays the product be it logged-in or as a guest

### What actually happened

The single product page only displays the product when the user is logged-in as the website's admin and it displays nothing when viewed as a guest.

### Context

Customer report and self-testing

### Other notes

Not sure if this is the correct log, but this is what I see on console:

```
Scripts that have a dependency on [wc-settings, wc-blocks-checkout] must be loaded in the footer, automatewoo-marketing-optin-editor-script was registered to load in the header, but has been switched to load in the footer instead. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5059
(anonymous) @ logo-collection/:197
```

This is the product page: https://ecom.corianderpho.blog/product/logo-collection/

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

The user can choose either to use theme Storefront or any newer themes (block themes)

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Rowling

![CleanShot 2024-02-21 at 16 53 53@2x](https://github.com/Automattic/themes/assets/14153300/26eedee4-7a9a-4d6f-bace-26c45b15a198)


📌 ACTIONS
- Requested author feedback

📌 Message to Author
@retnonindya those are very old themes that were developed pre-Atomic, so they don't explicitly declare WooCommerce support, and were never updated to do so, as far as I know.

I checked Rowling's files fbhepr%2Skers%2Sjcpbz%2Qcho%2Qgurzrf%2Sebjyvat%2S-og and compared to Radcliffe 2 (launched post-Atomic) fbhepr%2Skers%2Sjcpbz%2Qcho%2Qgurzrf%2Senqpyvssr%2Q2%2Svap%2S-og which has explicit WooCommerce support where the product pages load fine.

Did any of those themes used to work with Woo on your site? If you recall it worked before, we can keep it. If not, we can close as "by design" and open a Feature Request for the Theme Showcase to hide a8c themes without Woo support from the list if Woo is active.

**Comment by retnonindya** [comment]
Thanks for the ping, @liviopv! And yes, the classic themes are not Woo themes, so having them not displaying Woo products are expected. I'm going to close this issue.
