### ISSUE TITLE
List of issues with the Lettre theme

### ISSUE THREAD

**Issue by pkuliga** [Automattic/themes#7662]
Hi, I noticed some issues with the Lettre theme on https://pkuliganewsletter.com/.

This theme is pretty special because all of our customers creating the account from the Newsletter flow https://wordpress.com/newsletter/ have it enabled by default. That is why we would love those issues to get some attention.

- [ ] 1. Blog title has max-width 360px which looks bad
<img width="544" alt="Screenshot 2024-02-23 at 11 13 15" src="https://github.com/Automattic/themes/assets/4068554/073af583-b80d-4064-93a8-f151947c3a5e">
<br><br>

- [x] 2. No space between “Leave a Reply” and the comment form. Only for Atomic sites, the dedicated issue is here: https://github.com/Automattic/wp-calypso/issues/83991
<img width="672" alt="Screenshot 2024-02-23 at 11 15 04" src="https://github.com/Automattic/themes/assets/4068554/eebc49f9-de1b-4477-a88d-01000b93bf19">
<br><br>

- [x] 3. In navigation the About page is marked as active when I’m on the home page (previous attempt to fix this: https://github.com/Automattic/themes/pull/7167)
<img width="319" alt="Screenshot 2024-02-23 at 11 16 52" src="https://github.com/Automattic/themes/assets/4068554/1979a5e6-1de5-4241-8abc-6b3c0272808e">
<br><br>

- [x] 4. The “X” button in navigation is glued to the top of a page without any margin
- [x] 5. Search input on Archive page has no left padding and the text inside it looks weird. No padding controls for this block, dedicated issue: https://github.com/Automattic/wp-calypso/issues/68736
<img width="676" alt="Screenshot 2024-02-23 at 11 21 42" src="https://github.com/Automattic/themes/assets/4068554/2d24b5f1-355c-4aa0-85b6-f63ae4a5b8bb">
<br><br>

- [x] 6. Archive page after search has no home page link in the top-left corner. It’s quite hard to get back to the home page since navigation also doesn’t have link to it. Need to click the link in the footer…
- [x] 7. When no posts were found on the Archive page the page is blank. We should add some text there, e.g. “No posts were found” or sth like that
- [x] 8. This is how the nav looks on mobile, it’s glued to the top-right corner without any extra space
<img width="425" alt="Screenshot 2024-02-23 at 13 06 34" src="https://github.com/Automattic/themes/assets/4068554/aafee2a7-aa4c-4c9f-b31a-02dc1d8d599b">

**Comment by alaczek** [comment]
> Blog title has max-width 360px which looks bad

This one is a little tricky - the 360 max-width seems to be very deliberate here, matching the description and the subscribe box below. Your example is a bit of an edge case of a very long single word, but I agree that longer titles that get broken up into multiple lines will look off as well, and that's much more common. 

So in this instance we could:
* leave the max-width as is, and make the heading smaller (maybe use large font size instead of x-large?). I like this option, but changing the font-size would be a noticeable on existing sites, which we typically try to avoid. On the other hand bumping up the font-size back up would still be possible for anyone who prefers it.
* increase the max-width, although not by much (maybe to 400?) - I'm not sure how much of a difference this would make. 

@beafialho or @iamtakashi what do you think about this?

> No space between “Leave a Reply” and the comment form

This is a comment form issue separate from the theme, and happens only on Atomic. I already reported it here: https://github.com/Automattic/wp-calypso/issues/83991, but I could also push a CSS fix to the theme in the meantime.

> Search input on Archive page has no left padding and the text inside it looks weird

The search block has no padding controls ([reported here,](https://github.com/Automattic/wp-calypso/issues/68736) but little movement on the issue), so I might need to fix this with custom CSS as well.

I'll get on with fixing the rest :)

**Comment by alaczek** [comment]
> In navigation the About page is marked as active when I’m on the home page (previous attempt to fix this: https://github.com/Automattic/themes/pull/7167)

In my testing this only happens on Atomic - there's a CSS rule that overrides the theme. I can try adding `!important` and see if it helps 🫣

**Comment by pkuliga** [comment]
Thanks for the update @alaczek! Really appreciate it!

Added numbers to issues to make it easier to point them.

Ad 1. Don't bother with it if it's too tricky. My case is pretty special, not sure if it's worth addressing it. Activated this theme on my Simple site (https://pkuliga.wordpress.com/) and it looks fine there.

Ad 2. On my Simple site, it looks ok. Updated the list with your findings, thanks!

Ad 3. This is how it works on my Simple site when I'm on Home page (still broken 😕)

![2024-02-28 10 35 16](https://github.com/Automattic/themes/assets/4068554/2d5ade5c-fa1b-4d0c-93b9-6136135cbd0b)

**Comment by alaczek** [comment]
Ah yes, there is an issue with the nav on simple sites as well. I tried to fix it, but couldn't quite nail what's wrong. I tried a CSS fix, but I don't think it worked.

I merged and deployed the rest of the fixes.

**Comment by pkuliga** [comment]
Thanks!

My attempt to fix the nav issues: https://github.com/Automattic/themes/pull/7670

@alaczek can you take a look?

**Comment by alaczek** [comment]
Deployed! I think that concludes this issue?

**Comment by pkuliga** [comment]
Yup, I think we can close it. Thanks for your help!
