### ISSUE TITLE
Spearhead: [Bug] Loading Gutenberg JS on the frontend

### ISSUE THREAD

**Issue by sgomes** [Automattic/themes#7848]
### Quick summary

The Spearhead theme seems to be loading large amounts of Gutenberg JS on the frontend, which doesn't appear to be necessary.

### Steps to reproduce

Open a site using Spearhead and observe the loaded JS resources

### What you expected to happen

Gutenberg JS such as `blocks/index.min.js` should not be included

### What actually happened

Gutenberg JS is included

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Uncertain
- Tested on Atomic – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
Spearhead demo site:

![CleanShot 2024-06-10 at 16 13 34@2x](https://github.com/Automattic/themes/assets/14153300/eabc7096-4f20-4606-bc2d-c667b1200b3c)

TT4 Demo for comparison
![CleanShot 2024-06-10 at 16 17 47@2x](https://github.com/Automattic/themes/assets/14153300/54d4cd37-bac9-4d3b-ad1f-0b32d6440774)

Atomic site with Spearhead
![CleanShot 2024-06-10 at 16 18 12@2x](https://github.com/Automattic/themes/assets/14153300/3ce40570-a392-423e-8c10-3575680b055b)


📌 ACTIONS
- Triaged
- Requested author feedback

I'm not sure if I'm looking at the correct file, @sgomes, but a version of it is loading on all contexts I tested. In Spearhead on a simple site, it loads from `wp-content/plugins/gutenberg-core/v18.5.0-rc.1/build/blocks/index.min.js` but on TT4 and Atomic it comes from a different folder `/wp-content/plugins/gutenberg-core/v18.4.1/build/interactivity/index.min.js?ver=18.4.1`, which might what you're referring to.

Since you have a PR lined up, I'm going to mark this as triaged.
