### ISSUE TITLE
Organizer: impossible for block setting to override a hard-coded "posts per page" from theme template

### ISSUE THREAD

**Issue by lancewillett** [Automattic/themes#8002]
## Steps to replicate

Re: https://wordpress.com/theme/organizer -- theme `home.html` template sets posts per page to `4`

Code ref: https://github.com/Automattic/themes/blob/trunk/organizer/templates/home.html#L13

But as a user, when using Site Editor to change the settings -- using the home page template, the block sidebar visually 

1. Appearance > Editor
2. Click Templates, then click Blog Home in the grid
3. In the editor sidebar, template settings allows changing `Posts per page` to any number -- choose 12
4. Save, and reload — nothing changes, still 4 on home page (front end result is NOT 12 as expected)

<img width="305" alt="Screenshot 2024-08-07 at 14 33 47" src="https://github.com/user-attachments/assets/c8d19460-c472-48d6-87e9-939c6048f5b4">

Workaround — I hand-coded the 12 number in "Code Editor" in the JSON code and saved. 

## Result

Nothing changes, still 4 posts on homepage.

## Expected

Expect the block setting in the template editor to override the theme's template setting. That should be dynamic, no?

* User report: [8580751-zen]

**Comment by cuemarie** [comment]
Added to the One Board for PA triaging, thanks for reporting @lancewillett!

**Comment by lancewillett** [comment]
Possibly related? 

[Live-update the site preview when changing posts per page value · Issue \#54821 · WordPress/gutenberg](https://github.com/WordPress/gutenberg/issues/54821) and https://github.com/WordPress/gutenberg/pull/63358/files

I don't know enough yet about Site Editor enabled block themes — if this is a theme bug (not using a variable instead of hard-coded values in the template) — or if this is a core bug where inheritance of user settings isn't applying to templates.

**Comment by alaczek** [comment]
The Query Loop block has custom settings that can override what's in Settings > Reading (or in the Editor sidebar, which is the same setting).

Organizer is set up to display four posts only in that top section:
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/c62c25cd-bf8d-4ee6-827a-57b310650f9a">
This setting is only available in the floating bar in the editor, not in the block settings in the sidebar.

This gives theme authors lots of design flexibility, because we can put multiple query loops on a page to create more interesting designs, but on the flip side it is confusing for the customers. 

Since Query Loop blocks can override "Posts per page" setting, I'm thinking there should be a way to let the customer know that this is happening.

**Comment by alaczek** [comment]
I opened an issue here: https://github.com/WordPress/gutenberg/issues/64527

**Comment by lancewillett** [comment]
Thanks for the explanation and Gutenberg enhancement, Ola.

I'll close the loop with this customer for now.

**Comment by lancewillett** [comment]
User updated in [8580751-zen]

Closing this ticket as "solved."
