### ISSUE TITLE
[DotCom Launch]: Raconteur

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#8201]
### DotCom launch checklist

- [x] Create [demo site](https://raconteurdemo.wordpress.com/)
- [x] Create [theme showcase](https://theme.wordpress.com/themes/raconteur/)
- [x] Network activate
- [x] Launch theme

**Comment by iamtakashi** [comment]
There was an issue with some fonts in the theme, but now it's fixed. Once the theme gets deployed to WP.com, it should be ready.

**Comment by alaczek** [comment]
I noticed a few things about this theme that I want to make sure are intentional.
1. The left and right columns repeat on every page, but are not template parts - instead the same code is repeated in single.php, page.php, search.php, home.php - basically any pattern that corresponds to a template. Is there a reason for this?
2. There are subtle color changes between the home and internal pages - the site title and description are blue on home, but black elsewhere. Similarly, the right column is pink on home, while it has white bg elsewhere. Was this intentional?

Homepage:
<img width="1633" alt="image" src="https://github.com/user-attachments/assets/1290d33c-0e96-410c-b928-2e95bee4bb20">

Single post:
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/6a82b19b-c5b0-4cd0-af4c-1a5ea63962c4">

The overlay menu is also looking slightly different, plus longer items are not centre-aligned (see "Contact Form") 

Homepage:
<img width="1554" alt="image" src="https://github.com/user-attachments/assets/bd28380a-638c-416e-97ef-c439ba669adf">


Single page:
<img width="1551" alt="image" src="https://github.com/user-attachments/assets/7efd38b2-33fa-4a8b-aee4-1effb5b4bb8d">

Lastly, could we remove the copyright line "© 2024"?

I can open a separate issue for this if that helps.

**Comment by henriqueiamarino** [comment]
Thanks, @alaczek!
I have fixed the color discrepancies on all templates at this PR #8204 

Unfortunately, I don't know how to use patterns to display the alternate posts on the front page. If you think it is possible, please let me know how, and I'll fix this, too.

**Comment by alaczek** [comment]
Thanks for tackling the colors!

> Unfortunately, I don't know how to use patterns to display the alternate posts on the front page. 

Are you referring to this comment of mine: "The left and right columns repeat on every page, but are not template parts"? If so, I didn't mean the posts, I meant the thin sidebars/columns on the left and right  - these would ideally be reusable template parts, because they repeat on every page:

![Image](https://github.com/user-attachments/assets/c688b1c9-5b2a-47bd-9278-fc4a06a87791)

**Comment by henriqueiamarino** [comment]
Oh, right, I should have done that as my last task and forgot about it.
All templates now have column contents set as Header and Navbar, with the exception of the front page, which got a Navbar Home. This is working at #8204.

**Comment by iamtakashi** [comment]
@alaczek This should be ready to go after the latest updates get deployed to dotcom.
