### ISSUE TITLE
Page Templates: Default content for About page template

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#920]

**Comment by iamtakashi** [comment]
https://pagetemplatesandbox.wordpress.com/about-page/

**Comment by iamtakashi** [comment]
The testimonials being quotes from those people seem strange to me. They don't feel like testimonials anymore.

**Comment by ranh** [comment]
> They don't feel like testimonials anymore.

That's intentional. Open to discussion though of course :)

I went with generic quotes on the assumption that the "About" page template should apply to any type of site, whereas "traditional" testimonials – praise from customers – only apply to specific types of sites. 

I did include the term "testimonials" in the post content along with some general instructions for how to use them. And the title "What people say" should also reinforce that.
